### ISSUE TITLE
fmDNS - Add support for named.root

### ISSUE THREAD

**Issue by WillyXJ** [WillyXJ/facileManager#104]
When a server supports recursive lookups, automatically build/include named.root from http://www.internic.net/domain/named.root

**Comment by beza2000** [comment]
Hi!
fM Version : **3.0.2**
fmDNS Version : **3.0.3**
CentOS 7.x, SELinux = Enforcing, firewalld is on.
This feature does not work now.
If 'recursion yes' is defined in global or view options, the Preview Config does not work - the window opens and nothing happens, no preview.

**Comment by beza2000** [comment]
Does it work only when 'recursion yes' is defined in global options?
I try to define 'recursion yes'  only in view options and I have no the hint zone anywhere.
