### ISSUE TITLE
sub-dir install fails with non-apache httpd

### ISSUE THREAD

**Issue by hurricanerainbow** [WillyXJ/facileManager#107]
I follow the instructions as per the README, but still doesn't find <code>&lt;subdir&gt;/admin-modules.php</code> . The file isn't there, it's at <code>facileManager/pages/</code> . I have rewrite equivalents in the nginx conf.

Nor does the <code>php dns.php install</code> command work to find the same file.

<pre>
 location /fm/ {
        try_files $uri $uri/ @rewrite-fmdns;
    }
    location @rewrite-fm {
        rewrite ^ /index.php;
    }
</pre>

I have lots of experience installing this sort of thing, but this baffles me.

php-fpm errors out from it not finding the script.

BTW, thank you very much for writing this software, it's about time someone stepped up and did this :). It's very much appreciated :).

**Comment by peterschen** [comment]
I'm using facileManager as a subfolder under a certain domain. So this configuration might not exactly match your configuration but it works for me:

```
location ~ \.php$ {
                        try_files                               $uri $uri/ /fm/index.php?$args;
                        expires                                 off;
                        include                                 fastcgi_params;
                        fastcgi_pass                            dev;
                        fastcgi_param                           SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_split_path_info                 ^(.+\.php)(/.+)$;
                }
```

**Comment by WillyXJ** [comment]
@ericcotelnu - did the solution provided by @peterschen work?

**Comment by jisse44** [comment]
Hi
I have Nginx webserver OK with these parameters:

root /var/www/;

index index.html index.htm index.php index.cgi index.pl index.xhtml;

```
location ~ \.php$ {
	try_files $uri $uri/ /index.php?$args;
	expires off;
	include /etc/nginx/fastcgi_params;
	fastcgi_pass unix:/run/php/php7.3-fpm.sock;
	fastcgi_index index.php;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	fastcgi_intercept_errors on;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
}
```
