### ISSUE TITLE
security question

### ISSUE THREAD

**Issue by hart323** [WillyXJ/facileManager#122]
Correct me if I'm wrong. 
1) The only thing that protect unuthorized machine to build/read configuration is server SERIAL NUMBER?
2) Unuthorized machine can create unlimited bogus servers on fmdns server by spoofing SERIALS.
3) What is AUTHKEY, how to use it?

Thanks! Great product by the way!

**Comment by WillyXJ** [comment]
A global setting is now available to allow/disallow automatic client registrations.  This will be available in 2.0-beta1 and later.
