### ISSUE TITLE
feature: 'include' option

### ISSUE THREAD

**Issue by hart323** [WillyXJ/facileManager#123]
Hi!

We have a task to create a bunch of blank zones for blackholing.
Simple solution is to create file blocked.zones and include it in configuration like
include "/etc/blocked.zones";

**Comment by peterschen** [comment]
I'd like to see this feature included as well. In case you want to have a static zone which should not be touched by fmDNS the include feature would be really handy to accomplish this.

**Comment by mike2m** [comment]
Hi,
please do soon as possible, it is very necessary

**Comment by mike2m** [comment]
Hi,
include parameter supported in global and view options - not showing fmDNS in global and view options.
setup version: https://github.com/WillyXJ/facileManager/tree/2.1

**Comment by mike2m** [comment]
Hi,
sorry first installed from your site after a reinstalled here https://github.com/WillyXJ/facileManager/tree/2.1

**Comment by mike2m** [comment]
Hi,
please add $INCLUDE in domain options (zones->edit domain->Configure Additional Options->domain options)
link http://www.zytrax.com/books/dns/ch8/include.html

**Comment by WillyXJ** [comment]
Include statements are now supported in the next 2.x release.
