### ISSUE TITLE
server option for ipv6/ipv4 only

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#145]
Buried in /etc/default/bind9 is the option to turn ipv6 on or off. In our case, one of our bind servers is in a non-IPv6 capabale network and the log is filling up with network unreachable errors trying to reach IPv6 DNS servers. The option in /etc/default/bind9 (the same place where the user to run bind is set) also lets you specificy if you want IPv4 or IPv6 only. On this server for us, we want IPv4 only and set the option to 
     #OPTIONS="-4 -u bind"
There is an option on each server to select the run as user. Can there be an option to select IPv6/IPv4 only?

**Comment by WillyXJ** [comment]
After sitting on this request for a few years, I'm sorry, but it's still not within the scope of the project.
