### ISSUE TITLE
Upgrade Fails, and wrong error message is displayed

### ISSUE THREAD

**Issue by bigwillystyle42** [WillyXJ/facileManager#160]
I tried to upgrade my fmDNS module from 1.2.5 to 1.3.1 and it fails due to an error in my setup. I have the show errors option selected, so here is the error message it gives me:

Database error: [Unknown column 'domain_id' in 'where clause' | Query: [SELECT * FROM `fm_dns_soa` WHERE (`domain_id`='67' OR `domain_id` = (SELECT `domain_clone_domain_id` FROM `fm_dns_domains` WHERE `domain_id`='67') ) AND `soa_status`!='deleted']]

While that query might be failing, it's actually a much earlier one that really fails and would've been more helpful in diagnosing my mistake:

CREATE TABLE IF NOT EXISTS `fm_{$__FM_CONFIG['fmDNS']['prefix']}controls` (
  `control_id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL DEFAULT '1',
  `server_serial_no` int(11) NOT NULL DEFAULT '0',
  `control_ip` varchar(15) NOT NULL DEFAULT '*',
  `control_port` int(5) NOT NULL DEFAULT '953',
  `control_addresses` text NOT NULL,
  `control_keys` varchar(255) DEFAULT NULL,
  `control_comment` text NOT NULL,
  `control_status` enum('active','disabled','deleted') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`control_id`)
) ENGINE = MYISAM DEFAULT CHARSET=utf8;

That's from upgradefmDNS_1301(). When I migrated servers, I neglected to grant the correct privileges to the database user and fmDNS cannot currently create tables.

If there's anything you'd like me to test in upgrade.php let me know. I can leave my system like this for a while.

**Comment by WillyXJ** [comment]
v2.0 should now handle running the upgrades a lot better which should prevent the database from getting in a goofy half-upgraded state.
