### ISSUE TITLE
forward only | forward first

### ISSUE THREAD

**Issue by lgallard** [WillyXJ/facileManager#168]
Hi WillyXJ,

We are using facileManager for DNS purposes and we ran into a missing option in zone definition: forward only / forward first. As explained here http://www.zytrax.com/books/dns/ch7/queries.html#forward, if set to 'only' the server will only forward queries, if set to 'first' (default) it will send the queries to the forwarder and if not answered will attempt to answer the query.This statement may be used in a zone, view or a global options clause.

Although on facileManager you can set the forward option in view and options, there's no way to set it in zone. There should be a dropdown to choose between only and first when defining the zone as forward.

In our case we needed to use a forward only, so we solved the issue by changing this line in file classes/class_buildconf.php:

case 'forward':
            $zones .= "\tforwarders { " . $zone_result[$i]->domain_forward_servers . "};\n";

We added this:

case 'forward':
            // Added "\tforward only;\n" to force forward only behavior
            $zones .= "\tforward only;\n\tforwarders { " . $zone_result[$i]->domain_forward_servers . "};\n";

But it would be nice to have the option when defining a zone of type forward.

Best regards!

**Comment by WillyXJ** [comment]
This fix has been added to v1.3.5 which will be released in the next day or two.

**Comment by lgallard** [comment]
I really appreciate it. One more time, thanks!

**Comment by WillyXJ** [comment]
You're welcome - I'm glad you find it useful.
