### ISSUE TITLE
Ability to switch between 'DNAME' and 'FULL' clones

### ISSUE THREAD

**Issue by mdklapwijk** [WillyXJ/facileManager#169]
Currently fmDNS creates a zone with a DNAME record for each clone of a domain. This is not always desirable, because for example you're not able to receive email on those clones (CNAME/DNAME in MX is NO!).

The functionality I'm looking for is to be able to set a global mode to (dis)allow the use of DNAME for cloning. And furthermore the ability to override this behaviour on a per clone basis.

I think a lot of the core functionality (FULL/DNAME output) is already in place, since the code already switches to FULL-output once you add a MX record to the clone...

**Comment by mdklapwijk** [comment]
P.S. At this moment I add an A record 'clone' to the clones so it generates a full config for the clone.

**Comment by WillyXJ** [comment]
Interesting point and thank you for bringing it up.  I'll look into how this could be down by adding a checkbox to the fmDNS settings page and then another one in the zone config page.  I should be able to get this out with 2.0.

**Comment by WillyXJ** [comment]
Aside from mx records, what other scenarios would somebody not want to use a dname? I can't think of any and perhaps just checking for defined mx records and if they exist then don't use a dname otherwise use a dname.

**Comment by mdklapwijk** [comment]
Automatic checking would be a nice feature, but would result in almost never using DNAME. In most situations you (read I) want to receive email on the main TLD and the county TLDs the company is active in (or only home country TLD). So all other country TLDs which are only used for redirection to the main TLD would be perfectly fine as a DNAME.

Here is an (really old) piece on another reason not to use DNAME:
- http://blacka.com/david/2006/12/04/dns-dname-is-almost-useless/

**Comment by WillyXJ** [comment]
A global setting and a per-zone override are now available to allow/disallow automatic DNAME usage for cloned zones. This will be available in 2.0-beta1 and later.
