### ISSUE TITLE
Double MX records when adding MX records to a clone

### ISSUE THREAD

**Issue by mdklapwijk** [WillyXJ/facileManager#170]
If you add MX records to a clone to receive email for the cloned domain, the generated config switches from a DNAME-clone to a FULL-clone. But then just adds the new MX records to the FULL-clone resulting in double MX records (if the same are given as the parent).

**Comment by WillyXJ** [comment]
You can toggle the "Skip Import" tickbox for the MX records you don't want to be included in the clone.

**Comment by mdklapwijk** [comment]
Yes, that is a cleaner workaround than my 'lazy' add-a-bogus-A-record-to-the-clone solution (described in #168)...

**Comment by WillyXJ** [comment]
Correct me if I'm wrong, but this issue will be fixed with #169.
