### ISSUE TITLE
multiple strings in txt records for large DKIM key support

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#171]
Old DKIM keys with 768 bits fit fine in a standard text record, but 1024 and 2048 bit DKIM keys are larger than the 255 byte txt record. You can get around this by using the built in support for multiple strings within txt records in bind. 

https://kb.isc.org/article/AA-00356/0/Can-I-have-a-TXT-or-SPF-record-longer-than-255-characters.html

Can the UI be updated to handle this use case? IE, check if the proposed txt string is longer than 255, and if so, break it into multiple chunks less than 255 bytes each?

**Comment by WillyXJ** [comment]
Simple enough - Added to 2.0-beta1 and later.

**Comment by wispr** [comment]
Tested and confirmed resolved. Nice work!

**Comment by andrewhotlab** [comment]
Sorry to come back to this old issue, but it seems not to be completely solved to me. I just added a 2048 bit DKIM public key in a TXT record and all seemed to work (reloaded the zone from the GUI without errors). But the zone cannot replicate to slave servers and invoking named-checkzone manually returns this error:
> named-checkzone test.com db.test.com.hosts
> dns_rdata_fromtext: db.test.com.hosts:20: syntax error
> zone test.com/IN: loading from master file db.test.com.hosts failed: syntax error
> zone test.com/IN: not loaded due to errors.

Here is the line 20 (and next ones) of the zone file. You can see that the second payload is actually 256 character long (there is a space added in the end which breaks the rules):
>test._domainkey.test.com.      IN   TXT ("v=DKIM1; k=rsa; "
>"p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8m4+Bz29MvYo7uEEQhj&kzhmXIm7Qko80Lw41sKsxkQM1raySqwVyVN6pTYieLjprXpzq1qHU/ah5xzXxbud&yXXOdS+NmmMdSIpqvn340fU61OBR32t3lxtP6uRv2eoRKyIFzUugPCYKGURH+Auy&Fmfj/RVyTSqoIEmOIukoFQfuhb/4i9jfK6gDn0a9ajyrY+XlGBOkMvdJNE "
>"PSoTsV&6z9CB4jvjyXot59+yMTZhPV/wMtqziUoPG2frolNUvLh+vbz16OVlbzhUDejcJYa&TIFLOvdOEO8bgVuf0ljjwnT5vei4+ntqXFsRzTv47kLfxBpZpQrUkTm12guBTubM&GwIDAQAB")
>
I'm running facileManager 3.0.1 with fmDNS 3.0.1 over a nameserver running BIND 9.10.5-P1 on FreeBSD 10.3/amd64.

**Comment by WillyXJ** [comment]
@andrewhotlab - Thanks for the report.  I've verified this broke in v3.0.1 with a fix for other types of TXT records in 4b3e6f44cbe95c8eb30632b41d298e92fad681a9.  You can rollback to 3.0 until a fix is in place.  I'll need to revist the function to better account for a word split.

**Comment by WillyXJ** [comment]
@andrewhotlab - The fix will be included in the next release of fmDNS (3.0.2).  You can either wait until then or manually apply the commit (557e5b0).

**Comment by andrewhotlab** [comment]
Great! Thank you very much Willy!!

**Comment by wispr** [comment]
Confirmed broken (won't load the zone) in 3.0.1 and fixed in 3.0.2.
