### ISSUE TITLE
Generating new serial number: failed

### ISSUE THREAD

**Issue by linuxchuck** [WillyXJ/facileManager#172]
I have the server installed, and am trying to install the client on the same system.  The server web interface is up and running, and the fmDNS shows up as a detected module.  I don't yet see any way to configure or look at the module status from the admin web interface, but that may not yet be available until I register a client.

When I try to run the "dns.php install" command, it asks for the location of the facileManager interface, which I provide.  It finds the server, and checks account details successfully.

Next, it asks for me to enter the serial number for the server or to leave it blank for creating a new one.  I have tried both leaving it blank, and typing in random numbers.  Here are the results:

Just pressing enter:
------------output start----------------
Please enter the serial number for somefakeservername.com (or leave blank to create
new): 
  --> Generating new serial number: failed

Installation aborted. fmDNS is not an active module.
------------output end----------------

When I type in a serial number:

------------output start----------------
Please enter the serial number for somefakeservername.com (or leave blank to create
new): 2015012300
  --> Adding somefakeservername.com to the database...failed

Installation aborted. fmDNS is not an active module.
------------output end----------------

Where should I go from here?  Is there some sort of debug output I can get it to produce in order to determine where the failure is happening?

Thanks,
Chuck

**Comment by WillyXJ** [comment]
Hi Chuck,

After installing facileManager and the fmDNS module, did you activate the module at the "Modules" page as shown in the screenshot?

![image](https://cloud.githubusercontent.com/assets/1309591/5881981/b83a90e6-a302-11e4-8f46-1f4f81c8149b.png)

Once activated, the links will change signifying it's now active as shown:

![image](https://cloud.githubusercontent.com/assets/1309591/5882006/eb8fa1f2-a302-11e4-957b-751d6da1a371.png)

**Comment by linuxchuck** [comment]
Ah hah, I figured something was missing...  Here's my screenshot:

![facilemanager_no_activate_link](https://cloud.githubusercontent.com/assets/7502493/5882046/ac27b8b6-a30b-11e4-9a3d-84a051ab91aa.png)

I have no activate or uninstall link on the page.

**Comment by linuxchuck** [comment]
Agh!@  And now I see where I fail.

I don't have the required version.  I need to learn to pay better attention.  My apologies for wasting your time.  I'll find the beta and start from scratch...

**Comment by WillyXJ** [comment]
No worries.  2.0-beta1 isn't released yet, but alpha2 is albeit a bit buggy.  For your production environment, I would recommend running the stable release:

Download the full package or core from:
http://www.facilemanager.com/download/

If you downloaded the core, download fmDNS from http://www.facilemanager.com/modules/fmdns/.
