### ISSUE TITLE
allow-query

### ISSUE THREAD

**Issue by geckeon** [WillyXJ/facileManager#173]
Hi,
I think they are a problem with allow-query option.
When they are several subnets in this option, the webui display is correct with ";" but in database they are ","
So named.conf file is in error.
The good syntax is : allow-query {192.168.0.0/24; 192.168.10.0/24;}
But they are : allow-query {192.168.0.0/24, 192.168.10.0/24;}

I can modify the database but i think is beter to correct this.
Perharps see this class address_match_element

**Comment by WillyXJ** [comment]
What version of fmDNS do you see this on?

**Comment by geckeon** [comment]
I use http://www.facilemanager.com/download/facilemanager-complete-1.3.1.tar.gz
I can't test with git zip.

**Comment by WillyXJ** [comment]
I've been able to reproduce this with fmDNS 1.3.5 and the 2.0 pre-releases.  As a workaround until a fix is in place, you can create an ACL with those IPs/subnets and select only that ACL for allow-query.

**Comment by WillyXJ** [comment]
fmDNS 1.3.6 has been released with this fix.
