### ISSUE TITLE
Error Named checks

### ISSUE THREAD

**Issue by geckeon** [WillyXJ/facileManager#174]
HI,
I have this error message after update :
zone 77.168.192.in-addr.arpa/IN: NS 'dhcpTEST.77.168.192.in-addr.arpa' has no address records (A or AAAA)
zone 77.168.192.in-addr.arpa/IN: not loaded due to errors.

But the reserve zone don't need to have a A entry.

Geckeon.

**Comment by WillyXJ** [comment]
Hi,

All master zone files require NS and associated A records. Please ensure you have at least one of each and the zone file will load.

**Comment by geckeon** [comment]
It works better as well.
You can close this issue, sry.

**Comment by geckeon** [comment]
I have always an error in conf file : allow-query { 192.168.0.0/16,172.16.0.0/12; };
Your modification is ok in the webui but not in the database.
So i use an ACL.

thx
