### ISSUE TITLE
In PTR(RR) records SOA bug

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#176]
Hi,
please fix bug in PTR(RR) records SOA:

x.x.x.in-addr.arpa. IN SOA pd.x.x.x.in-addr.arpa. root.x.x.x.in-addr.arpa. (
		2015021600	; Serial
		15m		; Refresh
		1h		; Retry
		1w		; Expire
		5m )		; Negative caching of TTL

; Name servers
x.x.x.in-addr.arpa.         IN   NS   pd.domain.ru.

**Comment by WillyXJ** [comment]
Hi,

Could you please elaborate what the bug is?  I'm not seeing it.

Thanks.

**Comment by mike2m** [comment]
This bug appears when enabled Append Domain:

Serial Number	Auto Generated
Master Server	pd
Email Address	root
Refresh	15m
Retry	1h
Expire	1w
TTL	5m
Append Domain	 yes

**Comment by WillyXJ** [comment]
Hi,

This functionality is designed to allow the user to have the domain name automatically appended to the master server and email address, so this is not a bug in itself as the SOA in your example is supported by BIND.  However, even though this is not necessarily breaking any RFC's (best I can tell), reverse zone SOAs really shouldn't append the domain by best practice.  I'll consider removing the option in v2.0.

**Comment by mike2m** [comment]
Hi,
in a bind version 9.8.4 on Debian 7 such record does not pass

**Comment by WillyXJ** [comment]
SOA records for reverse zones can no longer append the domain to the master server and email address.  This improvement has been added to v2.0-beta2 and later.
