### ISSUE TITLE
Issue: Quotes around TXT records

### ISSUE THREAD

**Issue by bmssupport** [WillyXJ/facileManager#179]
Hi,
My DKIM TXT record is made up of multiple separated keys:
mail._domainkey.domain.com.     IN   TXT     "v=DKIM1;blah" "blah2" "blah3"

When adding this record to fmDNS it creates it in the zone with quotes on each end.
This causes a syntax error.

Removing these quotes manually to leave it as v=DKIM1;blah blah2 blah3 loads fine, but of course the quotes are put back on reload.

I can't seem to add quotes either so v=DKIM1;blah" "blah2" "blah3 doesn't work.

Am I just doing this wrong or is there another way to achieve this?

Thank you.

**Comment by WillyXJ** [comment]
Hi,

You should be able to specify it with semi-colons to delimit rather than quotes.  Such as v=DKIM1;t=s;p=blah;

Does this meet your requirements or is there extra functionality missing?

**Comment by bmssupport** [comment]
Thanks for the reply, sorry the break up is a single key, BIND allows it to be broken into multiple lines.
The quotes automatically added on each end still cause a syntax error no matter what.

Here is an example of a working key:
mail._domainkey.domain.com  IN  TXT ("v=DKIM1;"
"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDfl0chtL4siFYCrSPxw43fqc4z"
"Oo3N+Il220oK2Cp+NZw9Kuvg8iu2Ua3zfbUnZWvWK4aEeooliRd7SXIhKpXkgkwn"
"AB3DGAQ6+/7UVXf9xOeupr1DqtNwKt/NngC7ZIZyNRPx1HWKleP13UXCD8macUEb"
"bcBhthrnETKoCg8wOwIDAQAB")

I need to be able to insert this into fmDNS so it appears exactly as above in the BIND zone, at this stage I have not been able to successfully do this.

Thank you.

**Comment by WillyXJ** [comment]
Ah, the multi-line support in TXT fields. That's currently not supported and is an oversight which should be added in v2.0 once released.

**Comment by WillyXJ** [comment]
I think this is similar to #171 which I'm revisiting as I don't think that support quite worked as expected.  In short, with 2.0 you'll be able to add you DKIM key in a single line and fmDNS will automatically/correctly split it up into multiple lines when necessary.

**Comment by WillyXJ** [comment]
You can either wait for v2.0 to be released or you can test v2.0-beta2 and manually apply this commit.

http://facilemanager.com/download/?t=4
https://github.com/WillyXJ/facileManager/commit/19d02f18db1ee50dc571bbb8ed8a21eea9b0f115
