### ISSUE TITLE
Configurable user for ssh operations

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#182]
It would be great to have control over the user name which is used for ssh operations. Not all users are allowed to login via ssh and companies might have security policies in place and may maintain their users in a different place (e.g LDAP).

Therefor creating a local user might not be everyones favorite way of doing things.

**Comment by WillyXJ** [comment]
Thanks for the request.  I see your point, but I'm not sure how doable it is to maintain security of the system.  Correct me if I'm wrong, but using a ssh key with a LDAP account typically doesn't work well unless the user has already authenticated with a password.  Therefore, fM would need to specify a password with the ssh prompt which could be seen in the process list.  This is why a local account and key was chosen as the only option.  I'm all ears if you have an additional approach or information.

**Comment by peterschen** [comment]
The local user is not my concern. Only which user is used to connect to the remote systems is something I'd be interested in configuring. For now I changed the user in the code but that breaks upgrade scenarios in the future.

**Comment by WillyXJ** [comment]
User selectable SSH account will be a part of 2.0.
