### ISSUE TITLE
removal verification of zones

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#185]
When removing a zone, a popup comes up and says, "Are you sure you want to delete this item?" Can the word "this" in the popup box be replaced with the zone name that is being removed? Once you get a few zones in list, it becomes a bit more of a challenge to make 100% sure you're clicking the right delete button.

**Comment by WillyXJ** [comment]
Maybe.  Right now all deletes use the same jQuery function and that's where the confirmation prompt comes from.  Passing dynamic information will be more difficult especially when we're dealing with translations, too.  Leaving this open.

**Comment by wispr** [comment]
Makes sense. One of the other requests in to reverse a change would help with this in case some does delete the wrong zone.

**Comment by WillyXJ** [comment]
This will be included in 3.0-alpha2 and later.
