### ISSUE TITLE
zone template creation in v2.0RC2

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#186]
Cannot create a zone template in templates > zones. Goes through the wizard but doesn't submit the changes. You can create a template zone in zones > forward > new zone wizard and checking the box that say create template.

**Comment by WillyXJ** [comment]
Confirmed bug and is fixed in v2.0.

In 2.0-rc2, the template mistakenly gets created as a regular zone from templates > zones and requires the template name to pass zone name validation.  In 2.0, template names can contain illegal characters as it's just a friendly name.
