### ISSUE TITLE
creating a new zone with a template V2.0RC2

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#187]
When creating a new zone and selecting a template, it appears to create the zone in fmdns but it does not cause a build config to happen. Thus, even though the zones are in fmdns, they are not getting written to bind. Manually running a build config does not force the changes to bind.

**Comment by WillyXJ** [comment]
There seems to be some bigger issues that have been uncovered with this report.  For example, when creating a zone based on a template that has specific servers and/or groups defined, the zone is built on all servers and does not honor the template's servers.

**Comment by WillyXJ** [comment]
Code changes submitted and ready for 2.0 which addresses these issues.
