### ISSUE TITLE
Remove requirement for Apache

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#189]
When I tried to install facileManager to one of our production servers I noticed that there is a hard requirement for Apache as the installed modules are collected to ensure that mod_rewrite is enabled. It would be nice to have this limitation removed to be able to run facileManager with nginx.

**Comment by WillyXJ** [comment]
Starting with 2.0-rc1 there is support for non-httpd servers as the mod_rewrite check will be skipped if apache_get_modules() does not exist.  However, you'd be on your own for getting the proper rewrites working unless somebody can contribute them to the project (see #107).

**Comment by peterschen** [comment]
Cool. I need to have a look at 2.0 then.

**Comment by WillyXJ** [comment]
2.0 was released with this support.
