### ISSUE TITLE
Requirement Error when using virtual hosts

### ISSUE THREAD

**Issue by Vringe** [WillyXJ/facileManager#193]
I cannot use fM in a virtual host on apache2.

mod_rewrite is enabled.

I have set "AllowOverride All" in /etc/apache2/sites-available/default(-ssl) and also directly in my vhost file. I always get a requirement error. I also restarted apache2.

Do I have to do something else?

Regards,
Vince

**Comment by WillyXJ** [comment]
Hi Vince,

Which requirement error are you receiving?  Also, what does your virtualhost directive look like?

If you'd rather send that in an email for privacy, you may do so with support@facilemanager.com.

Thanks.

**Comment by WillyXJ** [comment]
The issue was related to a user ACL which did not allow the fM web server to access itself.
