### ISSUE TITLE
Is version 2.0 released, yet?

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#194]
Is the 2.0 version released yet? On the public web site I found two different versions for fmDNS - I'm a little confused :)

**Comment by WillyXJ** [comment]
Not yet.  2.0-rc2 is the latest non-stable release available.  2.0 is still under going bug fixes that were introduced in the 2.0 branch with hopes of releasing the stable version in the next week or two.

**Comment by peterschen** [comment]
Coo.. I'll try to give it a shot this week.

**Comment by WillyXJ** [comment]
2.0 stable has been released.
