### ISSUE TITLE
Support reverse subnet maps

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#195]
When public IP ranges are distributed mostly only subnets are assigned to one company/person and not full nets. In this case one might be only responsible for providing authoritative answers for PTR queries for certain parts of a network.

This common practice is described here: http://www.zytrax.com/books/dns/ch9/reverse.html

I noticed today that it is not possible to automatically create a PTR record when using reverse subnet maps. This would be a great thing to include.

**Comment by WillyXJ** [comment]
Added to v2.1.  Thanks for the request!
