### ISSUE TITLE
bad record SOA in reverse zone in second version (bad from first version)

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#196]
Hi, bad record SOA in reverse zone (Append Domain - yes)

XX.XX.XX.in-addr.arpa. IN SOA pd.XX.XX.XX.in-addr.arpa. root.XX.XX.XX.in-addr.arpa.

This problem was in the first version, the second version promised to correct, but not fixed.

Link old bad https://github.com/WillyXJ/facileManager/issues/176

**Comment by mike2m** [comment]
Hi, reinstall facileManager is normal SOA

**Comment by WillyXJ** [comment]
I see - the SOA will retain domain_append='yes' upon upgrade and will not let users change it.  Confirmed v2.0 bug.

**Comment by WillyXJ** [comment]
Fixed for 2.0. Thanks!
