### ISSUE TITLE
no change hostname name server to ip name server

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#197]
Hi,
not change hostname name server to ip name server in facileManager (fmDNS) 2.0

Regards

**Comment by WillyXJ** [comment]
@mike2m - could you please elaborate on what the issue is?  I was able to add a name server using fqdn and then change it to an IP address.

**Comment by mike2m** [comment]
Hi,
Edit hostname name server in menu fmDNS 2.0:
Config->Servers->Server Name 
change from pd (Hostname) to X.X.X.X(IP-address)
no change!

Sysrem:
Debian Wheezy
Mysql 5.5.41
Apache 2.2.22
PHP 5.4.36

**Comment by WillyXJ** [comment]
Ok, I had a bad test environment earlier.  I've reproduced this with 2.0-rc2 and verified it's fixed for the next release.  Thanks!
