### ISSUE TITLE
please add in options match-clients

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#198]
Hi,
please add in options match-clients

**Comment by WillyXJ** [comment]
@mike2m - the match-clients option is already supported in 1.3.x.  It can only be used in a view clause so you have to edit the options for the views.

**Comment by mike2m** [comment]
Hi, in version 2.0 not in options view match-clients, please add match-clients in options view

**Comment by WillyXJ** [comment]
This is indeed reproducible in 2.0-rc2.  The bug is any view- or zone-only options are not shown in the drop-down.

**Comment by WillyXJ** [comment]
Fixed for the next release.  Thanks!
