### ISSUE TITLE
Support $GENERATE records

### ISSUE THREAD

**Issue by WillyXJ** [WillyXJ/facileManager#2]
It would be nice to support $GENERATE records such as:

$GENERATE 1-10        IN     PTR     10-0-1-$.domain.com.
$GENERATE 1-10        web$.domain.com.     IN   A   10.0.1.$

**Comment by hklygre** [comment]
Are there any current plans to support/implement this?  (It's tagged with "1.2 release", which is a while back).

**Comment by WillyXJ** [comment]
Would like to, but still don't know how.

**Comment by mike2m** [comment]
Hi,

I read the link topic. And experimented, that's a very simple example, it can will help you to make the generator:

<?php
$value1="$.test.local";
$value="0-255";

$value=explode('-',$value);

for ($v = $value[0]; $v < 1 + $value[1]; $v++){
$value1 = str_replace("$",$v, $value1);
}
?>

**Comment by hklygre** [comment]
How about being able to bulk-generate the records (so they're stored as individual records, not as a GENERATE statement in the configuration)? This would "ease the pain" of transitioning to fmDNS. 

We have quite a few series of names (foo-switch-XXX, foo-ap-XX) - the IPs never change, so the $GENERATE statement in itself isn't necessary, just an easy way in BIND to accomplish this.

**Comment by paulospcosta** [comment]
Hi,
Its is what Ineed, but I don't understand if was implemented or not. 

To contribute you, I send two links how to delegate subnets in reverse zones.

The first is too simple, but I don't understand about programming.

http://www.netdaily.org/tag/29-classless-reverse-delegation-bind/

http://www.zytrax.com/books/dns/ch9/reverse.html

**Comment by WillyXJ** [comment]
Thank you for confirming. The feature is not yet implemented and I will close this issue as a duplicate and work off the original issue.

**Comment by WillyXJ** [comment]
With the release of [fmDNS 5.0.0](http://www.facilemanager.com/modules/fmdns/), there is support to add custom RR data where one could utilize the $GENERATE directive.

<img width="803" alt="Screen Shot 2021-12-23 at 2 04 44 PM" src="https://user-images.githubusercontent.com/1309591/147291347-86627507-cd46-45d1-a6c5-5f978a7bc8d0.png">
