### ISSUE TITLE
bind using old host files

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#200]
So one of our more active domains has a few different host files after a few changes. I'm not sure if/when they get created, but in our case the live version should be 11 but looking at zones.conf bind is loading an older version of the file, which naturally is breaking a few things.
![capture](https://cloud.githubusercontent.com/assets/7743948/7122059/8b58bc24-e1cd-11e4-906f-d4e275cb210c.JPG)
Thoughts on how to get it to use the most current version? Running 2.0RC2.

**Comment by WillyXJ** [comment]
Thanks for the report.  This was discovered earlier in 2.0-rc2 (albeit no issue was created) and a fix is in place for the next (imminent) release.

**Comment by wispr** [comment]
Great, thanks for the heads up Jon. We'll be looking forward to that update, we're kinda broken at the moment.

**Comment by wispr** [comment]
Jon, any way that we can manually work around this for the time being?

**Comment by WillyXJ** [comment]
I'm pretty sure you are using zone templates and law.net.11.hosts is based on the template.  This is the behavior I saw earlier and fixed it along with several other fixes.  If you need a fix now, I'd recommend breaking free of the template as the zone filenames should be correct during a reload/config build then.
