### ISSUE TITLE
Changing the SOA template doesn't mark zone to be reloaded

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#202]
When using SOA templates and selecting a new template and verifying it the change is persisted in the database but the zone is not marked for reload so the change is only pushed to the bind servers on a config build or manual reload.

When switching from a SOA template to custom SOA settings the changes are immediately noted and can be pushed.

**Comment by WillyXJ** [comment]
Confirmed bug in 1.3.6 and later.  Fix submitted for 2.0.  Thanks for the report.

**Comment by peterschen** [comment]
Thanks for the fix :smile:
