### ISSUE TITLE
placing notes on ACL IP's

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#206]
Thinking about ACL's to allow outside access to resources and that it would be handy to be able to put a comment in for each IP address that is in an ACL to note a customer, specific resource, etc, that needs access to the given ACL. Could be beneficial to use something like that zone UI to list each ACL entry with options, like enabled, disabled, comment, etc?

**Comment by WillyXJ** [comment]
I'm not sure I quite understand your last sentence - could you please elaborate?

Also, ACL entries can support comments in the comment box - is this not sufficient?

**Comment by wispr** [comment]
Correct, the ACL group can have a comment against all of the IP addresses that might belong to a given ACL. I'd like to see comments for each IP address or range inside of the ACL. Imagine a customer ACL list, with a dozen IP addresses in it. I'd like to be able to comment on each IP address with the customer name or code of who the IP address belongs to. 

The existing text box wouldn't allow you to enter a comment for each IP address. It'd need a new UI of some type for the ACL. In the perfect world in my head, you could reuse the existing UI from zone management and treat each IP address like an RR inside of a zone.

**Comment by WillyXJ** [comment]
Thanks for the clarification. I'll have to play around with this idea.

In the meantime, you could handle you comments similar to this idea:

![image](https://cloud.githubusercontent.com/assets/1309591/7282514/b274d8de-e8ed-11e4-8c49-a4a097cc8134.png)

**Comment by wispr** [comment]
The downside to the workaround suggested above is that we generally use the comment field for meaningful information on the main acl page so we can quicky scroll through the rules and know what each is for.

**Comment by WillyXJ** [comment]
I'm hesitant to expand the ACL page like you suggest as it may end up complicating several pieces.  However, would something like this work for your needs (if it were supported)?  I'm assuming you'll probably want to see your ACLs and comments all in one line. :)

![image](https://cloud.githubusercontent.com/assets/1309591/11577367/634f692e-99da-11e5-8439-4a84468d6899.png)

**Comment by wispr** [comment]
Yeah, that could probably work, but might make your life more
complicated....


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Reworked the approach and implemented a solution similar to the zones listing with clones.  Feature added to the v3.0 dev branch.  Will be available in 3.0-alpha1 and beyond.
