### ISSUE TITLE
Non-assigned zone config can be viewed by any user

### ISSUE THREAD

**Issue by Vringe** [WillyXJ/facileManager#210]
The url for previewing the config file is: https://example.com/preview.php?server_serial_no=-1&config=zone&domain_id=44

The domain_id can be easily changed to view an other config file which not must be assigned to the current user.

*Tested in 2.0*

**Comment by WillyXJ** [comment]
Confirmed along with viewing the full server config when the user is not privileged to.  These have been fixed in 2.0.1.
