### ISSUE TITLE
Request: Permit access by group

### ISSUE THREAD

**Issue by deklar** [WillyXJ/facileManager#211]
We'll be switching to the fantastic fmDNS package in the coming weeks. One option that is missing is the ability to allow zone access for an individual username based on a group (or even a view). 

For example, a customer of ours may host 500 domains, they need access to their DNS. Instead of adding 500 individual zone permits (which would be painful) it would be nice if we could group all of their domains together in a view (we can and will do this much) and then allow that user to access only those domains in that view. The same could be done if it was possible to assign a zone in a group, and simply allow a user to access that group.

It's not documented anywhere, however I did play with the fm_accounts/account_id table/fields. It appears to allow for a second, third, etc. instance of the same software - which is great, but not something that will work for us. I figured this was part of a future release or what not. 

Thanks

**Comment by WillyXJ** [comment]
Good request with a use-case.  This will probably be implemented with groups in fM instead of fmDNS views so other modules can leverage it.

**Comment by WillyXJ** [comment]
Group support has been added to the next v2.x release.
