### ISSUE TITLE
Connection with SSH

### ISSUE THREAD

**Issue by TheSkyHeart** [WillyXJ/facileManager#213]
Hi Guys,

I'm having trouble connecting through SSH, I generated the SSH Keys with fm_user and the user i use to connect is root, couldn't find a way to regenerate SSH for root.

when ever i try to connect I get SSH Connection Fail.

**Comment by WillyXJ** [comment]
It is not recommended to use the root user for security reasons, but if you insist, you probably have to enable root login via sshd_config (PermitRootLogin).  Also, the SSH user should be defined in the Global Options before running the installation script on the clients as the client installer will install the public key for the defined user.

If you want to regenerate the SSH key then you'd have to manually remove it from the fm_options table.

**Comment by TheSkyHeart** [comment]
Thanks for Replying Willy,

I would like to use the recommended way, so i guess i will use fm_user instead, do i need to create the user on the client machines? or the installer will create it automatically.

**Comment by WillyXJ** [comment]
The installer attempts to create the user if it does not already exist along with any necessary sudoers entries.

**Comment by TheSkyHeart** [comment]
I just reinstalled the client using the installer and it created the fm_user, but i'm still not able to get to work, below are the audit log 
type=USER_LOGIN msg=audit(1431807159.230:4490): user pid=23669 uid=0 auid=0 ses=497 msg='op=login acct="fm_user" exe="/usr/sbin/sshd" hostname=? addr=185.76.x.x terminal=ssh res=failed'

is there any log's to check on the server side?

**Comment by WillyXJ** [comment]
No, there are no server logs for authentication issues.  Does your client have any additional log entries for the authentication attempt (ie password rejected, key rejected, etc.)?  What OS and version is your client(s)?

**Comment by TheSkyHeart** [comment]
I'm using CentOS 6.6, and also cpanel DNS-Only installed on it.
below are the logs 

May 16 22:11:38 ns1 sshd[23668]: Did not receive identification string from 185.76.x.x
May 16 22:12:39 ns1 sshd[23669]: Failed password for fm_user from 185.76.x.x port 49921 ssh2
May 16 22:12:39 ns1 sshd[23669]: Failed password for fm_user from 185.76.x.x port 49921 ssh2
May 16 22:12:39 ns1 sshd[23670]: Connection closed by 185.76.x.x

**Comment by WillyXJ** [comment]
I'm surprised there are no entries regarding an attempt with a key.  Can you please send me the output of the following?

`ls -la /home/fm_user/.ssh`

Feel free to email support@facilemanager.com to take this request outside of the Git issue.

**Comment by TheSkyHeart** [comment]
there is no directory here is the output 

ls -la /home/fm_user/.ssh
/bin/ls: cannot access /home/fm_user/.ssh: No such file or directory

**Comment by WillyXJ** [comment]
It appears the home directory either does not exist or is in another location in your implementation.  The client actually parses /etc/passwd for the home directory so it does not rely on assumed locations.  Can you please send me the output of your installer session and also of `grep fm_user /etc/passwd` for my review?

**Comment by TheSkyHeart** [comment]
it's working now, I deleted the RAS Key form fm_options table and regenerated the key, then installed the client.
the .ssh folder doesn't exist cause i changed the value AuthorizedKeysFile	/etc/ssh/hosts/authorized_keys in sshd_config

but when i update i get this 
WARNING:  key file ( /etc/rndc.key ) exists, but using default configuration file ( /etc/rndc.conf).

**Comment by WillyXJ** [comment]
I'm glad to hear you got the SSH authentication working in your environment.  Regarding your update warning, this is not from fmDNS, but rather BIND (see https://deepthought.isc.org/article/AA-00722/0/Why-does-rndc-log-warning-key-file-...-exists-but-using-default-configuration-file-rndc.conf.html).
