### ISSUE TITLE
Unable to update hosts via http/s

### ISSUE THREAD

**Issue by iam8up** [WillyXJ/facileManager#214]
Error when trying to build/update via http(s):
It appears ($HOST) does not have php configured properly within httpd or httpd is not running.

This error is very useless and it would be great if there was more information to help troubleshoot!

I have the client running on the same CentOS 7 machine as the server.  I have enforced SSL, but the host is configured for https/443.

facileManager 2.0.1
php 5.4.16
mariadb 5.5.41
httpd 2.4.6
bind 9.9.4

Not sure what other information I can offer to help fix this problem.  This software is new to me and I am trying it for the first time today.  If you need anything else, please let me know.

**Comment by WillyXJ** [comment]
That error typically means reload.php is not being processes correctly on the client.  Could be the php module is not loaded or a docroot issue.  For http/s connections, the server will use the following URL to connect to the client with:

https://$HOST:port/fmDNS/reload.php

Please try the following from your server to see what result you get:

curl -k -v "https://$HOST:port/fmDNS/reload.php"

**Comment by iam8up** [comment]
It connects just fine, but I'm not sure what the page is supposed to look like:
http://pastebin.com/DXfnvCMU

**Comment by WillyXJ** [comment]
In your output, you are connecting to an IP directly.  Is your DNS server hostname changed within fmDNS to an IP address instead of the hostname? The fM server uses the DNS server hostname that's displayed in config-servers.php.  If the hostname is not defined as an IP address, please run the curl again with the hostname.

**Comment by iam8up** [comment]
That was part of my problem.  I set up an A record and it appears to get me a step further.  Changing to IP I continue to get this same new problem shown here:

http://i.imgur.com/KD3Vut8.png

**Comment by WillyXJ** [comment]
Ok, so first problem solved.  Second problem...

Could you please run the following on your client?  This will run the buildconf in debug mode so see more of where it's failing at.

`sudo php /usr/local/facileManager/fmDNS/dns.php -b -d`

I suspect this could be related to CentOS 7 as outlined in #215.

**Comment by iam8up** [comment]
Sure looks like it.  That command (build and debug?) ends with:

Reloading the server
The server is not running - attempting to start it
sh: /etc/init.d/named: No such file or directory

**Comment by WillyXJ** [comment]
Ok, thanks for your patience and pointing out this support issue with EL7.  I'll have to work on a fix to rollout in the next bugfix release.

**Comment by WillyXJ** [comment]
Closing as the original issue has been resolved.  #215 has been opened to address the second issue.
