### ISSUE TITLE
Cron (possibly http/ssh) update attempting /etc/init.d/named

### ISSUE THREAD

**Issue by iam8up** [WillyXJ/facileManager#215]
# /bin/php dns.php cron
sh: /etc/init.d/named: No such file or directory

With CentOS 7 (and likely other distros) there is no longer much use for /etc/init.d (specifically the lacking of /etc/init.d/named).  Rather everything has been moved to systemctl.

**Comment by WillyXJ** [comment]
Thanks for pointing out this support issue with EL7.  This will be addressed in the next bugfix release.

**Comment by WillyXJ** [comment]
Fixed in v2.0.2.
