### ISSUE TITLE
Cron not specifying location of dns.php

### ISSUE THREAD

**Issue by iam8up** [WillyXJ/facileManager#216]
The installer does this:
*/5 * * * * /bin/php php dns.php cron

This makes it impossible for the program to run unless it is in $PATH of which it is not.

Corrected it should say:
*/5 * * * * /bin/php php /usr/local/facileManager/fmDNS/dns.php cron

**Comment by WillyXJ** [comment]
This one is a bit strange as I haven't been able to reproduce it yet.  How did you execute the installer?  Did you use the full or relative path to dns.php?

**Comment by iam8up** [comment]
I did this:

php dns.php install

It should probably be documented that the command used to install it would carry to the cron entry IMO.

**Comment by WillyXJ** [comment]
The installer has been fixed in the upcoming v2.0.2 to account for being invoked via the relative path.
