### ISSUE TITLE
TTL field adding (PTR) records

### ISSUE THREAD

**Issue by iam8up** [WillyXJ/facileManager#219]
It would be nice to be able to copy/paste the TTL values instead of typing them all out.  It looks to me like alphabetical keys are blocked only allowing numbers.  Ideally it would let you type whatever but the field should go red and prevent submission if there is a problem.

**Comment by WillyXJ** [comment]
I see what you're reporting.  If you are copy/pasting, does that mean the import tool doesn't work for you?

**Comment by iam8up** [comment]
Honestly I'm not really understanding it the web interface.  I think the
whole template part is causing my problem.  With the lack of documentation
it's a lot of guess work =(

I have my named.conf working and it is what I'm used to.  It would be nice
if I could just take the named.conf and zone files and then upload it
having fM do all of the GUI stuff (ie put the config on the servers, create
a zone in the GUI using my zone config without using an existing zone to
replace).

On Fri, May 29, 2015 at 8:00 PM, WillyXJ <notifications@github.com> wrote:

> I see what you're reporting. If you are copy/pasting, does that mean the
> import tool doesn't work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WillyXJ/facileManager/issues/219#issuecomment-106964636>
> .
>



-- 
Josh Luthman

A patch in time saves kill -9
-http://www.tuxmaniac.com

**Comment by WillyXJ** [comment]
I'm sorry to hear the interface is not easily understood.  The goal of the project is to make it easy and intuitive (hence the definition of 'facile').  The use of templates are optional and they only allow zones to be based off of them if you have several zones with the same (or very similar) content.  Feel free to not use them especially while you learn the tool.

You can indeed import your BIND-compatible zone files (including SOA) into fmDNS using the Import tool (Admin -> Tools).  Just select the file to import and the zone file to import the records to.  There is currently no way of importing the named.conf file (#184) so you'd have to configure it using the pages under the Config menu.

I hope this helps!
