### ISSUE TITLE
Feature request - PTR generator

### ISSUE THREAD

**Issue by iam8up** [WillyXJ/facileManager#220]
It would be very convenient to be able to add large volumes of PTR records with assumed fields, ie:

1	IN	PTR	1.33.222.111.in-addr.arpa
2	IN	PTR	2.33.222.111.in-addr.arpa
3	IN	PTR	3.33.222.111.in-addr.arpa
4	IN	PTR	4.33.222.111.in-addr.arpa

For example, when a /20 is allocated from ARIN.  A form asking for the first three octects and a safe assumption of the rest (being 1 through 4 in this example).

At this time I'm doing it with notepad++ and regex.

**Comment by WillyXJ** [comment]
I believe this would ultimately be the same as #2.
