### ISSUE TITLE
Make update of /etc/sudoers optional

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#221]
As we manage our /etc/sudoers centrally (either by Ansible or LDAP) a local change of /etc/sudoers is not our desired behavior. Maybe we can make this change optional with the default to yes.

**Comment by WillyXJ** [comment]
Turning the creation of the sudoers entry into a global option shouldn't be too difficult to do.

**Comment by WillyXJ** [comment]
Add support in 2.1.
