### ISSUE TITLE
When a client node already exists entry should not be updated by install

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#223]
I have a configured node working with facileManager. When I run `php dns.php install` my settings for that node are overriden (root directory, cache directory, ...) even though they haven't changed. I would expect that the node in facileManager is not updated when a matching entry (with the same serial) was found.

**Comment by peterschen** [comment]
If the default behavior is to update the configuration a way to specify the configuration in the client (e.g. as a define in `config.inc.php`) would be great. This is actually one of the last things which prevent an automatic deployment of clients.

**Comment by WillyXJ** [comment]
Added a client install option of 'no-update' to prevent the client from updating the database.  This will go out with the next 2.x release.
