### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#224]
I have fm running on three different systems with a different combination of Apache, nginx, PHP-FPM, APC. For all the performance for rendering is not quite what I would like to have. I havn't drilled into this quite extensively but it seems that most of the time is spent for the first request and sending back the page.

On my production system (nginx, PHP-FPM, APC) I also used phpIPAM and with the same configuration and database it flies whilst fm feels sluggish.

**Comment by peterschen** [comment]
I had some time to look into this today. We have ~ 200 zones. I noticed that for every request made to the server two functions in `fm-modules/fmDNS/functions.php` are called: `getSOACount getNSCount`.

They are not called once but for every zone, whether it is displayed or not. I think there is a better way to achieve this as uncommenting the execution of the SQL statement results in much better performance already.

It seems that the performance degrades gradually with the amount of zones you keep. From my observations the abovementioned methods are called for every not deleted active zone.

**Comment by WillyXJ** [comment]
Both functions are required to ensure the zone can be built or reloaded which is why they are run against every zone.  As I work the other issues, I'll think about how the checks can be optimized.

**Comment by WillyXJ** [comment]
My test environment for resolving this issue includes ~180 forward zones with ~1400 records each and loading zones-forward.php would take ~13 seconds while showing all zones on a single page.

I've found the following:

- The query to pull zone record counts takes ~ 10 seconds.
  - After removing idx_record_account_id from fm_dns_records, the page load now takes ~3.5 seconds.  I haven't seen much performance gain by disabling the `getNSCount()` and `getSOACount()` functions.
- `session_start()` within `getLanguage()` takes ~1.4 seconds
- `getModuleBadgeCounts('zones')` takes ~1 second

Working on optimizing the above functions.

**Comment by WillyXJ** [comment]
Gained significant performance increases by:

* Adding another index to the fm_dns_records table
* Implementing better usage of `session_write_close()`
* Slightly decreasing the number of SQL calls

Fixes will be included in the next release.

**Comment by peterschen** [comment]
Sounds great. I'll give it a go when the next version is out.

**Comment by WillyXJ** [comment]
fM 2.1.1 and fmDNS 2.1.2 have been released and contain the performance improvements.

**Comment by WillyXJ** [comment]
@peterschen Is the performance still an issue in your environment with these changes?

**Comment by peterschen** [comment]
We're currently running 2.1.4. Loading the forward zones from the home screen takes little more than five seconds in total (see screenshot). 

Stats:
3 servers
223 forward zones 
6 reverse zones
~6 records per forward zone

Environment:
nginx 1.8.1
php-fpm 5.4.45-1~dotdeb+7.1
php 5.4.45-1~dotdeb+7.1
apc 	3.1.13

If there are some tweaks to be made I'd be happy to have them. All in all though I'm very happy with the product and the recent changes you incorporated.

![Performance](https://cloud.githubusercontent.com/assets/1166870/14225536/090352aa-f8c6-11e5-917b-d6e303bafa86.PNG)
