### ISSUE TITLE
Error in fmDNS 

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#225]
Hi,
on the Debian version 8 displays when the server is reload:
It appears {sitename} does not have php configured properly within httpd or httpd is not running.

https://yadi.sk/i/u_MoN7zLhKHWW

**Comment by WillyXJ** [comment]
Hi,

Sorry to hear of your issue. Please have a look at #100 to see if it's related to your setup and helps you to resolve it. If not, please let me know how your client is setup with Apache and we'll go from there.

**Comment by mike2m** [comment]
Hi,
I found the problem:
from /var/www/html
to /var/www
It works
