### ISSUE TITLE
client installation fails

### ISSUE THREAD

**Issue by octoberlast** [WillyXJ/facileManager#226]
Hi!

I'm trying to install fmDNS client and get the following problem:
----------------------------------
php /usr/local/facileManager/fmDNS/dns.php install debug
Welcome to the fmDNS installer.

Please answer the following questions and the necessary configurations will be performed
for you.

Please enter the location of the facileManager interface:
    Examples include:
	fm.mydomain.com
	fm.mydomain.com:8443
	mydomain.com/fm
	http://fm.mydomain.com/facileManager

Please enter the location of the facileManager interface: http://u528gw/facileManager
  --> Testing u528gw via https...failed
  --> Testing u528gw via http...ok
  --> Checking account details...

Installation failed.  Could not communicate properly with u528gw.  Failed to access
http://u528gw/facileManager/admin-accounts.php?verify.
-------------------

When I open http://u528gw/facileManager/admin-accounts.php?verify in the browser I get 
s:22:"Account is not found. ";

Tried to disable authentication but it didn't help at all. Any suggestions?
Thanks in advance

**Comment by WillyXJ** [comment]
That's interesting you've received that error as it would only fail if your fm_accounts table is empty.  Can you please verify you have an entry in that table?  The installer will add a 'default' account.

`SELECT * FROM fm_accounts`

**Comment by octoberlast** [comment]
Sure. Here's the output:
mysql> SELECT * FROM fm_accounts;
+------------+-------------+-----------------+----------------+
| account_id | account_key | account_name    | account_status |
+------------+-------------+-----------------+----------------+
|          1 | default     | Default Account | active         |
+------------+-------------+-----------------+----------------+
1 row in set (0.00 sec)


By the way, I've discovered another "bug". Ldap group option didn't work for me because fm doesn't get the group attribute option from the database. This extra line in fm-modules/facileManager/classes/class_logins.php fixed it:

if (empty($ldap_group_attribute))       $ldap_group_attribute   = getOption('ldap_group_attribute');

**Comment by WillyXJ** [comment]
Can you please provide your environment details so I can attempt to reproduce this problem?

**Comment by octoberlast** [comment]
It's a virtual vmware machine running RHEL 6.6 (apache 2.2, php 5.3.3, mysql 5.1.73). Please tell me if you need more details.

**Comment by WillyXJ** [comment]
What version of facileManager and fmDNS are you using?

**Comment by octoberlast** [comment]
It's 2.0.2 
I've tried both core and complete packages.

**Comment by WillyXJ** [comment]
This is an interesting one as so far I'm not able to reproduce it and that's a standard setup.  Could you please provide the output of the following that is run from your fmDNS client?

`curl -kv 'http://u528gw/facileManager/admin-accounts.php?verify'`

**Comment by octoberlast** [comment]
Of course!

* About to connect() to u528gw port 80 (#0)
*   Trying 10.17.200.103... connected
* Connected to u528gw (10.17.200.103) port 80 (#0)
> GET /facileManager/admin-accounts.php?verify HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: u528gw
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 26 Jun 2015 06:23:27 GMT
< Server: Apache/2.2.15 (Red Hat)
< X-Powered-By: PHP/5.3.3
< Set-Cookie: PHPSESSID=sak3641e7md3fk0gsqgoug2su7; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: myid=sak3641e7md3fk0gsqgoug2su7; expires=Fri, 03-Jul-2015 06:23:27 GMT
< Set-Cookie: myid=sak3641e7md3fk0gsqgoug2su7; expires=Fri, 03-Jul-2015 06:23:27 GMT
< Set-Cookie: myid=sak3641e7md3fk0gsqgoug2su7; expires=Fri, 03-Jul-2015 06:23:27 GMT
< Set-Cookie: myid=sak3641e7md3fk0gsqgoug2su7; expires=Fri, 03-Jul-2015 06:23:27 GMT
< Set-Cookie: myid=sak3641e7md3fk0gsqgoug2su7; expires=Fri, 03-Jul-2015 06:23:27 GMT
< Content-Length: 31
< Connection: close
< Content-Type: text/html; charset=UTF-8
< 

s:22:"Account is not found.
* Closing connection #0

**Comment by WillyXJ** [comment]
Hrm. The problem is not obvious and so far not reproducible.  Is it possible for me to gain access to your fM server and client so I can do some debugging with the code?  Feel free to email me at support@facilemanager.com.

**Comment by octoberlast** [comment]
I'm afraid it's not possible for the moment. I'm on vacation and will be back in 3 weeks. I will contact via mail then. Thank you!

**Comment by WillyXJ** [comment]
Were you able to get this installation sorted?

**Comment by octoberlast** [comment]
Yes. For some reason it didn't work with DNS names even though they were listed in /etc/hosts and resolved correctly.

**Comment by WillyXJ** [comment]
It's strange indeed, but glad to hear it's working for you.
