### ISSUE TITLE
Question $GENERATE

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#227]
Hi,
how to do so:
$GENERATE 0-255 $.1.15.in-addr.arpa.  86400  IN  NS  ns-1.cns.hp.com.

http://docstore.mik.ua/orelly/networking_2ndEd/dns/ch09_05.htm

**Comment by WillyXJ** [comment]
Hi,

$GENERATE is currently not supported. See #2.

**Comment by mike2m** [comment]
Hi,

I read the link topic. And experimented, that's a very simple example, it can will help you to make the generator:

<?php
$value1="$.test.local";
$value="0-255";

$value=explode('-',$value)

for ($v = $value[0]; $v < 1 + $value[1]; $v++){
	$value1 = str_replace("$",$v, $value1);
}
?>
