### ISSUE TITLE
Feature request : response-policy option

### ISSUE THREAD

**Issue by cahluor** [WillyXJ/facileManager#229]
Hello,

Would it be possible to support the "response-policy" option of bind ?

it looks like its just a matter of adding a line in table fm_dns_functions  like : 
  ('options', 'response-policy', '( quoted_string )', 'no', 'O', NULL, 'no'), 

but even if it should work for most usages I'am not quite sure of how the def_type should be.

**Comment by WillyXJ** [comment]
That entry is very close.  The following should work with the caveat there will be no error checking in the value you define when using the option and I believe the whole configuration would have to be defined in a single line with the current implementation of fmDNS.

INSERT INTO fm_dns_functions VALUES ('options', 'response-policy', '( string )', 'no', 'O', NULL, 'no');

More info on RPZ - http://www.zytrax.com/books/dns/ch7/rpz.html

**Comment by cahluor** [comment]
OK thanks, it works well

**Comment by WillyXJ** [comment]
Good to hear. I'd like to leave this open until it's been integrated into an official release.

**Comment by WillyXJ** [comment]
This has been added to the next v2.x release.
