### ISSUE TITLE
fmdns client cron mode issus

### ISSUE THREAD

**Issue by harryliu123** [WillyXJ/facileManager#232]
i have tree Name Servers , os is debin,centos,ubuntu
when i find Second Name Server added in fmdns server, first Name Server is changed linux release, 
 Config File,   	Config File ,   	Zones Directory, and Actions heppen "Client Install Required"

![1](https://cloud.githubusercontent.com/assets/7427806/8641482/8b045a18-2948-11e5-88bb-81630f6ed4ae.jpg)

**Comment by WillyXJ** [comment]
That's odd. Are you using unique serial numbers during the client installation?

**Comment by harryliu123** [comment]
Where can I see client  serial numbers ?
i use "facilemanager-complete-2.0.3.tar.gz" and run "php /usr/local/facileManager/fmDNS/dns.php install"
select "cron"

**Comment by WillyXJ** [comment]
There are two ways of viewing the serial numbers: 1. In the web interface under Config->Servers you can hover your mouse over the server names or 2. On the client you can view /usr/local/facileManager/config.inc.php. 

The expected behavior is for a client to only update its own record based on serial number and not to update any other server records (unless the serial number is not unique) however there should never be duplicate serial numbers.

**Comment by harryliu123** [comment]
i see web GUI two server have different hostname dns1,dns4
 /usr/local/facileManager/config.inc.php are "define('SERIALNO', 'dns1')" and define('SERIALNO', 'dns4')"
i thank its issus happen in server not client

**Comment by WillyXJ** [comment]
I think we've hit a bug with the client installer. The serial number field in the database is an INT(11) and if a user enters a non-integer value as a serial number during the client install, the serial number is stored as a 0 in the database. To overcome this for your environment, I would recommend deleting all three servers from the web interface, delete config.inc.php from all three clients, and reinstall the clients again. The difference though, is when the client asks for a serial number, leave it blank and a unique one will be generated.

**Comment by harryliu123** [comment]
You're right!!
my table name fm_dns_servers --> server_serial_no is "1"
i remove all dns server and re-add it ; it's OK
but os is Debian that  Config File , Server Root,  Server Root are wrong value; i change it 
Now everything is normal
thank you

**Comment by WillyXJ** [comment]
I'm glad to hear you are up and running now.  I'm leaving this issue opened to track the fix to the client installer.

**Comment by WillyXJ** [comment]
Client installer fix has been included in the next v2.x release.
