### ISSUE TITLE
new firewall server

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#236]
Setting up our first server in firewall management and having a hard time getting SSH updates to work correctly. This is the output from the install script. But fm server can't ssh into the box and the connectivity check fails on ssh. Tried removing the server and reinstalling it to generate a new key, but no love.

get updates via cron, ssh, or http(s) [c|s|h]? s
  --> Attempting to create system user (fm_user)...ok
  --> Installing SSH key...ok

  --> The sudoers entry already exists...skipping

Configuration file has been saved.

Installation is complete. Please login to the UI to ensure the server settings are
correct.

**Comment by WillyXJ** [comment]
Is the client firewall blocking inbound ssh from the fM server?

**Comment by wispr** [comment]
Turned off iptables for testing, still no joy.

Ping and remote port come back with success in the connection testing tool,
then it says ssh key login failed.


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Ok, I see your output shows the sudoers entry already exists on the client. Can you please send that to me? Also, when you run through the connection tests, what entries show up in your client system logs? This was supposed to be simple to use...

**Comment by wispr** [comment]
Correct, I had attempted the install once before and tried to remove it the
client and reinstall to test again. Only thing in the client log is this:

Aug 10 18:46:20 fmFirewall: Client installed successfully.
Aug 10 19:03:00 fmFirewall: Client installed successfully.

How can I verify the sudo entry for you?


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Sudo entry should be in /etc/sudoers or /etc/sudoers.d/99_fmFirewall

Also, are there any authentication entries in your /var/log/messages or /var/log/syslog files?

**Comment by wispr** [comment]
Defaults:fm_user  !requiretty
Defaults:fm_user  !env_reset
fm_user ALL=(root)      NOPASSWD: /usr/bin/php
/usr/local/facileManager/fmFirew$

The box is a centos box, nothing in /var/log/messages in regards to auth
and no syslog.


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Is this the complete line?

`fm_user ALL=(root)      NOPASSWD: /usr/bin/php
/usr/local/facileManager/fmFirew$`

There should be more of it.

**Comment by wispr** [comment]
Sorry, bad copy and paste.


Defaults:fm_user  !requiretty
Defaults:fm_user  !env_reset
fm_user ALL=(root)      NOPASSWD: /usr/bin/php
/usr/local/facileManager/fmFirewall/fw.php *




Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Sorry for the delay on this - I seemed to have lost it amidst the rest of the issues.

The sudoers file looks correct.  On CentOS, anytime a user logins it would be logged in /var/log/messages and/or /var/log/secure.  If there's no entry of even an attempt, then the username is not even being received.  You stated you disabled iptables for testing - do you happen to have another firewall between the two nodes that could be blocking ssh?

**Comment by WillyXJ** [comment]
I've found the issue in the client installer in that the SSH key would be incorrectly stored.  The fix will be included in v2.1.1.

**Comment by WillyXJ** [comment]
This is the same as #260.
