### ISSUE TITLE
Wrong cfgEntryFormat written to Bind config file (address_match_element)

### ISSUE THREAD

**Issue by dialsc** [WillyXJ/facileManager#237]
Hi,

I've got no glue if I'm just missing the know how but I just started to work with fmDNS (using the latest version available today) and ran into a problem. I tried to configure a list of allowed networks in the "options" dialog, the config name is e.g. allow-query.

As soon as I add more than one value to the option parameter, the configuration file created becomes invalid.

Example: Add two networks as the option value like this: 10.0.10.0/24 10.0.20.0/24
This becomes the following value in the options configuration file @ the server: allow-query { 10.0.10.0/24,10.0.20.0/24; };

You can add a couple more networks, they will all get seperated using commas instead of semicolons except after the last entry, there a semicolon gets included. It looks like this happens with all the option parameters which are of type address_match_element.

So, if I'm really just missing the knowledge how to do it, it would be cool if someone could tell me, plz. Otherwise I feel this could be bug.

Greez,

Dirk

**Comment by WillyXJ** [comment]
Hi Dirk,

I have confirmed this is a bug.  Until this is fixed, you can create an ACL with your entries and then add the ACL to the allow-query option as a workaround.

**Comment by dialsc** [comment]
Hi,

Thanks a lot for your very fast answer and the workaround!

Greez,

Dirk

**Comment by WillyXJ** [comment]
Code submitted and will be released with the next build.
