### ISSUE TITLE
facileManager 2.1 (fmDNS)

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#240]
Hi,
no create files zone slave "/etc/bind/zones/slave"
Regards

**Comment by WillyXJ** [comment]
Hi,

I don't understand this report.  Could you please clarify?  Also, there is no v2.1 so I'm assuming you mean 2.0.3.

Thanks.

**Comment by mike2m** [comment]
Hi,
this version https://github.com/WillyXJ/facileManager/tree/2.1
when you create a slave zone does not create directory "slave" and database files zones
Regards

**Comment by WillyXJ** [comment]
Hi,

I don't accept bug or feature reports from the 2.1 development tree.  I do accept bug/feature reports for the master branch as that is what the official releases are built from and I do accept pull requests for any branch.

Thanks.
