### ISSUE TITLE
Not create directory "slave" and database files zones

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#241]
Hi,
the same error, and in this version https://github.com/WillyXJ/facileManager (v.2.0.3)
when you create a slave zone does not create directory "slave" and database files zones

my system:
OS Debian 8
BIND9 9.9.5
Apache 2.4.10
PHP 5.6.9

Regards

**Comment by WillyXJ** [comment]
BIND should create the db files, but I do see the slave directory does not get created which would prevent BIND from creating its files.  Looking into a fix.

**Comment by WillyXJ** [comment]
This fix will be included in the next release.

**Comment by mike2m** [comment]
Hi,
Error Log:
Notice: Undefined index:server_serial_no in /var/www/html/facileManager/fm-modules/fmDNS/classes/class_buildconf.php on line 1633
