### ISSUE TITLE
In views no options recursion

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#242]
Hi,
In views no options recursion, please add recursion in views
Regards

**Comment by WillyXJ** [comment]
Recursion is already a valid option for views:

![screen shot 2015-08-20 at 9 32 28 pm](https://cloud.githubusercontent.com/assets/1309591/9400803/20321cee-4783-11e5-9587-9f82ad32682d.png)

Are you showing something different?

**Comment by mike2m** [comment]
Ok! thank
when downgrade from 2.1 to 2.0.3 this error...

**Comment by WillyXJ** [comment]
You are better off with a fresh install of 2.0.3.
