### ISSUE TITLE
It is too slow 

### ISSUE THREAD

**Issue by edenshen** [WillyXJ/facileManager#244]
When I visit the server via  http://example.com/facileManager and switch the menu and page,it is very too slow! 
I am Almost unbearable~Why is so?

**Comment by WillyXJ** [comment]
How many zones do you have? Issue #224 reported slowness with 200 zones.

**Comment by edenshen** [comment]
Just 3 zones only!
why?help~



139erc@163.com
 
From: WillyXJ
Date: 2015-09-16 20:34
To: WillyXJ/facileManager
CC: edenshen
Subject: Re: [facileManager] It is too slow (#244)
How many zones do you have? Issue #224 reported slowness with 200 zones.

**Comment by edenshen** [comment]
When I visit the http://example.com/facilemanager, I must connect to google to download picture and data?
I am in Chinaese!

**Comment by WillyXJ** [comment]
fM uses jquery, font awesome, and Open Sans font from remote sources.  I can look into packaging them with fM instead.

**Comment by edenshen** [comment]
how?when?

**Comment by WillyXJ** [comment]
This is included in v2.1-beta1 and later.
