### ISSUE TITLE
 “zones—forward”  the check box is lost!!!

### ISSUE THREAD

**Issue by edenshen** [WillyXJ/facileManager#245]
When I access “zones—forward” via http://example.com/facileManager/，I want to reload one of the zone/domain，but the check boxs is lost! I can't select one or more zones/domains, so I can't reload any zone/domain~

**Comment by WillyXJ** [comment]
Zone reloads are only available when the following criteria are met:

1. The zone has a SOA record
2. The zone has one or more NS records
3. The zone has been previously built with a server config build
4. The zone properties have not been changed
5. The zone has had one or more record changes

If all of the above is true then the zone is reloadable. If not, then the servers that host the zone will need their configuration built.

**Comment by edenshen** [comment]
Yes, all of above is ture, but I can't see the check box in  “zones—forward” 




139erc@163.com
 
发件人： WillyXJ
发送时间： 2015-09-16 20:40
收件人： WillyXJ/facileManager
抄送： edenshen
主题： Re: [facileManager] “zones—forward” the check box is lost!!! (#245)
Zone reloads are only available when the following criteria are met:
The zone has a SOA record
The zone has one or more NS records
The zone has been previously built with a server config build
The zone properties have not been changed
The zone has had one or more record changes
If all of the above is true then the zone is reloadable. If not, then the servers that host the zone will need their configuration built.

**Comment by WillyXJ** [comment]
You can try building your server config again.  This should reset the zone reload flags which should solve your problem going forward.

**Comment by edenshen** [comment]
It is not a good idea!

**Comment by WillyXJ** [comment]
Closing as this has not been reproduced.
