### ISSUE TITLE
unabled to build server config

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#246]
We've got 4 servers in fmDNS, one of them as started being unable to build a config. Nothing in /var/log/fm.log, nothing in syslog, apache, or anywhere else that I could find. What's the best way to dig into why the build is failing?

**Comment by WillyXJ** [comment]
You could try running the config build manually on the client in debug mode:

`sudo php /usr/local/facileManager/fmDNS/dns.php -b -d`

**Comment by WillyXJ** [comment]
Was a solution found as to why your build was failing?

**Comment by wispr** [comment]
Yes, sorry I did not update the ticket. It was an issue unrelated to fmDNS
ultimately, a changed NAT on a firewall.


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101
