### ISSUE TITLE
  user and groups management app will be very useful

### ISSUE THREAD

**Issue by zaxebo1** [WillyXJ/facileManager#247]
[feature Request , not bug]

an app for
(1) configuring user and groups (no LDAP, just plain /etc/passwd /etc/shadow etc ) 
(2) viewing and scheduling cron jobs across servers 
will be very useful

**Comment by WillyXJ** [comment]
Hi,

Have you considered using Puppet or Chef to manage accounts and cron jobs?  I would think they would be better suited than facileManager for those tasks.
