### ISSUE TITLE
support for naptr records

### ISSUE THREAD

**Issue by jostreff** [WillyXJ/facileManager#248]
Hi,
is't possible to add support for NAPTR records?

**Comment by WillyXJ** [comment]
I'm not familiar with NAPTR, but I'm reading the docs.  It's currently unclear to me if NAPTR RR are only supported in e164.arpa zones (which fmDNS currently does not support).  Any clarification is appreciated.

**Comment by jostreff** [comment]
My idea is to add support for LTE anvironment. Currently i'm also reading that part from different sources, because the standart is not well explained - http://www.lteandbeyond.com/2013/06/dns-in-evolved-packet-core-epc.html .

**Comment by WillyXJ** [comment]
Ok, I've added NAPTR support which will be included in v2.1-rc1 and later.
