### ISSUE TITLE
I wrote you about error in subject #241

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#250]
I wrote you about error but the answer and not from you https://github.com/WillyXJ/facileManager/issues/241#issuecomment-137229084
Hi,
Error Log:
Notice: Undefined index:server_serial_no in /var/www/html/facileManager/fm-modules/fmDNS/classes/class_buildconf.php on line 1633

**Comment by WillyXJ** [comment]
Which version of fmDNS is this from?

**Comment by mike2m** [comment]
Hi,
this version https://github.com/WillyXJ/facileManager/tree/2.1

**Comment by WillyXJ** [comment]
I only take bug reports on official releases that are published on www.facilemanager.com.  Anything else is incomplete code and errors/problems/bugs will exist.  Thanks.
