### ISSUE TITLE
Please add support file zone in secondary in the official release

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#251]
I wrote in one version of you told me that this version you do not support. I wrote at the other version, you have added this function in a version that is not supported, please add the support file zone in secondary in the official release:

Links:
https://github.com/WillyXJ/facileManager/issues/240#issuecomment-133170329
https://github.com/WillyXJ/facileManager/issues/250#issuecomment-144843249
https://github.com/WillyXJ/facileManager/issues/241#issuecomment-137229084

**Comment by WillyXJ** [comment]
I do this in my free time and I am not paid to write this software. Therefore, releases are built when I'm done adding features and fixing bugs and your previous requests are included in the code slated for the next release. However, they are not the only changes so please have patience or submit pull requests to speed up the development. Thanks.

**Comment by WillyXJ** [comment]
v2.1-beta1 has been released with these changes if you would like to test.
