### ISSUE TITLE
Unable to add whole IPv6 ranges in ACL

### ISSUE THREAD

**Issue by o1ramsky** [WillyXJ/facileManager#252]
Tried to add /64 in ACL and received below error:

2001:470:1f15:2d1::/64 is not valid

[facileManager v2.0.3]

**Comment by WillyXJ** [comment]
Thanks for the report - I'll have to figure out how to properly support it.

**Comment by WillyXJ** [comment]
Ok, this support has been added to v2.1-beta1 and later.
