### ISSUE TITLE
Bug: Underscores are allowed in A records

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#254]
Underscores seem to be allowed through to create an A record which BIND no longer supports. Had a quick look at the code and (I assume) it's this line:

/** Forward zones should only contain letters, numbers, periods, and hyphens */
                        return (preg_match("/^(_*[a-z\d](-*[a-z\d])*)(\.([a-z\d](-*[a-z\d])*))*$/i", $domain_name) // valid chars check

Which looks like it should invalidate underscores anyway but it doesn't seem to.

**Comment by WillyXJ** [comment]
Hello,

Which version of BIND dropped support for underscores in A records?  I'm not able to find it.  Underscores are not allowed in zone names, but they should be allowed in RR for domain keys and SRV records.

**Comment by Lormen** [comment]
It's only A records that BIND will fail to load on if there is an underscore: http://docstore.mik.ua/orelly/networking_2ndEd/dns/ch04_05.htm#FOOTNOTE-26

"WARNING: Underscores are not allowed in host names."

I am using the standard BIND 9.8.2 in the RHEL6.7 repos.

**Comment by Lormen** [comment]
This is what happens to BIND if you have an underscore in an A record:

Stopping named:                                            [  OK  ]
Starting named: 
Error in named configuration:
zone 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.1.11.in-addr.arpa/IN: loaded serial 2015111200
zone 181.25.10.in-addr.arpa/IN: loaded serial 2015101900
zone 3.17.172.in-addr.arpa/IN: loaded serial 2015102700
zone localhost/IN: loaded serial 0
zone 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 0.0.127.in-addr.arpa/IN: loaded serial 0
zone 181.25.10.in-addr.arpa/IN: loaded serial 2015101900
zone 3.17.172.in-addr.arpa/IN: loaded serial 2015102700
zone localhost/IN: loaded serial 0
/etc/named/zones/master/db.monkeys.co.uk.21.hosts:17: willy_xj_test.monkeys.co.uk: bad owner name (check-names)
zone monkeys.co.uk/IN: loading from master file /etc/named/zones/master/db.monkeys.co.uk.21.hosts failed: bad owner name (check-names)
zone monkeys.co.uk/IN: not loaded due to errors.
External/monkeys.co.uk/IN: bad owner name (check-names)
zone 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 0.0.127.in-addr.arpa/IN: loaded serial 0
zone 181.25.10.in-addr.arpa/IN: loaded serial 2015101900
zone 3.17.172.in-addr.arpa/IN: loaded serial 2015102700
zone localhost/IN: loaded serial 0
                                                           [FAILED]

If I remove the willy_xj_test.monkeys.co.uk entry then the zone loads correctly.

**Comment by WillyXJ** [comment]
Ah ha!  Upon further review, the underscore is not allowed in A, MX, SOA (except the email address portion), and NS records.  Thanks for additional information and bug report.

**Comment by Lormen** [comment]
Awesome! Hopefully this isn't too much work... Only bug that I've found so far and the only thing stopping it from going live :)

**Comment by WillyXJ** [comment]
If you don't want to wait for the next release with this fix (no date yet), you can enable named checks in the settings which should catch this (if check-names is set on the zone which it is by default) before the configs hit your DNS servers.

**Comment by Lormen** [comment]
I already had this enabled but it doesn't seem to make any difference sadly :(

**Comment by WillyXJ** [comment]
This is fixed in v2.1-beta1 and later.

**Comment by Lormen** [comment]
Confirmed that this now works as expected
