### ISSUE TITLE
Bug: server rebuild not changed to yes

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#257]
Again, only a small issue but I know how annoying it is when people update the same ticket for every issue, makes searching impossible!

If I add an option to a view selecting a single server then the server_build_config or server_update_config field is not updated to 'yes' so the new config cannot be built without forcing an update of the necessary servers.

**Comment by WillyXJ** [comment]
On a fresh installation, I just added two servers, created a view, added the SOA and NS records for the localhost zone and associated the view to it, and then performed a config build to clear all flags.  Then I went to Config->Views, clicked the view, selected server1 from the drop down, and added an option.  After clicking OK, I see in the UI server1 needs a config build and server2 does not.

Are there other steps required to reproduce your report?

**Comment by Lormen** [comment]
OK, servers were in a group "group1"
In a view called "internal" select "group1
add options for only group1 in internal
This didn't mention reloading
When I removed the option that I added it did however.

**Comment by WillyXJ** [comment]
Got it - thanks!  This is reproducible by selecting the server group.  This should get fixed for the 2.1 release.

**Comment by Lormen** [comment]
Excellent :-) Thank you!

**Comment by WillyXJ** [comment]
Fixed code submitted for the next release.
