### ISSUE TITLE
Possible bug: Login failed

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#258]
Bit of a weird one this one... Sometimes after a closed session (reboot etc) I can't get back into the GUI:
Login screen is shown, If I use an incorrect user/pass then it says it's incorrect. If I use a valid user/pass the page is simply reloaded.
The only way round this I've found is to get to the page through another domain (fmdns.some.domain.com, IP, server.domain.name). Once this has been used and no longer works it doesn't seem to be usable again... Very odd!

Is this a bizarre PHP variable that needs changing or something?

I also get "Unable to update the database" if I do a password reset which is very strange as the DB is totally accessible by FM (gets the username/email correct) and when it's in it happily updates the DB.

No idea about that one!

FYI - Although I am using the 2.1 beta this did happen in 2.0.3 as well.

Not sure how you would ever test this as it probably hasn't ever happened to you but here is the environment I am using:

RHEL6.7
PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33)
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
Server version: Apache/2.2.15 (Unix)
Server built:   Aug 18 2015 02:00:22

If you could shed any light on this that would be great!

**Comment by WillyXJ** [comment]
I have actually seen this behavior in one other EL6.7 environment and I have not been able to track down the source of the problem.  However, I have found that using an incognito browser window will allow authentication to work again.  It's a very difficult problem to solve as it's very intermittent and I actually haven't seen it for several months now.

Leaving this open until a resolution can be found.

**Comment by Lormen** [comment]
Oh, that's good (I guess) glad it's not just me :) ... It does seem completely random... Have you ever seen this issue in a Debian based environment? If it's something to do with RHEL then I have no issue moving (bosses permitting) as I prefer Deb/Ubuntu anyway...

**Comment by WillyXJ** [comment]
I have not seen or heard of this issue with Debian-based systems, but then again you are the first person outside of me that has reported it.  I was thinking it was an issue with my own production environment (I have not seen it in my dev/test environments which are RHEL-based) so it wasn't really looked into further.  However, now that there's a report from other users, it's on my radar a bit more.  I am curious to know if it's an issue outside of RHEL 6.x though.

**Comment by Lormen** [comment]
OK, I will ask the forces that be if I can set up a single machine just for the db/frontend and see if the problem goes away. Leave this open and I'll let you know.

**Comment by WillyXJ** [comment]
One correction - I've received a report of this through email from another user.  I've asked for the front-end environment details to see if there's any correlation.

**Comment by Lormen** [comment]
Hmmm... Yeah, if that was EL6 also then my guess would be something funny in the php5.3.3 that is currently the newest default version... Possibly something session/tmp based...

**Comment by Lormen** [comment]
Is there any chance you could write the server address into the session so that I can see the session differences? Then I can tell which one is which...

**Comment by Lormen** [comment]
OK, had a quick look and on sessions that work you get this:
s:10:"last_login";s:10:"1447955146";
and ones that don't:
s:10:"last_login";i:1447973839;

This probably means a whole lot more to you but it's what I've found.

**Comment by WillyXJ** [comment]
Solution found and submitted for the v2.1 release.  Thanks for the report and help.
