### ISSUE TITLE
Bug: SSH logins

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#260]
I don't know why I seemed to be one of the only people that had this issue but I had to do quite a bit of manual editing to get this working... 

When the installer was run it installed the authorized_keys file strangely:
/home/fm_user?/authorized_keys2
Which I found very odd...
Although it created (and uses) /home/fm_user the file still needed to be in 
/home/fm_user/.ssh/authorized_keys

I also had to make some manual adjustments to the /etc/sudoers/99_fmDNS file:

Defaults:facile  !requiretty
Defaults:facile  !env_reset
facile  ALL=(root)      NOPASSWD: /usr/bin/php fmDNS/dns.php *
Defaults:facile  !requiretty
Defaults:facile  !env_reset
facile  ALL=(root)      NOPASSWD: /usr/bin/php dns.php *
Defaults:apache  !requiretty
Defaults:apache  !env_reset
facile  ALL=(root)      NOPASSWD: /usr/bin/php /usr/local/facileManager/fmDNS/dns.php *

Are all the things that are needed (I changed the username to facile (don't like underscores))

I did this a few days ago so I can't remember if I needed all 3 lines (may have just been the last one that I added)

Not sure if it was only my set up but it took me a while to debug so if anything else it may help someone else.

**Comment by WillyXJ** [comment]
I've found the issue in the client installer in that the SSH key would be incorrectly stored. The fix will be included in v2.1.1.  This is the same as #236.
