### ISSUE TITLE
Feature Request: Ability to change View when adding options

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#262]
A second drop-down on the View-specific option page would be amazing! 

Going Views->External->drop to Group->"add option" etc and having to start the process again can take quite a while so having a second drop down with the Views next to the Groups/Servers would help speed things up a huge amount! 

Not important, would just be nice ;)

**Comment by WillyXJ** [comment]
Feature added to the v3.0 dev branch.  Will be available in 3.0-alpha1 and beyond.
