### ISSUE TITLE
Duplicate usernames for different auth schemes not allowed in 2.1

### ISSUE THREAD

**Issue by hklygre** [WillyXJ/facileManager#266]
I've had two users with the same username in FM, one with facileManager authentication, and one with  LDAP authentication.  After upgrading the server to 2.1.1 (from 2.0.3), that user could not log in using LDAP anymore.

I ended up manually renaming the user in the database (mysql update), allowing me to login with the LDAP user.

I'm not certain whether this should count as a bug in 2.0.x for allowing duplicate usernames to be created, or a bug in 2.1 for not ignoring users with a different auth scheme when logging in.

**Comment by WillyXJ** [comment]
This would be a bug in 2.0.x as duplicate usernames should not be allowed.  Nothing to fix as 2.1 works as designed with regards to user authentication.
