### ISSUE TITLE
Disabling DNS server gives "Uninitialized string offset" error

### ISSUE THREAD

**Issue by hklygre** [WillyXJ/facileManager#267]
FM 2.1.1, going to config->servers and hitting the "disable" (or "enable" for a disabled server) button gives the error "Notice: Uninitialized string offste: 0 in /path/facileManager/server/fm-modules/facileManager/functions.php on line 2129  Success".

The action is performed (but I have to reload the page to get rid of the popup), and on reload the server is marked as disabled.  Trying to enable again gives same behaviour - error popup, but action performed.

**Comment by WillyXJ** [comment]
Thanks for the report.  This behavior is only seen when "Show errors" is enabled in the settings.  This is fixed in the next bug fix release.
