### ISSUE TITLE
fmDNS 2.1: Building config gives Undefined index: server_serial_no

### ISSUE THREAD

**Issue by hklygre** [WillyXJ/facileManager#268]
After upgrading to 2.1.1, and pushing the updated client to the DNS servers, I'm getting "Notice: Undefined index: server_serial_no in /path/facileManager/server/fm-modules/fmDNS/classes/class_buildconf.php on line 1641".

Config appears to be built and pushed correctly.  Retrying (selecting the server and choosing 'build config' from the bulk actions menu gives same error.

**Comment by WillyXJ** [comment]
Thanks for the report.  I'm currently unable to reproduce this.

**Comment by WillyXJ** [comment]
With a different test environment I've been able to confirm this bug which is visible only when the "Show errors" setting is enabled.

**Comment by WillyXJ** [comment]
This issue is resolved in v2.1.2.
