### ISSUE TITLE
Bugs facileManager 2.1.2

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#269]
Hi,
please fix in facileManager 2.1.2 bugs see links to images:

https://yadi.sk/i/7afnIqqim4hSJ
https://yadi.sk/i/OY1JoUyOm4hSM
https://yadi.sk/i/QyzlExMym4hSR

**Comment by WillyXJ** [comment]
Thanks for the report.  The second issue with the domain being incorrectly displayed upon record updates has been confirmed and will be fixed in 2.1.3.  The other two issues will take more time to reproduce in order to find the source of the problem.

**Comment by WillyXJ** [comment]
All issues will be resolved in fM 2.1.2 and fmDNS 2.1.3.
