### ISSUE TITLE
Bug in ver. 2.1.3  in  zone options include statement 

### ISSUE THREAD

**Issue by mike2m** [WillyXJ/facileManager#270]
Hi,
in ver. 2.1.3 no work in zone options include statement (include "file-name";)

**Comment by WillyXJ** [comment]
It's not really a bug as it was left out by design. Why would you need to include a separate file within a zone clause outside of fmDNS?

**Comment by WillyXJ** [comment]
Confirmed bug.  Will be included in next bug fix release.

**Comment by mike2m** [comment]
Hi,
link to error (see image) https://yadi.sk/i/UmX65wQjm7qkD

**Comment by WillyXJ** [comment]
v2.1.4 contains the fix.
