### ISSUE TITLE
User rights and cloned zones

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#272]
Hi,
I need to manage access to users on cloned views, but i can't select thoses in zone list in users rights box, only master/forward zone are listed....
Is it just a bug on some expected behavior ?

Thank you very much
Louis C.

**Comment by WillyXJ** [comment]
Hi Louis,

This is the designed behavior.  There was never a use case where it made sense to allow access to a clone and not the parent.  Do you have such a case?

Thanks.

**Comment by lchanouha** [comment]
My use case is a security not a confidentality problem. I need to give to some users (technicians) access and records management permissions to the internal view which is in reality the cloned view delta added / removed records. 
But i can't let them alter the original public and critical zone because the impact of a some bad action could be very (too) important.
Sorry for the langage,  i'm not a english native speaker...


---- WillyXJ a écrit ----

**Comment by lchanouha** [comment]
Too bad, so i will need to find manually a workaround on this and alter the code for our DNS safety.
I can't pick proper rights to let technicians access only to cloned zone (for internal views) and keep right to original zone only to me (public view - critical).

**Comment by WillyXJ** [comment]
Thanks for the use case.  I'll see how this can be supported for v2.2 or 3.x.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this improvement.
