### ISSUE TITLE
CNAME with append domain seems to append to value aswel.

### ISSUE THREAD

**Issue by mdklapwijk** [WillyXJ/facileManager#273]
Just noticed whilst upgrading from2.0 beta to 2.1.3 that the domain gets appended to the set value aswel:
```
 ; Aliases
 www.domain.com.          IN   CNAME   www.domain.com.cdn.cloudflare.net..domain.com.
```

**Comment by mdklapwijk** [comment]
This solves my direct problem, not sure why one would want to add the domain to the value though?

./fm-modules/fmDNS/classes/class_buildconf.php:
```
                                        case 'CNAME':
                                        case 'DNAME':
                                                $record_array[$record_result[$i]->record_type]['Description'] = 'Aliases';
                                                //$record_value = ($record_result[$i]->record_append == 'yes') ? $record_result[$i]->record_value . '.' . $domain_name_trim . '.' : $record_result[$i]->record_value;
                                                $record_value = $record_result[$i]->record_value;
                                                $record_array[$record_result[$i]->record_type]['Data'][] = $record_start . $separator . $record_value . $record_comment . "\n";
```

**Comment by WillyXJ** [comment]
Appending the domain is actually for the record value and not the record name.  fmDNS will always append the domain for the record name, but appending the domain name to the value may or may not be desired.  For example, users may want test.domain.com to resolve to www.domain.com and in that case you would choose to append the domain for the record.  But, in your example record, you would not want the domain appended so you would choose not to append the record.  If you updated the option in the web interface for the record to "no", then the domain will not be appended when building the zone file.

**Comment by mdklapwijk** [comment]
Hi Willy,

Yes I understand, but when one sets the append toggle to 'no' fmDNS also does not append to the record column aswel. Which results in the following config:
```
; Aliases
 www          IN   CNAME   www.domain.com.cdn.cloudflare.net.
```

You could manually add the domain to the record column, but then you would get the following in the clones of that zone (test is with append=yes):
```
...
; Aliases
 www.domain.com          IN   CNAME   www.domain.com.cdn.cloudflare.net.
 test.domain.com          IN   CNAME   test.domain.com.
...
; Aliases
 www.domain.com          IN   CNAME   www.domain.com.cdn.cloudflare.net.
 test.domain.net          IN   CNAME   test.domain.net.
...
```

So we'd probably need an extra toggle/switch which does either "append domain to value aswel" or "do not append domain to value". Or even better a 3-way toggle "record only", "record+value" and "no".

If you want I could add this and sent you a pull request.

**Comment by mdklapwijk** [comment]
Sorry, ignore my last comment. It is not fmDNS which is responsible/needed for adding the domain to the record column, Bind will add it on its own (when it answers the actual request)!

I probably ran into problems, because of changes between 2.0beta and 2.1.3 handling this differently and my config already having that entry with "append domain" set to "yes".

Sorry for wasting your time!

**Comment by WillyXJ** [comment]
No worries - I'm glad it's working for you.
