### ISSUE TITLE
Function verifyName should ignore disabled records

### ISSUE THREAD

**Issue by mdklapwijk** [WillyXJ/facileManager#274]
While correcting my zone after I ran into https://github.com/WillyXJ/facileManager/issues/273, I noticed the following:
- If one tries to add a CNAME for a record which already exists as a disabled A record, the record is labeled invalid.

I think this is caused by verifyName in zone-records-validate.php, which seems to be responsible for enforcing unique/sigleton records, but does not notice the 'disabled' bit on a existing record...

**Comment by WillyXJ** [comment]
The fix is ready for the next bugfix release.
