### ISSUE TITLE
Inherit zones

### ISSUE THREAD

**Issue by yanky83** [WillyXJ/facileManager#275]
Lots of times, one has to manage multiple zones with the same entries, e.g.:

test.com
test.net
test.org

It would be awesome to have a feature, which allows to inherit from zones.

It can currently be done with templates, but this is a different use case imho.

**Comment by WillyXJ** [comment]
One of the original features of fmDNS is to support this very thing through the use of clones. You just need to create a parent zone, and then your subsequent zones can be created as a "clone of" the parent. For example:

1. Create test.com
2. Either click the + to add a new zone and select test.com from the "clone of" drop down or click the clone button next to test.com to automatically create a clone of it - define the zone as test.net and repeat for test.org

Please let me know if this does not accomplish what you are looking for.

**Comment by yanky83** [comment]
Thanks for the quick response.

The problem about cloning (as I understand it) is, that updates to the original do not get propagated to the clone(s), do they?

**Comment by yanky83** [comment]
Never mind, works just perfect ... my apologies :)
