### ISSUE TITLE
Automatically create slave zones

### ISSUE THREAD

**Issue by yanky83** [WillyXJ/facileManager#276]
A hidden master is used on a quite regular basis. It would be nice to be able to create a template, which can automatically create master records on a given server, and identical slave records on given (different) servers.

Thanks.

**Comment by WillyXJ** [comment]
Look into using server groups as you can define master and slave servers which should accomplish what you are looking for.

**Comment by yanky83** [comment]
Perfect!

My apologies for missing this!

I think fmDNS is a very good tool, but it could use some more advertisement, to make people more aware of its really good functionality :)
