### ISSUE TITLE
Link forward records stronger to their reverse records

### ISSUE THREAD

**Issue by yanky83** [WillyXJ/facileManager#277]
When I create a forward record, I get the option to create a PTR record. It would be really helpful to have an option to delete the reverse record on deletion of the forward record (and potentially the opposite as well), and/or have an option to point out orphaned records (records without according reverse entry)

Should a feature like this already exist, Id appreciate to be pointed at it.

Best regards

**Comment by WillyXJ** [comment]
Thanks for the request.  Hopefully I can incorporate this into v3.x.

**Comment by WillyXJ** [comment]
This is now implemented in fmDNS v3.0-alpha2 and later.

**Comment by yanky83** [comment]
Thanks a lot!
