### ISSUE TITLE
Master Slave Configuration

### ISSUE THREAD

**Issue by edwinmhondiwa** [WillyXJ/facileManager#279]
Greetings to you all, good software you have built for the community. I have built facileManager 2.1.3 client/server and everything works fine. Configured a second machine as client, also created a group for the two servers. I want the zone files transferred to the other machine, but i'm stuck. Any help would be appreciated. My OS is FreeBSD 11, BIND 9.9.8-P2 and FAMP.

**Comment by WillyXJ** [comment]
Hi,

Could you please provide more details on where you're stuck?

**Comment by edwinmhondiwa** [comment]
Thnx for the quick response. I did not know what else to do after configuring the second box. But here is what i have done.  1. I configured another zone template, zone type->slave. Populated the masters field with the IP Address of the master, on the DNS Servers field i selected the would be slave server from the drop down menu. 2. On the zone files menu, i cloned one of the domains, selected my newly created template and maintained the domain name. After rebuilding the configs i can now see that there is transfer. Please comment on my procedure.

**Comment by WillyXJ** [comment]
It's hard to comment as I don't quite know what you are trying to accomplish nor fully understood the steps you took.  If you are just looking to configure a master server (server1) and a slave server (server2), all you need to do is create a server group with server1 in the masters list and server2 in the slaves list.  Then create your master zones with All Servers or your server group associated as the DNS servers and you should be set.

**Comment by edwinmhondiwa** [comment]
Thank you very much, i used your method and it works. facileManager rocks.  I hope it will allow me to add more slave servers.

**Comment by WillyXJ** [comment]
Great! You can add as many masters and slaves as you'd like to each group.
