### ISSUE TITLE
Zone Import should ensure singleton RR

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#280]
We can add for example both A and CNAME records for one subdomain. 
This will trigger an error on bind and zone won't be reloaded. And worse if you restart the server your zone won't work anymore / no resolution.

A protection againts this kind of collpasing would be great to prevent some user errors.

**Comment by WillyXJ** [comment]
Hello,

As of v2.1, this is in place per #208 - is this functionality not working for you?

**Comment by lchanouha** [comment]
Yes it didn't worked. I got 1 cname and 1 a records for same domain. 
I imported my records via the zonefile import tool. Maybe there is no verifications on raw import ?

**Comment by WillyXJ** [comment]
Ah, the zone import does not check for singleton RR.  The import tool assumes the user is importing loadable zone files.  This will need to be fixed.

**Comment by WillyXJ** [comment]
This fix will be in the next release.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this fix.
