### ISSUE TITLE
ACLs names should be quoted in bind configuration files

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#281]
Hi
I got another use case where i got  unusable bind configuration files.
 
I created an ACL "test test"
and a rule "match client" where i set for value "! test test"

In my named.conf.local i get this line which is incorrect.

match-clients { !test test; };

Another solution could be to disallow spaces in acls names.

Thanks for your work.

**Comment by WillyXJ** [comment]
Thanks for the report - this is a confirmed bug.

**Comment by lchanouha** [comment]
That was very fast (i just patched my installation).
As a PHP developper too i'm impressed of the quality of your work and motivation !

Hope i will get some time one day to contribute on such project !

Regards
Louis.

**Comment by WillyXJ** [comment]
This was resolved in fmDNS v2.1.6.  Closing.
