### ISSUE TITLE
Upgrade Problem

### ISSUE THREAD

**Issue by sport80** [WillyXJ/facileManager#282]
Hi,

I've tried to upgrade my facilemanager installation v.2.0.3 but I have some problems, it did't upgrade!

In the apache error log file it appears:

[Tue Jan 12 18:49:03 2016] [error] PHP Notice:  Undefined index: module in /var/www/fmanager/fm-modules/facileManager/functions.php on line 3057, 
[Tue Jan 12 18:49:03 2016] [error] PHP Notice:  Undefined index: module in /var/www/fmanager/fm-modules/facileManager/functions.php on line 3057
[Tue Jan 12 18:49:03 2016] [error] PHP Notice:  Undefined index: module in /var/www/fmanager/fm-modules/facileManager/functions.php on line 3057
[Tue Jan 12 18:48:14 2016] [error] PHP Warning:  include(): Failed opening '/var/www/fmanager/fm-modules//ajax/functions.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/fmanager/fm-modules/facileManager/ajax/getData.php on line 28
[Tue Jan 12 18:48:14 2016] [error] PHP Warning:  include(/var/www/fmanager/fm-modules//ajax/functions.php): failed to open stream: No such file or directory in /var/www/fmanager/fm-modules/facileManager/ajax/getData.php on line 28
[Tue Jan 12 18:48:14 2016] [error] PHP Notice:  Undefined variable: fm_name in /var/www/fmanager/fm-modules/facileManager/ajax/getData.php on line 28

and the upgrade database show this error:

Can't DROP 'domain_id'; check that column/key exist | Query:[ALTER TABLE `fm_dns_config` DROP INDEX domain_id, ADD INDEX `idx_domain_id`(`domain_id`)]

My installation works on Ubuntu 12.04 server

Thank you very much

**Comment by WillyXJ** [comment]
Are you upgrading to facileManager 2.1.3 and fmDNS 2.1.6?

In addition, if you have not rolled back your database yet, can you please provide me the output of the following MySQL query?

```
SELECT option_name, option_value  FROM `fm_options` WHERE `option_name` IN ('fm_db_version', 'version');
```

**Comment by sport80** [comment]
Yes, i've tried to upgrade to the lastest version.

I've not rolled back the database, the query result is:

option_name         option_value
fm_db_version	      43
version	              2.0.3

**Comment by WillyXJ** [comment]
I just installed a 2.0.3 environment and successfully upgraded to 2.1.6 so something's not quite right with your database.  The upgrade failed while modifying the indexes for fm_dns_config in upgradefmDNS_2101().  Could you please provide me with the output from the following SQL statements?  I'd like to review your indexes and see how we can get you fixed up.

```
SHOW INDEXES FROM `fm_dns_config`;
SHOW INDEXES FROM `fm_dns_domains`;
SHOW INDEXES FROM `fm_dns_functions`;
SHOW INDEXES FROM `fm_dns_records`;
SHOW INDEXES FROM `fm_dns_records_skipped`;
SHOW INDEXES FROM `fm_dns_servers`;
```

**Comment by sport80** [comment]
ok, here the results:

[query_facilemanager.txt](https://github.com/WillyXJ/facileManager/files/88031/query_facilemanager.txt)

**Comment by WillyXJ** [comment]
For some reason your fm_records_skipped table didn't have any indexes and so the upgrade failed at that point.  In order to get a successful upgrade, you have two options:

1. Edit fm-modules/fmDNS/upgrade.php and comment out lines 1435 - 1440.  Then change line 1441 to be as follows:
```
	$table[] = "ALTER TABLE `fm_{$__FM_CONFIG['fmDNS']['prefix']}records_skipped` ADD INDEX `idx_record_id` (`record_id`)";
```
Then run the upgrade process again.

OR

2. Run the attached SQL statements and then run the upgrade process again.

[sport80_upgrade_fix.txt](https://github.com/WillyXJ/facileManager/files/88074/sport80_upgrade_fix.txt)

**Comment by sport80** [comment]
yes, i confirm, the upgrade now has worked correctly. Thank you very much. I've used your sql in attachment and then run the upgrade. Do you need that i make some check to you to verify that all worked correctly?

**Comment by WillyXJ** [comment]
Excellent news.  Would you be able to send me a mysqldump of just the database/table structure (I don't need any data)?

**Comment by sport80** [comment]
Sure, here the dump :+1: 
[fmanager_structure.zip](https://github.com/WillyXJ/facileManager/files/88150/fmanager_structure.zip)

**Comment by WillyXJ** [comment]
There are two things that are incorrect.  Please run the following SQL statements and then you'll be all set!

```
ALTER TABLE `fm_dns_records_skipped` ADD PRIMARY KEY (`skip_id`);
ALTER TABLE `fm_dns_soa` DROP INDEX `domain_id`;
```

**Comment by sport80** [comment]
#1072 - Key column 'skip_id' doesn't exist in table

**Comment by sport80** [comment]
I've run this 

ALTER TABLE `fm_dns_records_skipped` ADD `skip_id` INT NOT NULL 

and then

ALTER TABLE `fm_dns_records_skipped` ADD PRIMARY KEY (`skip_id`);

It's correct?

**Comment by WillyXJ** [comment]
Sorry I missed that - you can run this in one statement:

```
ALTER TABLE  `fm_dns_records_skipped` ADD `skip_id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
```

**Comment by sport80** [comment]
Ok, I've run this statement without problems. Thank you very much for your help :+1:

**Comment by WillyXJ** [comment]
You're welcome.  Do you happen to remember the path you took to get to v2.1.3?  I don't see anything wrong with the upgrade path, but perhaps I've missed something that only you've encountered/performed.

**Comment by sport80** [comment]
No, sincerly i don't have encountered others problems. I've followed the instructions step-by-step
- downloaded the core from the link on your website (not the master.zip from github)
- unpacked the archive
- downloaded the fmdns package from the link on your website
- unpacked the archive
- maked a backup of current SERVER/CLIENT/DB
- substituted the current installation
- copied the config.inc.php in the new installation
- logged in and followed the steps to upgrade

I've also used the web gui to upgrade the clients and worked perfectly :-)
