### ISSUE TITLE
unable to deploy the facileManager on RedHat 6.7

### ISSUE THREAD

**Issue by bsturzoiu** [WillyXJ/facileManager#283]
Hello, i tried 2 days to deploy this application, buit without sucess.
Environment used: RedHat 6.7
mysql  Ver 14.14 Distrib 5.1.73
PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33)
Server version: Apache/2.2.15 (Unix), Server built:   Nov  4 2015 07:18:39
user used: root

Step followed:
1. download the archive http://www.facilemanager.com/download/facilemanager-complete-2.1.3.tar.gz
2. extract it in tmp folder
3. cp -a  /tmp/facileManager/server/ /var/www/html/facileManager/
4. open chrome browser to http://IP/facileManager
5. It redirect me to http://10.173.35.240/facileManager/fm-install.php
6. where i placed the info like mysql ip, username and password.
7. it said:
Install
I cannot create /var/www/html/facileManager/config.inc.php so please manually create it with the following contents::
<?php

/**
 * Contains configuration details for facileManager
 *
 * @package facileManager
 *
 */

/** Database credentials */
$__FM_CONFIG['db']['host'] = '10.173.35.240';
$__FM_CONFIG['db']['user'] = 'root';
$__FM_CONFIG['db']['pass'] = 'testDNS';
$__FM_CONFIG['db']['name'] = 'facileManager';

require_once(ABSPATH . 'fm-modules/facileManager/functions.php');

?>

I also add require_once('fm-init.php'); before 
require_once(ABSPATH . 'fm-modules/facileManager/functions.php');
8 All steps appears in green:
Creating Database	
Creating facileManager Schema	
The following modules were installed as well:
(They can always be uninstalled later.)

fmDNS	
fmFirewall	
fmSQLPass	
Database setup is complete! Now let's create your administrative account.

9. i enter in step4, (Ok, now create your super-admin account)
10. after submit i enter in this screen: Installation is complete! Click 'Next' to login and start using facileManager.

11. I was redirect to login page, where I successfully login, but I was redirected to http://IP/facileManager/admin-modules.php 

These are the errors i get in /var/log/httpd/error_log (see attachment)

Same issue I have also when I try to configure the client
Please help.

Thank you.

[facileManagerLog.txt](https://github.com/WillyXJ/facileManager/files/91927/facileManagerLog.txt)

**Comment by WillyXJ** [comment]
Did you activate the modules you want to use at /admin-modules.php?

**Comment by bsturzoiu** [comment]
My mistake 
/var/www/html - AllowOverride All was the solution
