### ISSUE TITLE
Reverse zone and subnet

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#284]
I can't create reverse zone for which I have a subnet different that /8 /16 /24.

Eg i own revUNR.10.20.30.in-addr.arpa and not directly the 10.20.30.in-addr.arpa.

My records should be 1.revUNR.10.20.30.in-addr.arpa

Here is an RFC to stick to : http://www.ietf.org/rfc/rfc2317

A workaround could be to clone the 10.20.30.in-addr.arpa to revUNR.10.20.30.in-addr.arpa but the software doesn't actually allows that.

**Comment by WillyXJ** [comment]
fmDNS does support classless zones. When creating the zone, just enter it as x.y.z/cidr. For example, 30.20.10/28.

**Comment by lchanouha** [comment]
This time i do not understand; Am i suppose to entre the network/cirdr as "Domain Name" ?

I still get "Invalid zone name." when i enter "192.168.0/24"

**Comment by WillyXJ** [comment]
My mistake - it won't accept the cidr notation, but you can specify the range. For example, a valid domain name would be 1-128.10.20.30.in-addr.arpa.

**Comment by lchanouha** [comment]
Your rule "/^(\d{1,3})\-(\d{1,3})$/" is too restrictive.(/server/fm-modules/fmDNS/classes/class_zones.php:1229). The reverse zone i got from my ISP for my subnet does not fit it.
I think it should be near '([a-zA-Z0-9-]*)' (or include an option to force creation for such cases). I think you did it for auto PTR generation and I know this isn't the best way to handle subnets (http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/avoid-rfc-2317-delegation.html) in reverse zones, but i  can't change my ISP policy...
To keep PTR generation feature working i thought to simply clone zone from 0.20.30.in-addr.arpa to revUNR.10.20.30.in-addr.arpa.

Sorry for my english

**Comment by WillyXJ** [comment]
I'm sorry, but I don't understand what revUNR means in an IPv4 reverse zone.

**Comment by lchanouha** [comment]
Nothing. That's a custom name to identify the zone. It could be revExample, revOffice, ...

**Comment by WillyXJ** [comment]
RFC2317 was referenced when support for classless subnets was added per #69. I don't see how revUNR follows the RFC as the delegation is for IPv4 octects which do not contain alphabetical characters. Any help to understand would be appreciated.

**Comment by lchanouha** [comment]
As of $ 5.2 in this RFC

> As a result of this method, the location of the zone containing the
   actual PTR records **is no longer predefined**.  This gives flexibility
   and some examples will be presented here.

The name of the reverse zone is not fixed to the start ip address to end. It could be an arbitrary name.

**Comment by WillyXJ** [comment]
This will be supported in the next release.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this fix.
