### ISSUE TITLE
DNSSEC signature

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#285]
It could be nice to add an option to auto-sign zones when they are pushed to servers.

Eg : add an option on zone parameters to activate this feature and set the path of the ksk and zsk files (or load then directly into variables).
This feature would need dnsutils package and call system function "dnssec-signzone" on Debian. 

EDIT : and handle DS record
EDIT2 : and set an auto-sign time interval

**Comment by WillyXJ** [comment]
I'll see how this can be incorporated in 3.x.

**Comment by WillyXJ** [comment]
I'm looking into signing zones and also managing the ZSK and KSK for each secured zone through fmDNS.  Of course, this would mean when enabling DNSSEC for a zone, the ability to assign multiple keys would be required in order to handle key rollovers.

**Comment by WillyXJ** [comment]
The next pre-release will include support for generating, adding, and revoking DNSSEC KSK and ZSK keys and signing zones with them.  I hope to have automatic DS record support when signing sub-domains by the stable release.  Here are some snippets of the zones page in case they entice you to help test the feature. :)

![image](https://cloud.githubusercontent.com/assets/1309591/23683297/7739e456-0355-11e7-9740-95384c67e048.png)

![image](https://cloud.githubusercontent.com/assets/1309591/23683317/8ddd3f1e-0355-11e7-871e-62938c1de8ae.png)

![image](https://cloud.githubusercontent.com/assets/1309591/23683338/b5241c32-0355-11e7-8311-8be0075469ff.png)

![image](https://cloud.githubusercontent.com/assets/1309591/23683354/cb133500-0355-11e7-8bd1-9c43fb955d90.png)

![image](https://cloud.githubusercontent.com/assets/1309591/23683459/4bf0e9ce-0356-11e7-9249-e244ec79a79c.png)

**Comment by WillyXJ** [comment]
DS RR is now included in [the latest beta version](http://www.facilemanager.com/download/?t=4) and later.
