### ISSUE TITLE
Zone already exists.

### ISSUE THREAD

**Issue by bsturzoiu** [WillyXJ/facileManager#286]
Hello, 
I knew that I am newbie on this (so, maybe I am wrong).
I have defined 2 dns servers, both of them are visible on facileManager UI.
What I tried to do was to create a zone on the master server and same zone on slave server.
And I receive this error - Zone already exists.
I used the clone zone option, I changed the the type from master to slave.
To be more clear, this is the zone definition that I want to use. 
It is possible with facileManager to accomplish this?

ON MASTER DNS SERVER
zone "testnpr.example.com" IN {
        type master;
        file "masters/testnpr.example.com.dyn.db";
        allow-update {
                key root.testnpr.example.com;
        };
        notify yes;
        also-notify { 10.173.35.252; };
        allow-transfer { 127.0.0.1; 10.173.35.240; 10.173.35.252; };
};

ON SLAVE DNS SERVER
zone "testnpr.example.com" IN {
        type slave;
        masters { 10.173.35.240; };
        file "slaves//testnpr.example.com.dyn.db";
        allow-transfer { 127.0.0.1; 10.173.35.240; 10.173.35.252; };
};

Thank you

**Comment by bsturzoiu** [comment]
Based on, 
https://github.com/WillyXJ/facileManager/issues/148
i think the solution is to define a group.

**Comment by WillyXJ** [comment]
Hello,

Please have a look at #279 - you only need to create the zone once and create the master/slave association through the use of server groups. fmDNS will then create the zone on the client as either a master or slave based on its server group.

**Comment by bsturzoiu** [comment]
Thank you for the tip.
I still have a small issue, 
I tried to define **key root.testnpr.example.com;** as attribute value for allow-update.
Is it possible currently? 
Because when i tried, on UI it set 2 separate values: key and root.testnpr.example.com and the change in /etc/named/zones/zones.conf.all is:
**allow-update { key; root.den.vz.altidev.test.net; };**
instead of 
**allow-update { key root.den.vz.altidev.test.net; };**

Thank you

**Comment by WillyXJ** [comment]
Hello,

This original issue looks to be resolved now so it will be closed. Please open a new issue for the key issue you describe so we can have better tracking.

Thanks.
