### ISSUE TITLE
 allow-update attribute value issue

### ISSUE THREAD

**Issue by bsturzoiu** [WillyXJ/facileManager#287]
Hello, 
I tried to define **key root.testnpr.example.com**; as attribute value for **allow-update**.
Is it possible currently? 
Because when i tried, on UI it set 2 separate values: **key and root.testnpr.example.com** and the change in /etc/named/zones/zones.conf.all is:
**allow-update { key; root.testnpr.example.com; };**
instead of 
**allow-update { key root.testnpr.example.com; };**

Thank you

**Comment by WillyXJ** [comment]
Thanks for the report. This appears to be an oversight/bug that will need to be resolved in a future bugfix release. Currently, allow-update is expecting an address_match_element or acl.

**Comment by WillyXJ** [comment]
After looking into this further, keys are supported in address_match_elements.  You need to first define the key under Options -> Keys and then it will appear in the dropdown list for allow-update and similar.

**Comment by bsturzoiu** [comment]
Thank you
