### ISSUE TITLE
bulk data process

### ISSUE THREAD

**Issue by bsturzoiu** [WillyXJ/facileManager#289]
Hi there, 
I tried your product in the last 2 weeks and seems to be the right tool to manage the DNS infrastructure.
I came to you with 2 additional questions:
1. Is there any intention in the future to have exposed the application functionalities as API ?
2. is it possible currently to bulk insert info in the database and the process of propagating these info in DNS files to happen as is happen if the data are inserted from UI?

I used in my tests the cron job to propagate the changes from UI and I will be happy if same thing can happen if I insert same information directly in the database.
I tried this option, i saw the info on UI after that, but the changes are not propagated even I manually execute the cron job, so something is missing in the chain.

Thank you for your time.

**Comment by WillyXJ** [comment]
Hello,

Hopefully I can answer your questions.

1. There are currently no plans to add API support. If you provide a use case then this issue could potentially be turned into a feature request. 
2. You can use the zone import tool to add records in bulk which will also set the necessary flags to raise the reload buttons (or server config build buttons) that would still need to be clicked. If you are modifying the database directly via MySQL, then you will also need to set the zone_reload flag and insert one or more records into the fm_dns_track* tables.

fmDNS isn't designed to be used outside of the UI.

**Comment by bsturzoiu** [comment]
1. A scenario will be that 100 VMs are need to be set into a specific zone, for each of them need to create A, PTR and TXT records.
What will be nice to have is a command like:
sudo php /usr/local/facileManager/fmDNS/dns.php addRecord type:A name:newVM value:192.168.1.100  comment:none status:a createPtr:yes

sudo php /usr/local/facileManager/fmDNS/dns.php deleteRecord type:A name:myTestVM

or better, to minimize the number of calls 
sudo php /usr/local/facileManager/fmDNS/dns.php addRecord -f myFile.csv
where file will have an expected structure

Similar for all objects, for all CRUD operations.
etc,

For 2: where the  zone_reload flag is located?
For fm_dns_track* tables: i don't know yet:
1 - their meaning. I saw that they contains few records having server_serial_no identical with what is in fm_dns_servers table. I believe that this has role of FK.

2 - I have currently fm_dns_track_builds and fm_dns_track_reloads tables. Can be more? 

Thank you.

**Comment by WillyXJ** [comment]
1. There are security implications that would need to be considered for that to work since fM supports granular permissions.  Is there a reason the zone import tool wouldn't accomplish what you need to do?

2. My mistake, it's the domain_reload field in the fm_dns_domains table.  The *track_builds table contains the server serial numbers and domain IDs that have been built via 'config build' - zones cannot be reloaded until they've been built.  The *track_reloads table contains server serial numbers and domain IDs for servers that need to reload a zone (domain ID) via cron.

**Comment by bsturzoiu** [comment]
1. zone import mechanism is useful when that file exists. My scenario is happen when I want to manage 100 new machines or to change their configuration

**Comment by WillyXJ** [comment]
API functionality is now implemented in [fmDNS 4.0-beta1](http://www.facilemanager.com/modules/fmdns/?t=3) and later. Testing is requested. Final release will come out later.

**Comment by WillyXJ** [comment]
[fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) has been released.
