### ISSUE TITLE
Enclose database name in backticks for SQL operations

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#290]
When using the name of the database in SQL queries, it should be enclosed with backticks (`) as it might contain characters which won't get accepted in the query otherwise.

I had this break my upgrade as my database name contains a dash (-) and an underscore (_).

**Comment by WillyXJ** [comment]
Thanks for the report.  It's been confirmed that there is the inconsistency of some code enclosing the database name while other code does not.

**Comment by WillyXJ** [comment]
Fixed in fM v 2.1.5 and packaged modules.
