### ISSUE TITLE
fmFirewall does not work / cannot click it

### ISSUE THREAD

**Issue by air101** [WillyXJ/facileManager#292]
Hello,

fmDNS works just fine. I thought I'd give fmFirewall a try, so I enabled the module. But when I try to switch to Firewall module, it just stays at fmDNS. Did i forget something?

Thank you

**Comment by WillyXJ** [comment]
What version of facileManager and fmFirewall are you using?

**Comment by WillyXJ** [comment]
Confirmed bug with fM 2.1.4.

**Comment by air101** [comment]
Yes, it is 2.1.4

**Comment by WillyXJ** [comment]
Fixed in fM 2.1.5.
