### ISSUE TITLE
fmFirewall issue saving iptables file on client

### ISSUE THREAD

**Issue by air101** [WillyXJ/facileManager#294]
Good Job on the latest fixes :+1:  Through there is still an issue. The Servers are added @ servers list successfully and I can edit everything fine through the webui. But the iptables file is not written/updated on the servers. php fw.php cron tells me "There are no files to save. Aborting."

**Comment by WillyXJ** [comment]
Thanks for the report and your patience.  Confirmed bug only when using the cron update method (I'm sorry it wasn't caught with 1.2.4!).  I'll get an official 1.2.5 build released this evening.  If you need it fixed before then, you can change line 151 in server/fm-modules/fmFirewall/classes/class_buildconf.php to the following:

```
return $this->buildServerConfig($post_data);
```

**Comment by air101** [comment]
Thank you! Everything works fine now! :+1:

**Comment by WillyXJ** [comment]
Glad to hear it. 1.2.5 is released.
