### ISSUE TITLE
Different zones on DNS servers

### ISSUE THREAD

**Issue by cahluor** [WillyXJ/facileManager#296]
Hello,

I have a setup where I manage different groups of nameservers with differents zones.
Is it possible to have a group of zones existings on a group of servers and another set on another group ?

**Comment by WillyXJ** [comment]
Absolutely! You can create your server groups through Config -> Servers and click on the Server Groups link in the upper right.  Once you've defined your server groups, you can define which group(s) and/or server(s) each zone is hosted on in the Zones page.  This can be done when adding new zones or editing the zone properties of existing zones.

![image](https://cloud.githubusercontent.com/assets/1309591/13961845/f10ef76c-f023-11e5-901a-2018c0646946.png)

Of course, you are not required to create server groups, but they may make it easier to manage your zones.

**Comment by cahluor** [comment]
Ok thanks, Exactly what I was looking for... but failed to see it because I use template and in this case the options are masked.

If I remove the template and assign to zone to "internal servers" it works.

I tried to change it on the template level. I put the template "internal" to the group "Internal servers" but it don't seems to work.

**Comment by WillyXJ** [comment]
Thanks for the report.  Server selection within the templates should be honored.  I have verified they are not.  I'll work on a bug fix for this.

**Comment by WillyXJ** [comment]
This is fixed in fmDNS v2.1.8.
