### ISSUE TITLE
Allow empty forwarders for forward zone

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#299]
In some scenarios (for example when working with DNSBLs) it is required/handy to disallow queries to a certain zone to be send to the default forwarder and instead execute the query against the root NS yourself.

[The last paragraph of this article](https://wiki.apache.org/spamassassin/CachingNameserver) explains how the forward zones should look like.

When trying to create these zones with facileManager/fmDNS an error is displayed that it is not possible to *not* specifiy a forwarder thus leaving the forwarder empty.

Is there a workaround for this/can this behavior be changed in a future release?

**Comment by WillyXJ** [comment]
Thanks for the report and use case that I was not aware of.  A fix will be in the next release.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this fix.
