### ISSUE TITLE
Deleting Zone Template results in error

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#300]
I create a zone template and from that a zone. I deleted the zone and wanted to delete the zone template as well. Deleting the zone was not possible (see screenshot). I think this is because of a typo in the table name (it should be ``fm_dns_domains`` instead of ``fm_dns_domain``).

 ![delete_zone_template](https://cloud.githubusercontent.com/assets/1166870/14170293/3b461a58-f72d-11e5-9a3d-941e2949bc93.PNG)

**Comment by WillyXJ** [comment]
Thanks for the report.  This will be fixed in the next release.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this fix.
