### ISSUE TITLE
Add possibility to add include statement to named.conf

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#301]
Sometimes it is handy to have the possibility to include a custom zone file for a nameserver when certain options are not available or feasible through fmDNS. I can add include within the ``options`` for a nameserver but this excludes the use of ``zone`` and all other statements which are not allowed within ``options``

**Comment by WillyXJ** [comment]
`include` support in the zone configs was added in v2.1 (#123) and then fixed in v2.1.4 (#270).  However, #271 shows one report where it still does not work.  Are you having a similar issue?

**Comment by peterschen** [comment]
I want to have the include in ``named.conf`` and not in the ``options`` or ``zone`` statements. I found no way to make this happen. For now I hacked the buildconfig process to have this for a particular server. But this is not the way would like this.

**Comment by WillyXJ** [comment]
I understand now you want `include` in named.conf, but not in the `options`, `view`, and `zone` clauses.  I remember looking at supporting that with #123, but could not come up with a good implementation at the time.  Leaving this open to revisit it.

**Comment by WillyXJ** [comment]
Found a solution and this can be included in the next release.

![image](https://cloud.githubusercontent.com/assets/1309591/14215491/94da7e28-f800-11e5-9f9f-f502a969cb82.png)

**Comment by peterschen** [comment]
I like it. 

A more forward looking solution might be to have a third tab within the options: one for ``named.conf`` (``include`` and whatnot), one for ``options {}`` and one for rate limiting. This would an extensible solution in the future.

**Comment by WillyXJ** [comment]
That's an interesting and good suggestion.  However, I don't know of any other entries in named.conf that would not be `include` or a clause thus that tab would have nothing but `include` statements listed.  I could be wrong though.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this improvement.
