### ISSUE TITLE
table fm_dns_domain does not exist

### ISSUE THREAD

**Issue by fraksken** [WillyXJ/facileManager#302]
When I try to delete a zone template, I receive the message "Database error: [Table 'facileManager.fm_dns_domain' doesn't exist | Query: [UPDATE 'fm_dns_domain' SET 'domain_status'='deleted'WHERE account_id='1' AND 'domains_id=9]]"
I went to have a look in the database, and there is no fm_dns_domain. There is a fm_dns_domains table though. Probably a typo.

**Comment by peterschen** [comment]
Duplikate of #300.

**Comment by WillyXJ** [comment]
Yes, it will be fixed in v2.2 which is in final stages of testing.
