### ISSUE TITLE
creation of ssh-key for centos

### ISSUE THREAD

**Issue by fraksken** [WillyXJ/facileManager#303]
Hey,
When I install the client software on a CentOS box, the ssh key is generated in the file /home/fm_user/.ssh/authorized_keys2
the sshd in centos, however, only listens to .ssh/authorized_keys files. Is it possible for the install to detect if the OS runs CentOS/Redhat and subsequently creates an authorized_keys file instead of the authorized_keys2 file?

**Comment by WillyXJ** [comment]
Which version of CentOS are you using? Also, what version of OpenSSH are you using?

**Comment by fraksken** [comment]
Openssh-server: Version: 6.6.1p1 - Release 25.el7_2
Centos Linux release 7.2.1511 (Core)
uname -a returns:
Kernel: 4.2.8-pve

**Comment by WillyXJ** [comment]
Thanks for bringing this up. After reading the OpenSSH release notes, authorized_keys2 was deprecated in version 3.0 and support was removed in version 5.9. Since 3.0 was released in 2001, fM should be updated to only use authorized_keys. This should be a simple fix I can include in v2.2.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this fix.
