### ISSUE TITLE
Add SPF record type

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#304]
Newer versions of bind support the SPF record type. When specifiying SPF records the "old" way as a TXT the following message will appear in bind log:

``found SPF/TXT record but no SPF/SPF record found, add matching type SPF record``

The SPF record type should be added and depending on the version of bind either generate a TXT and/or a SPF record.

**Comment by WillyXJ** [comment]
Which version of bind requires the SPF RR? The reason the SPF RR was never supported in fmDNS is because it's recommended that RR never be used. See http://www.zytrax.com/books/dns/ch9/spf.html.

**Comment by WillyXJ** [comment]
In addition, there was a bug in bind for EL7 that discusses this - https://bugzilla.redhat.com/show_bug.cgi?id=1215164

**Comment by peterschen** [comment]
I'm running bind9 (9.9.5.dfsg-9+deb8u6) on Debian. Maybe the version in Debian Jessie is affected by the same problem. I'll keep an eye on that. Closing for now.
