### ISSUE TITLE
Issue with Finding admin-modules.php

### ISSUE THREAD

**Issue by c0fe** [WillyXJ/facileManager#306]
I have CentOS 7 running, have MariaDB, PHP (from repo) and Apache (from repo) installed and running.

Error is the following:

https://dpaste.de/y8VD

Content of .htaccess (got it from the tarball)

https://dpaste.de/kto1

What can be causing this issue? How to resolve it?

**Comment by c0fe** [comment]
Also made changes to httpd.conf to allow overwrite and I am now getting the following errors:

https://dpaste.de/Q8Ei

**Comment by c0fe** [comment]
Nevermind, I figured and fixed all the issues.

**Comment by WillyXJ** [comment]
Good news! Would you mind sharing what the fixes were?  Does the documentation or code need to be updated to prevent this in the future?

**Comment by c0fe** [comment]
The issue for CentOS was providing the Allow Override. Ubuntu was never resolved even with Allow Override.
