### ISSUE TITLE
the requested URL /facileManager/admin-modules.php was not found on this server.

### ISSUE THREAD

**Issue by lcbk** [WillyXJ/facileManager#308]
hi,when i login ,it appears to "the requested URL /facileManager/admin-modules.php was not found on this server."

My installation directory is as follows 
[root@xx facileManager]# ll
total 60
-rw-r--r--. 1 root root    379 Apr 12 17:31 config.inc.php
-rwxr-xr-x. 1 salt games   356 Apr 17  2013 config.sample.inc.php
drwxr-xr-x. 4 salt games  4096 Mar 12 09:15 fm-includes
-rwxr-xr-x. 1 salt games  9211 Mar 12 09:15 fm-init.php
-rwxr-xr-x. 1 salt games 12569 Mar 12 09:15 fm-install.php
drwxr-xr-x. 7 salt games  4096 May 28  2015 fm-modules
-rwxr-xr-x. 1 salt games  3746 Nov 20 21:25 fm-upgrade.php
-rw-r--r--. 1 salt games  2021 Apr 26  2015 index.php
-rwxr-xr-x. 1 salt games  6136 May 13  2015 password_reset.php
[root@agent facileManager]# pwd
/var/www/html/facileManager

**Comment by lcbk** [comment]
I do not what happen ? My system os is CentOS7 The install process apper very well.

**Comment by WillyXJ** [comment]
Can you please confirm .htaccess is in /var/www/html/facileManager?

**Comment by lcbk** [comment]
it really exists in /var/www/html/facileManager

**Comment by WillyXJ** [comment]
Does your apache configuration allow for .htaccess files?

**Comment by lcbk** [comment]
Hi，It work again。however ，when i restart apache，It notice me
Starting httpd: [Wed Apr 13 09:34:36 2016] [warn] Useless use of AllowOverride in line 9 of /etc/httpd/conf.d/namedmanager.conf.
what happening？

**Comment by lcbk** [comment]
And I want to konw that It can be installed in centos7

**Comment by WillyXJ** [comment]
With the default Apache installation on CentOS6, you don't need the AllowOverride. I have not tested fM on EL7 yet, but based on this and #306, it looks like I need to get another test environment built.

**Comment by lcbk** [comment]
Tks，I very much looking forword to ，that fm can installed in EL7。

**Comment by lcbk** [comment]
i want to know that the client make what affect on fmdns，can you explain ？

**Comment by WillyXJ** [comment]
I have tested fM on EL7 with a plain installation of httpd and php from the yum repo and found a few bugs in the installer which would throw PHP fatal errors if .htaccess was missing.  These have been fixed for the next release.  Until then, the steps to make it work on EL7 are as follows:

1. `sudo yum install httpd php php-mysqli php-posix`
2. `wget http://facilemanager.com/download/facilemanager-complete-2.1.5.tar.gz`
3. `tar zxf facilemanager-complete-2.1.5.tar.gz`
4. `mv facileManager/server /var/www/html/facileManager`
5. `vi /etc/httpd/conf/httpd.conf`
 * Change `AllowOverride None` to `AllowOverride All` in the `<Directory "/var/www/html">` directive
6. `sudo systemctl reload httpd.service`
7. Point your browser to http://domain.local/facileManager/
8. Follow the installer steps

**Comment by WillyXJ** [comment]
This was fixed in 2.2.
