### ISSUE TITLE
Config build after slave zone creation

### ISSUE THREAD

**Issue by Pierre-CHABREDIER** [WillyXJ/facileManager#310]
Hi, when I create DNS slave forward zones, then  facileManager does not ask me to build configuration.

I have to create a temporary master zone, then delete it - then facileManager ask me to build configuration.

Thank You very much for your that tool.

PS : Sorry for my bad english.

Best Regards.

**Comment by WillyXJ** [comment]
Thank you for the report.  I'll see if a fix can be included in v2.2.

**Comment by WillyXJ** [comment]
v2.2 has been released and contains this fix.
