### ISSUE TITLE
Import Zone Files Tool issue with DMARC or DKIM

### ISSUE THREAD

**Issue by Pierre-CHABREDIER** [WillyXJ/facileManager#311]
Hello All,

I just want to report an issue with DKIM, DMARC records and "Import Zone Files" tool.

In fact, I thinl it's an issue with ";" or "\" or both that are included in records.

For example :

domain.ext zone file 
[....]
_dmarc.domain.ext.			       IN TXT	"v=DMARC1\; p=none"
XXXXXXXXXXXXXXXXXXXX._domainkey.domain.ext.  IN TXT "v=DKIM1\; k=rsa\; p=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Both records are not imported, and are shown :

_dmarc.domain.ext.			       IN TXT	"v=DMARC1\
XXXXXXXXXXXXXXXXXXXX._domainkey.domain.ext.  IN TXT  v=DKIM1\

In import verification window.

Regards.

**Comment by WillyXJ** [comment]
Thanks for the report. Confirmed bug - the parser first separates comments (denoted by ;) in which case semi-colons need to be allowed in quoted strings.

**Comment by WillyXJ** [comment]
This is fixed in v2.2.1.
