### ISSUE TITLE
Client upgrade from 2.1.4 to 2.2

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#312]
Installed 2.2 on the server without a hitch. However, it can no longer update any clients. Getting an error from all 4 NS servers that"

"This client requires a manual installation."

Couldn't find anything in the changelog that would suggest we have to actually do that.

**Comment by WillyXJ** [comment]
Yes, upgrading to 2.2 does require a manual installation using the steps provided in the README.md - https://github.com/WillyXJ/facileManager#client-upgrade.  Since you've bested me, I'll update the changelogs to include this as well and repackage.

**Comment by wispr** [comment]
Well, it would appear I've royally botched this. Tried to do the [client update](https://github.com/WillyXJ/facileManager#client-upgrade) manually, removed config, wiped directory, copied new files and moved config back, but server still can't see the upgrade. Ran the client upgrade script, tried the reinstall script, all with no joy. Server is now showing
`sudo: no tty present and no askpass program specified`

**Comment by WillyXJ** [comment]
After a manual client upgrade, the database won't recognize the new client version until some form (ie build config, upgrade, client reinstall, etc.) of client interaction occurs.  It looks like you've done something like that if you are getting a sudo error.  Which update method are your clients using?  Would you also be able to send me your /etc/sudoers.d/99_fmDNS file?

**Comment by wispr** [comment]
The clients are config'd for ssh updates from the server. 99_fmDNS does not
exist on the client or the server...


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Your /etc/sudoers must not support including /etc/sudoers.d files.  Would you be willing to send your /etc/sudoers for review?  The client installer should have put entries in it to support your ssh user running the client scripts as root and not requiring a TTY.  In addition, are there any failures in your sudo log file (/var/log/secure or /var/log/syslog by default)?

**Comment by wispr** [comment]
Correct, it did get correctly into the file correctly. Well, at least it
looks right to me.

#includedir /etc/sudoers.d
fm_user ALL=(root)      NOPASSWD: /usr/bin/php
/usr/local/facileManager/fmDNS/dns.php *
fm_user ALL=(root)      NOPASSWD: /usr/bin/php dns.php *

No /log/secure and syslog only contains entries from our monitoring system
using snmp.


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
Ah, you need to update your sudo lines to use client.php instead of dns.php or just run `sudo php /usr/local/facileManager/fmDNS/client.php reinstall` which should take care of that for you along with adding the following in your sudoers file:

```
Defaults:fm_user !requiretty
Defaults:fm_user !env_reset
```

See https://github.com/WillyXJ/facileManager#important-upgrade-notes for more information for the upgrade notes.  Let me know if that does not resolve it for you.

**Comment by wispr** [comment]
Ok, manually changed dns.php to client.php and ran the reinstall script.
Once executed, it simply goes to another blank command prompt. I manually
added the two default entries in the the sudoers file, rebooted the
machine, and tried again. The fm server no longer reports tty type issues,
but simply says client updated failed.


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
This was resolved by reinstalling/upgrading the clients with the following steps:

```
cd ~
cp /usr/local/facileManager/config.inc.php .
sudo rm -rf /usr/local/facileManager
wget http://www.facilemanager.com/download/facilemanager-core-2.2.tar.gz http://www.facilemanager.com/download/module/fmdns-2.2.2.tar.gz
tar zxf facilemanager-core-2.2.tar.gz
tar zxf fmdns-2.2.2.tar.gz
sudo mv facileManager/client/facileManager /usr/local
rm -rf facile* fmdns*
sudo mv config.inc.php /usr/local/facileManager
sudo php /usr/local/facileManager/fmDNS/client.php reinstall
```
