### ISSUE TITLE
http://10.76.249.141/facileManager/admin-modules.php

### ISSUE THREAD

**Issue by cucy** [WillyXJ/facileManager#314]
Not Found

The requested URL /facileManager/admin-modules.php was not found on this server.

**Comment by WillyXJ** [comment]
Hi,

Please look at these similar issues to see if your's has the same resolution steps.

https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+admin-modules

Thanks.

**Comment by cucy** [comment]
Thanks
