### ISSUE TITLE
Performing client upgrade | Unable to download file.

### ISSUE THREAD

**Issue by aredan** [WillyXJ/facileManager#317]
I lost one of my Internal DNS Servers (disk crash and no backup) its only job was serving DNS request, a combination of bind (fmDNS) and dnsmas (pi-hole).

I reinstalled everything in a VM with the same name (leela). look for the server ID in the mysql database and use that number when the client.php ask me for one. everything was OK, build config and all my zones are there like anything happened.

Now in the dashboard the server is asking for client upgrade but I used fmDNS 2.2.2, I think that the management server is 2.2.

dasjboard:
![2016-05-21 21_08_39-dashboard facilemanager](https://cloud.githubusercontent.com/assets/939894/15451577/3efd048e-1f98-11e6-91eb-ef68a7053f96.jpg)

fm.log:
![2016-05-21 21_01_52-settings](https://cloud.githubusercontent.com/assets/939894/15451579/4a5fb4c0-1f98-11e6-9d5e-ca327a5e1f4c.jpg)

**Comment by WillyXJ** [comment]
The UI will report the need to upgrade the client whenever the server and client versions don't match. Once you upgrade the server to 2.2.2 then all should be well.

**Comment by aredan** [comment]
I can't find the download link for the 2.2.2 server.
 http://www.facilemanager.com/download/

 I'm already running that one.

**Comment by WillyXJ** [comment]
Can you please confirm the version of fmDNS your server is running on the Modules page (/admin-modules.php)? facileManager is the core which the latest is 2.2 and fmDNS is a module and the latest is 2.2.2. According to your client log, it looks like you are using fmDNS 2.2 on the server. The latest module can be found at http://www.facilemanager.com/modules/fmdns/.

**Comment by aredan** [comment]
Done, I was getting the upgrade process upside down. I know understand that each client (or server) can be upgrade individually.

Thanks!

![2016-05-22 21_14_49-dashboard facilemanager](https://cloud.githubusercontent.com/assets/939894/15458080/633d92a2-2063-11e6-87cd-60015393897f.png)

**Comment by WillyXJ** [comment]
Glad to hear it!
