### ISSUE TITLE
Users are removed from group when it is updated

### ISSUE THREAD

**Issue by karlism** [WillyXJ/facileManager#319]
It seems that facileManager has bug in group editing. Whenever group settings are edited and saved, users belonging to that group are removed from it. To reproduce this bug:
1) create new group without any users
2) create two new users and associate them with previously created group
3) go to group tab and edit the group (just clicking "save" without actually editing anything is enough)
If you click "edit" again, you'll notice that all the users associated with this group are missing now.

I've tried it on facileManager v2.2 + fmDNS v2.2.2. All operations where performed from "admin" account.

**Comment by WillyXJ** [comment]
Thank you for the report - it's a confirmed bug in that the group edit window is not populating the users list properly.

**Comment by WillyXJ** [comment]
This is fixed in fM core 2.2.1.
