### ISSUE TITLE
Incorrect permissions for created configuration files

### ISSUE THREAD

**Issue by karlism** [WillyXJ/facileManager#320]
BIND configuration files that are created by facileManager have incorrect permissions:

`$ pwd`
`/var/named/chroot/etc`
`$ ls -la named.conf*`
`-rw-r--r--. 1 named root 703 May 31 12:33 named.conf`
`-rw-r--r--. 1 named root 193 May 31 12:33 named.conf.keys`
I don't think that _named_ user should have _rw_ access to _named.conf_ file considering that it only needs to read it.
_named.conf.keys_ file should also have stricter permissions and shouldn't be readable by anyone (except _root_ and _named_ users) because it contains sensitive information.

**Comment by WillyXJ** [comment]
Thanks for the suggestion. fmDNS creates the files with permissions based on the default install of bind9 (Debian-based) and bind (RHEL-based).  It shouldn't be much effort to change the permissions in the code.

**Comment by karlism** [comment]
I've just installed bind-9.9.4-29.el7_2.3 on CentOS 7 and default file permissions are following:
$ ls -la /etc/named.conf
-rw-r-----. 1 root named 1558 Jun 1 2015 /etc/named.conf

As for the _key_ files, the only available keys in default installation are ISC public root keys, these are not supposed to be secret:
$ ls -la /etc/named.*.key
-rw-r--r--. 1 root named 2389 Mar 16 15:40 /etc/named.iscdlv.key
-rw-r--r--. 1 root named  487 Jul 19  2010 /etc/named.root.key

**Comment by WillyXJ** [comment]
Ah, after the files are written to disk, a chown is run instead of a chgrp which allows named to write slave files; however, it inadvertantly allows named to write to configuration files.  This will need to be fixed.

**Comment by WillyXJ** [comment]
This has been fixed in v2.2.4.
