### ISSUE TITLE
zones type forward / empty forwarders IPs

### ISSUE THREAD

**Issue by Kevin323** [WillyXJ/facileManager#324]
Hello,
I try to create a zone type forward. It works, but I can't define any IP's for the forward server. I put in the IP in the "Define forwarders" field and press enter. This works, but after pressing "Save" and editing again, the field is empty again. I use version 2.2 and saw that you added the functionality to allow empty IP fields (Issue #299) from version 2.1 to 2.2. Since it works in your demo (v2.1) very well, may I suppose that this issue came up with this change?
Beside this, it's a great peace of software :-) . Thanks!

**Comment by WillyXJ** [comment]
Thanks for the report - it's a confirmed bug which will be fixed in the next release.

**Comment by Kevin323** [comment]
Thanks a lot!

**Comment by WillyXJ** [comment]
This is fixed in fmDNS 2.2.3.
