### ISSUE TITLE
Address_match_element options do not show text box

### ISSUE THREAD

**Issue by andrerdrummond** [WillyXJ/facileManager#329]
When I try to put the allow-query option I'm having the problem that the system don't allow me to put the addresses in the field. This message is in the field: (address_match_element).

What I need to do?

**Comment by andrerdrummond** [comment]
I solved the problem. First I needed to create an acl. Then the system let me put the values that I needed. I think it's a bug.

**Comment by WillyXJ** [comment]
Thanks for the report. I have confirmed this behavior and is indeed a bug for all address_match_element options.

**Comment by WillyXJ** [comment]
This has been fixed in v2.2.4.
