### ISSUE TITLE
Serial numbers not updated on cloned zones

### ISSUE THREAD

**Issue by karlism** [WillyXJ/facileManager#330]
Hello,

There is an issue with serial numbers and zone reloads when using cloned zone feature.  To reproduce it do the following:
1) create a new zone (with proper SOA record and NS records so that facileManager deploys it to server);
2) create a clone of that zone (I'm using same name of the zone but different view);
3) deploy these zones to server configuration and note/remember serial numbers of both zones (master and clone);
3) add new A record in master zone (that was created in first step), do not reload server configuration yet:
3.1) verify that both zones (created in step 1 and step 2) now contain this new A record in web interface;
3.2) reload this zone;
4) if you check serial numbers on DNS servers (or from zone preview page), you'll notice that serial number has been updated only on master zone (created in step 1), but not on its clone (created in step 2).

**Comment by WillyXJ** [comment]
Thanks for the report - I have confirmed this bug using your provided steps.

**Comment by WillyXJ** [comment]
This has been fixed in v2.2.4.
