### ISSUE TITLE
Feature Request: Module for DHCP

### ISSUE THREAD

**Issue by Lobout** [WillyXJ/facileManager#332]
How about a module to configure and manage DHCP configurations?

**Comment by wispr** [comment]
Another vote for this. We'd love to see the ability to manage/see dhcp leases from redudant isc dhcp servers...

**Comment by WillyXJ** [comment]
Is anybody interested in donating The DHCP Handbook for this project?

http://a.co/a0y4YJg

**Comment by wispr** [comment]
That and the DNS server book on your list will be there on Thursday!

**Comment by WillyXJ** [comment]
@wispr - Thank you, kindly!

**Comment by wispr** [comment]
My pleasure! I'd love to see something to help us manage HA deployments of ISC Bind. And a book or two is the least I can do to show the value we get out of FM.

**Comment by WillyXJ** [comment]
The first release is now available [fmDHCP 0.1](http://www.facilemanager.com/modules/fmdhcp/).  There are a few features to implement before 1.0, but here's a start and feedback is welcome.
