### ISSUE TITLE
Problems with configuration after upgrade

### ISSUE THREAD

**Issue by karlism** [WillyXJ/facileManager#333]
Hello,

After seemingly successful upgrade of facileManager to 2.3 and fmDNS module to 2.2.4, I now experience two issues with server configuration building:
![facilemanager](https://cloud.githubusercontent.com/assets/19568035/17292599/ec1971a0-57f3-11e6-8766-4bd7aa03e1f7.png)
![facilemanager2](https://cloud.githubusercontent.com/assets/19568035/17292776/addabcea-57f4-11e6-909c-634579140346.png)

As you can see, there are two errors, about 13th line of _/etc/named.conf.key_, even though this line is actually empty, and about nonexistent _/var/named directory_. BIND is running chrooted in my case and both _/var/named_ and _/var/named/chroot/var/named_ directories exist.

Any ideas what could be wrong?
Thanks!

**Comment by WillyXJ** [comment]
Hi,

That is indeed odd behavior. The syntax checks are performed by the BIND named-checkconf utility. Did you upgrade BIND recently, too? What version of BIND are you using?

**Comment by karlism** [comment]
Thank you for prompt reply!

I'm using bind-chroot package 9.9.4-29.el7_2.3 on CentOS 7.2. Judging by yum logs, BIND package hasn't been upgraded since May 27th, so I suspect that's not an issue.

**Comment by WillyXJ** [comment]
I've found the issue with $fm_module_buildconf->namedSyntaxChecks() which only impacts the syntax check routine.  If you disable the checks, config builds and zone reloads are successful.  A fix will be coming in the next bug fix release.

**Comment by karlism** [comment]
Thanks!
