### ISSUE TITLE
more granular user rights / permission to create own zones

### ISSUE THREAD

**Issue by herono** [WillyXJ/facileManager#339]
Currently it is possible to restrict users to manage selected zones. I would be very helpful if users could also be given the right to create their own zones that they (and the admin) can manage.

**Comment by WillyXJ** [comment]
Thank you for the feature request.  I'll look into how it can be implemented in a future version.

**Comment by WillyXJ** [comment]
This is now included in 3.0-alpha1 and later.

**Comment by herono** [comment]
Sehr geehrte Damen und Herren,

bis einschließlich 23. Juni 2017 bin ich nicht erreichbar. Eingegangene Nachrichten werde ich ab dem 26. Juni bearbeiten. Ihre Nachricht wird NICHT weitergeleitet. Bitte wenden Sie sich in dieser Zeit gegebenenfalls an meine Kollegen:

Herr Böneke (boeneke@online-now.de)
Herr Hoyer (hoyer@online-now.de)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++

Dear Sirs and Madams,

until the 23rd of June 2017 I am not available. Received e-mails I will process from the 26th of June. Your message will NOT be forwarded. If needed, please contact my colleague at this time:

Mr. Böneke (boeneke@online-now.de)
Mr. Hoyer (hoyer@online-now.de)


Mit freundlichen Grüßen,
best regards,

Johannes Herzfeldt

--------------------------------------------------
Online Now! GmbH
Agentur für digitale Kommunikation
Reichsstr. 100
14052 Berlin

Tel +49 30 615082-120
Fax +49 30 615082-222
E-Mail: herzfeldt@online-now.de
Web: http://www.online-now.de/

Geschäftsführer: Dr. Maximilian Hoyer
Handelsregister: Amtsgericht Berlin-Charlottenburg HRB 57835
Ust.-ID: DE 176635553
