### ISSUE TITLE
How to reset lost password "admin"

### ISSUE THREAD

**Issue by zm0k4h** [WillyXJ/facileManager#341]
How i can reset admin password? without email form.

**Comment by WillyXJ** [comment]
Without having mailing enabled to use the reset form, you can perform the following:

> You can reset the authentication method by setting the following in config.inc.php:
>
> `define('FM_NO_AUTH', true);`

This will disable authentication so you can update your password.  You will then want to remove that line from config.inc.php and enable authentication again in the General Settings.
