### ISSUE TITLE
Ubuntu 16.04.1 and php7

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#343]
Well totally jacked myself up tonight. The upgrade to 16.04.1 didn't go well. It doesn't install php by default during the upgrade and host of other problems. The site won't load and getting a bunch of error logs that leads me to this:

http://stackoverflow.com/questions/34557221/php-undefined-function-mysql-connect

Basically looks like FM is us mysql_connect, which is no longer support in php7. But I could have just as easily missed a package install that was removed during the upgrade.

Anyone else running FM on 16.04.1 with php7 on apache?

**Comment by WillyXJ** [comment]
I have yet to test fM with php7, but perhaps this is your solution.

http://stackoverflow.com/questions/35424982/how-to-enable-mysqli-extension-in-php-7

**Comment by wispr** [comment]
Unfortunately no....

I had not found the reference to enable mysqli in php7. Needed to add it to the file and this is what is in php.ini for mysql now:
`/etc/php/7.0/apache2$ fgrep "mysql" php.ini
;extension=php_mysqli.dll
extension=php_mysqli.so
;extension=php_pdo_mysql.dll
[Pdo_mysql]
; If mysqlnd is used: Number of cache slots for the internal result set cache
; http://php.net/pdo_mysql.cache_size
pdo_mysql.cache_size = 2000
; http://php.net/pdo_mysql.default-socket
pdo_mysql.default_socket=
; http://php.net/mysqli.max-persistent
mysqli.max_persistent = -1
; http://php.net/mysqli.allow_local_infile
;mysqli.allow_local_infile = On
; http://php.net/mysqli.allow-persistent
mysqli.allow_persistent = On
; http://php.net/mysqli.max-links
mysqli.max_links = -1
; If mysqlnd is used: Number of cache slots for the internal result set cache
; http://php.net/mysqli.cache_size
mysqli.cache_size = 2000
; Default port number for mysqli_connect().  If unset, mysqli_connect() will use
; the $MYSQL_TCP_PORT or the mysql-tcp entry in /etc/services or the
; http://php.net/mysqli.default-port
mysqli.default_port = 3306
; http://php.net/mysqli.default-socket
mysqli.default_socket =
; Default host for mysql_connect() (doesn't apply in safe mode).
; http://php.net/mysqli.default-host
mysqli.default_host =
; Default user for mysql_connect() (doesn't apply in safe mode).
; http://php.net/mysqli.default-user
mysqli.default_user =
; Default password for mysqli_connect() (doesn't apply in safe mode).
; *Any* user with PHP access can run 'echo get_cfg_var("mysqli.default_pw")
; http://php.net/mysqli.default-pw
mysqli.default_pw =
mysqli.reconnect = Off
[mysqlnd]
; Enable / Disable collection of general statistics by mysqlnd which can be
; http://php.net/mysqlnd.collect_statistics
mysqlnd.collect_statistics = On
; Enable / Disable collection of memory usage statistics by mysqlnd which can be
; http://php.net/mysqlnd.collect_memory_statistics
mysqlnd.collect_memory_statistics = Off
; http://php.net/mysqlnd.net_cmd_buffer_size
;mysqlnd.net_cmd_buffer_size = 2048
; http://php.net/mysqlnd.net_read_buffer_size
;mysqlnd.net_read_buffer_size = 32768`

**Comment by WillyXJ** [comment]
I guess it's time to change fM to use mysqli. :)

**Comment by WillyXJ** [comment]
Until fM supports mysqli, this _should_ work as an interim.

http://www.phpclasses.org/package/9199-PHP-Replace-mysql-functions-using-the-mysqli-extension.html

**Comment by WillyXJ** [comment]
This is now included in 3.0-alpha1 and later.

**Comment by wispr** [comment]
FYI, running through this in the alpah version and the website will load at this point. Getting this error:

Your PHP installation appears to be missing the mysql extension which is required by facileManager.

Let me know if I can get you any more info.

**Comment by WillyXJ** [comment]
Ah, that check was missed.  If you edit fm-includes/init.php line 62, remove 'mysql' from the array.  I'll get this check fixed for the next pre-release.

**Comment by wispr** [comment]
Thanks Jon. Made the change manually, server went through the upgrade process just fine. All of the clients updated as well.

**Comment by wispr** [comment]
FYI, looks like this is broken again. Tried the lastest from the 3.0 branch on github as well. Apache is up and running but the main page won't load at all. You can get the login page to load (after removing mysql from the array in init.php) but after attempting to log in, it'll just sit there and spin.

**Comment by lchanouha** [comment]
linked to #353

**Comment by tedcahall** [comment]
Is there a build version I can download and test on 16.04.1 that corrects this?  Happy to test and start using that.  If not, is there an ETA for that build?

**Comment by WillyXJ** [comment]
The latest unstable version that includes this fix is [3.0-alpha2](http://www.facilemanager.com/download/?t=4).
