### ISSUE TITLE
How stop to create file  in /etc/bind/zones/slaves

### ISSUE THREAD

**Issue by Sporrdig** [WillyXJ/facileManager#344]
Hei i serach the config for stop to create automatically the file in the zone/slave folder. I don't want have the file create d.$domän_name.cout().hosts.

Can please any tell me what i have to change?

**Comment by WillyXJ** [comment]
Hi. The zones/slave directory gets created when you have any slave zones defined or if you have slave servers defined in your server groups.  The files are then created by BIND.  If you don't want any slave zones then you need to make all of your servers masters and one configure master zones.
