### ISSUE TITLE
starting named-chroot vs named in Centos/RHEL 7

### ISSUE THREAD

**Issue by wmerkens** [WillyXJ/facileManager#345]
In the Client code for fmDNS the function getStartupScript() needs a tweak, in RHEL/Centos 7.x when using a chroot named environment you need to start named-chroot not named.  I saw the you do detection of the chroot environment and according to RHEL docs the use of named-chroot is required now. I changed the line for the moment to 

'CentOS'    => array('/etc/init.d/named start', findProgram('systemctl') . ' start named-chroot.service'),

The fmDNS module should have a option switch asking if chroot is being used and based on it change the startup function.

**Comment by WillyXJ** [comment]
Thanks for the report.  I'll have to see how to change the service name based on whether $server_chroot_dir is set or not.  The other distros will also need to be checked for this.

**Comment by WillyXJ** [comment]
This fix is added to fmDNS v2.2.6.
