### ISSUE TITLE
fmDNS client constantly reloading server

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#348]
Hello,
everytime the client starts (/usr/bin/php /usr/local/facileManager/fmDNS/client.php cron), all files are generaterd and bind restarded "server reload successful". The zone files are updated and works.
That should not happen unless i modified my zone or server configuration.

Debug option isn't really helpfull but i found a 500 error *somewere*. I didn't found how you handle your exceptions...
x.x.x.x - - [14/Sep/2016:21:12:16 +0200] "POST /dnsManage/buildconf.php HTTP/1.1" 200 33097 "-" "-"
x.x.x.x - - [14/Sep/2016:21:12:16 +0200] "POST /dnsManage/buildconf.php HTTP/1.1" 500 3688 "-" "-"

Happened and lasted version of client and server (2.3.1).

**Comment by WillyXJ** [comment]
Thanks for the report - this should be included in the next bug fix release.

**Comment by WillyXJ** [comment]
This fix is added to fM v2.3.2.
