### ISSUE TITLE
Rights per zone / Zones with same name in different views

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#349]
This is related to #272.
My cloned zone have the same than the original one si i can't select the proper one in the user rights toolbox.
I suggest to add view name after the domain name to identify the zone for which we want grant access to one user.

**Comment by WillyXJ** [comment]
Thank you for the request.  The domain ID used to be appended to solve this, but was removed in a later version.  Your idea of including the view name makes more sense and will be included in the next bug fix release.

**Comment by WillyXJ** [comment]
This fix is added to fmDNS v2.2.6.
