### ISSUE TITLE
Rights one cloned zones

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#350]
I have two zones:
- x.univ-toulouse.fr
- clone of x.univ-toulouse.fr

I gave one user access to the clone x.univ-toulouse.fr. He can't view the cloned zone, but can access it with direct link zone-records.php?map=forward&domain_id=<cloned_zone_id>&record_type=A

I thiunk this is a problem with (sub)zone grouping function.

**Comment by WillyXJ** [comment]
Thank you for the report.  This is a confirmed bug that will either be included in the next bug fix release or v3.0.

**Comment by WillyXJ** [comment]
This is now included in [3.0-alpha2](http://www.facilemanager.com/download/?t=4) and later.
