### ISSUE TITLE
Support for statistics-channels

### ISSUE THREAD

**Issue by karambol** [WillyXJ/facileManager#352]
Hi,
bind has new monitoring channel via statistics-channels:
statistics-channels {
        inet 127.0.0.1 port 8080 allow { 127.0.0.1; };
};

there is no option to configure this in fmdns (or I didn't know how)

**Comment by WillyXJ** [comment]
Thanks for the request! I'll have to look into how it can be implemented.

**Comment by WillyXJ** [comment]
This is now included in [3.0-alpha2](http://www.facilemanager.com/download/?t=4) and later.
