### ISSUE TITLE
fmHelp is empty in v3.0-alpha1

### ISSUE THREAD

**Issue by aredan** [WillyXJ/facileManager#354]
This is an spin-off from [https://github.com/WillyXJ/facileManager/issues/353](https://github.com/WillyXJ/facileManager/issues/353).

 I just forgot to mention that this is in v3.0-alpha1, in another install of fM that is on 2.2 fmHelp is working.

in v3.0 alpha:
![2016-10-05 12_21_52-sivdc01 siv gov do - putty](https://cloud.githubusercontent.com/assets/939894/19122033/c308c8b6-8af6-11e6-9438-5024227d1e8d.png)

in 2.2:
![2016-10-05 12_21_42-sivdc01 siv gov do - putty](https://cloud.githubusercontent.com/assets/939894/19122043/cbdf1652-8af6-11e6-8027-9a4597edfe43.png)

**Comment by WillyXJ** [comment]
If you enable debug mode, are there any PHP errors?  What happens when you popout fmHelp?

**Comment by aredan** [comment]
I've looking and I don't know how to turn on debug mode. this is something inside fM or directly in PHP?
Running php7 on Debian Sid.

**Comment by WillyXJ** [comment]
Within fM: General Settings -> Show Errors

**Comment by aredan** [comment]
Was already enabled.

 There is no error logs related to fmHelp.

`[Wed Oct 05 18:34:48.719396 2016] [:error] [pid 32563] [client 10.45.252.250:33101] PHP Fatal error:  Uncaught Error: Call to undefined method fm_module_buildconf::updateReloadFlags() in /var/www/fm/fm-modules/shared/pages/buildconf.php:62\nStack trace:\n#0 /var/www/fm/index.php(50): include()\n#1 {main}\n  thrown in /var/www/fm/fm-modules/shared/pages/buildconf.php on line 62
[Wed Oct 05 18:34:50.038386 2016] [:error] [pid 503] [client 10.45.153.2:49530] PHP Fatal error:  Uncaught Error: Call to undefined method fm_module_buildconf::updateReloadFlags() in /var/www/fm/fm-modules/shared/pages/buildconf.php:62\nStack trace:\n#0 /var/www/fm/index.php(50): include()\n#1 {main}\n  thrown in /var/www/fm/fm-modules/shared/pages/buildconf.php on line 62
[Wed Oct 05 18:34:51.228042 2016] [:error] [pid 3366] [client 10.45.153.1:47199] PHP Fatal error:  Uncaught Error: Call to undefined method fm_module_buildconf::updateReloadFlags() in /var/www/fm/fm-modules/shared/pages/buildconf.php:62\nStack trace:\n#0 /var/www/fm/index.php(50): include()\n#1 {main}\n  thrown in /var/www/fm/fm-modules/shared/pages/buildconf.php on line 62
`

only this just after adding a AAAA record to a zone.

**Comment by WillyXJ** [comment]
This has been found with PHP 7 only and the use of preg_replace().  The fix will be included in 3.0-alpha2.
