### ISSUE TITLE
fmFirewall wrong if-pre-up.d script

### ISSUE THREAD

**Issue by air101** [WillyXJ/facileManager#356]
Good Morning,

i recently upgraded to the lastest version of fmFirewall. Everything works fine on Debian except after reboot the network interface didnt come up. This is due to the script /etc/network/if-pre-up.d/fmFirewall.

#!/bin/sh
# This file was built using fmFirewall 1.3.1 on Thu, 10 Nov 2016 11:23:10 +0100 Europe/Berlin

iptables-restore < /usr/local/facileManager/fmFirewall/fw.rules
exit0

the exit0 is the problem. it should be exit 0.

Best Regards

**Comment by WillyXJ** [comment]
Thank you for the report. This fix will be included in the next release.

**Comment by WillyXJ** [comment]
This is now included in [3.0](http://www.facilemanager.com/download/) and later.
