### ISSUE TITLE
DynDNS management

### ISSUE THREAD

**Issue by ghost** [WillyXJ/facileManager#358]
Is it possible to add a new funktion like DynDNS management for the own domains  by user ? There are no good DNS tools like facilemanager. It would made FM **greater than ever before!**

Do you know any other DynDNS management tools?

**Comment by WillyXJ** [comment]
Similar to #177.  It looks like DynDNS has some development tools to interface with their infrastructure (https://help.dyn.com/developers/).  This can be looked into when #177 is worked on; however, a DynDNS account would be required for testing purposes.

**Comment by WillyXJ** [comment]
Merging with #177.
