### ISSUE TITLE
FacileManager authenticate doesn't work when LDAP Authentication  selected. (facileManager v2.3.3)

### ISSUE THREAD

**Issue by AlexeyKukin** [WillyXJ/facileManager#359]
Hello!
I have some LDAP users and main super user account. 
When I try create additional users with facileManager modudle authentication I was unable to log in to web interface with new user account. I try recreate user and make some user with facileManager authenticate for test. No one can login to Web interface. (main super user and LDAP users still can log in)
So, then I've changed LDAP auth to "Builtin Authentication" and all my "test facileManager modudle authentication users" can log in!
So seems when LDAP Authentication is chosen only LDAP and main super user can authenticate.
(for facileManager v2.3.3)

**Comment by WillyXJ** [comment]
Hi.  This is the designed behavior.  When you are using LDAP authentication, the only local account that can still authenticate is the super admin as a fail safe in case the LDAP authentication no longer works.  LDAP and all local accounts should not be able to authenticate - it should be one or the other.
