### ISSUE TITLE
Change initial super user password. (facileManager v2.3.3)

### ISSUE THREAD

**Issue by AlexeyKukin** [WillyXJ/facileManager#360]
Hello!
Please can you help me change password for main (initial) super user? 
![admin pass](https://cloud.githubusercontent.com/assets/23698931/20560929/d7153c92-b18c-11e6-84df-177344270889.jpg)
I can not do anything with this user. (Onle change Email in profile)

facileManager v2.3.3

**Comment by webterror** [comment]
Go to Admin --> User & Groups --> Click on "Actions"

![grafik](https://cloud.githubusercontent.com/assets/20971927/20561130/2cf6492c-b17d-11e6-8bbe-0afa7c9f1de3.png)

You can see the password fields. Type your new password and confirm it in the second field. Click on save.

**Comment by AlexeyKukin** [comment]
Hello.
when LDAP Authentication selected in Actions tab I see N/A please check screenshot.
So, I change method to "Builtin Authentication" and can change password. Then I turn LDAP Authentication back and can login with new password...

**Comment by AlexeyKukin** [comment]
Seems some problems with "mixed"authentication Builtin and LDAP users...
I have another here https://github.com/WillyXJ/facileManager/issues/359

**Comment by WillyXJ** [comment]
Hi.  Thank you for the report.  I have tested and verified this is flawed logic in the code as the local super admin should be able to change have a password change.

**Comment by WillyXJ** [comment]
This is now included in [3.0-alpha3](http://www.facilemanager.com/download/?t=4) and later.
