### ISSUE TITLE
Support Certification Authority Authorization (CAA) Resource Record

### ISSUE THREAD

**Issue by lchanouha** [WillyXJ/facileManager#361]
Bind 9.9.6 supports native CAA record. It would be nice to implement it.
It could be used to on bind < 9.9.6 (RFC 3597 format

https://tools.ietf.org/html/rfc6844
https://sslmate.com/labs/caa/

**Comment by WillyXJ** [comment]
This is now included in [3.0-beta1](http://www.facilemanager.com/download/?t=4) and later.

**Comment by lchanouha** [comment]
@WillyXJ is 3.0-beta considered stable for main features ? I would like to test DNS CAA and DNSSEC features but i don't have a test environment..

**Comment by WillyXJ** [comment]
@lchanouha While I have not seen any functionality issues with the features from 2.x, there are a lot of changes in the core and module code between 2.x and 3.0-beta1 that _could_ impact 2.x features that I have missed in my testing.  For that reason, I cannot recommend the beta versions for production use.
