### ISSUE TITLE
[BUG] Serial number not updated after changing zone's template

### ISSUE THREAD

**Issue by andrewhotlab** [WillyXJ/facileManager#368]
fM Version : **2.3.3**
fmDNS Version : **2.2.6**

**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**Expected Behavior:**
By changing zone's template, a few records are added or removed, and such changes should be propagated to slave DNS servers, thanks to zone's serial number increment.

**Actual Behavior:**
Record changes are applied on master DNS server, but they are not transferred to slaves.

**Steps to reproduce:**
Change the zone template of an existing zone in an environment with at least one master and one slave DNS server.

**Comment by WillyXJ** [comment]
I do not believe this is a bug with fmDNS.  By changing the records of a zone or template, the serial numbers do increment on the masters as you've stated.  I have configured a master-slave relationship within my test environment and slaves are getting the zone updates from the master.

If the zone transfers do not occur at all then it'd be best to troubleshoot if the slaves have permission to transfer from your masters.

If the zone transfers do occur, but slower than you'd like, then you may need to adjust your SOA refresh value.

Here's a KB that might help tune your transfers - https://kb.isc.org/article/AA-00726/0/Tuning-your-BIND-configuration-effectively-for-zone-transfers-particularly-with-many-frequently-updated-zones.html

**Comment by andrewhotlab** [comment]
Sorry, maybe I did not explain well... what I mean is: when I edit a zone which is associated to a template, by choosing another template to link with, this type of change does not cause serial number update, thus different records eventually inherited by the new template are not transferred to slave servers.

**Comment by WillyXJ** [comment]
Thanks for the clarification as I've now been able to reproduce this.
