### ISSUE TITLE
[ISSUE] Secure download

### ISSUE THREAD

**Issue by jovrum** [WillyXJ/facileManager#369]
I'm looking at the releases at http://www.facilemanager.com/download/ and I see that the latest release is version 2.3.3. The site seems to only support plaintext HTTP and no cryptographic signature is offered for the archive files, so there doesn't appear to be a secure way to download the software from the website.

Do the releases on the website correspond to a specific git commit so I could get it from Github? I don't see any git tags in the repository.

**Comment by WillyXJ** [comment]
You are correct that SSL is not supported on the domain as no funding has yet to provide such a service.

There currently are no tags in the commits, but as of right now, master provides the stable 2.3.3.

**Comment by jovrum** [comment]
Right, I see; master is the stable release, and the 3.0-unstable-dev branch is the development tip. Installing from git was painless, I guess the releases are just exact archives of the git repository at a given time? Anyway, thanks :)
