### ISSUE TITLE
named won't start with *pid path in named.conf

### ISSUE THREAD

**Issue by m3morx** [WillyXJ/facileManager#371]
Hi
I'm running a virtual test environment with tow servers. 
The Bindservice can not be started as long as in config is a paht configured where the pid should run.
I can chown and chmod this folder and subfolders as i want, the service won't start!
If i comment this line manually in /etc/named.conf the server starts as expected.
Where can i change the template of this config file or where can i stop putting this line in the config !?

 Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.10.2.el7.x86_64
      Architecture: x86-64

 Could not open '/var/named/named.pid'.
Apr 05 18:05:17 testsystem.local named[5619]: Please check file and directory permissions or reconfigure the file
Apr 05 18:05:17 testsystem.local named[5619]: could not open file '/var/named/named.pid': Permission denied
Apr 05 18:05:17 testsystem.local named[5619]: generating session key for dynamic DNS
Apr 05 18:05:17 testsystem.local named[5619]: sizing zone task pool based on 1 zones
Apr 05 18:05:17 testsystem.local named[5619]: set up managed keys zone for view _default, file 'managed-keys.bind
Apr 05 18:05:17 testsystem.local named[5619]: command channel listening on 127.0.0.1#953
Apr 05 18:05:17 testsystem.local named[5619]: command channel listening on ::1#953
Apr 05 18:05:17 testsystem.local named[5619]: managed-keys-zone: loaded serial 0
Apr 05 18:05:17 testsystem.local named[5619]: zone test.zone/IN: loaded serial 2017040501
Apr 05 18:05:17 testsystem.local named[5619]: all zones loaded
Apr 05 18:05:17 testsystem.local named[5619]: running
Apr 05 18:05:17 testsystem.local named[5619]: zone test.zone/IN: sending notifies (serial 2017040501)
Apr 05 18:05:17 testsystem.local systemd[1]: PID file /run/named/named.pid not readable (yet?) after start.
Apr 05 18:06:40 testsystem.local polkitd[666]: Unregistered Authentication Agent for unix-process:5587:1843368 (s
Apr 05 18:06:47 testsystem.local systemd[1]: named.service start operation timed out. Terminating.
Apr 05 18:06:47 testsystem.local named[5619]: shutting down

**Comment by WillyXJ** [comment]
You can configure the PID file location by going to Config -> Options and edit "pid-file" as you please.  If you don't want it in the configuration, simply delete it from that page.  Changing config options will require a config build to be performed on the servers to pick up the changes.

**Comment by m3morx** [comment]
Thank you, that helped!
i wish there were a better description about functions and how it works.
i.e. i dind't get it how to update nameserver via ssh. Givs me a error, no user. But where i have to define a user. Where i have to put i.e. a password or a key pair...

**Comment by WillyXJ** [comment]
I'm sorry to hear fM is not easy to use.  Whenever error messages are displayed regarding the lack of a SSH user being defined, the message should include a hyperlink that takes you to the General Settings page to define one.  Once it's defined in the web interface, you will need to install (or reinstall) the client so the public key will get installed on the client.

**Comment by m3morx** [comment]
i mean this error
Will nameserver4.aac.ch get updates via cron, ssh, or http(s) [c|s|h]? s
Installation failed.  No SSH user found for this account.

Where have i to define a user ? how is this function working ?
Cron works fine, but have a long delay to apply changes. Actually i did not figured out how to use ssh.

**Comment by WillyXJ** [comment]
In the web interface, you need to define the SSH username and generate a SSH key pair all from the General Settings page (General -> Settings).  Also, from the help page:

> SSH Username
>When servers are configured to receive updates via SSH, this username will be created (if not already present) on your clients and will be used for the client interaction.
>
> 
> SSH Key Pair
> In order for client configs to be updated via SSH, facileManager needs a 2048-bit passwordless key pair generated. Without this key pair, clients cannot use the SSH update method. Click the 'Generate' button to have facileManager automatically generate the necessary key pair.

I hope this helps.

**Comment by m3morx** [comment]
Thanks for you advice.
Now i figured out what i did wrong.
The field SSH Username looks filled with 'fm_user'.
I wonder why is it not created and ended in a error. Please fill the field with other values like e.g. fm_user or something else. Very confusing.

now it works

**Comment by m3morx** [comment]
ok, installation is working ....
After this was successful, im trying to update my server over SSH. 
When i want to Update the config, i get this error.
Failed: could not access ?hostname' using ssh (tcp/22).

I cant see any logon attempts from my management machine to the dns server in /etc/log/secure ...
Is there a log for connections from the management server ?

**Comment by WillyXJ** [comment]
fM does not log any connection attempts.  If your OS is configured to, you can check the system logs.  However, that message does not state the login failed, it states the TCP connection failed.  You ought to check your firewall configuration between your fM server and your clients.

**Comment by WillyXJ** [comment]
Improved error messaging is now included in [the latest beta version](http://www.facilemanager.com/download/?t=4) and later.

**Comment by m3morx** [comment]
dont get it to work :(
On both sides are SSH enabled on firewalld. as well i'v tried with service stopping on both sides. I'm able to connect from management to Nameserver by ssh. but still the same error Failed: could not access ?hostname' using ssh (tcp/22).

**Comment by WillyXJ** [comment]
fM connects to the clients using the hostname, but the names will need to be resolvable in DNS since connections ultimately happen with the IP address.  What messages appear in your authentication logs on the client during these connection attempts?

**Comment by m3morx** [comment]
/var/log/secure
empty
LogLevel VERBOSE

If i open a SSH connection from mgmt via CLI i can see the Login attempt ind secure log.

**Comment by WillyXJ** [comment]
I'm sorry I let this issue drop off for two years.  Was it resolved or does it warrant further discussion and research?

**Comment by WillyXJ** [comment]
The placeholder text in the input fields is now a lighter grey in [fM 3.5.2](http://www.facilemanager.com/download/) and later to hopefully be less confusing.

This issue can be reopened if it's still a problem.
