### ISSUE TITLE
[BUG] Undefined Variable: Return in /Var/www/facileManager.git/server/fm-modules/fmDNS/classes/class_zones.php on Line 1325

### ISSUE THREAD

**Issue by jovrum** [WillyXJ/facileManager#374]
I managed to trigger the following PHP errors when clicking "Add New" on the forward zones page:
![facilemanager_newzone_error](https://cloud.githubusercontent.com/assets/25455921/25228900/6d127218-25ce-11e7-8e24-32c7f55dc7df.png)
Using commit 907423f012be1493ee1c35893ff314a5aad68f6b (HEAD at the time of posting) on both client (one fmDNS client is configured) and server.

**Comment by WillyXJ** [comment]
Feel free to submit pull requests when testing the unstable-dev branch(es).  Thanks.

**Comment by WillyXJ** [comment]
This is now included in [the latest RC version](http://www.facilemanager.com/download/?t=4) and later.
