### ISSUE TITLE
[FEATURE REQUEST] Grouping zones in DNS

### ISSUE THREAD

**Issue by cahluor** [WillyXJ/facileManager#375]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **2.3.3**
fmDNS Version : **2.2.6**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

We are managing multiples zones on multiples dns servers for multiples customers.
It would be nice to be able to create groups for zones,

It would be mostly cosmetic, to be able to display only the zones belonging to a customer for instance, or the zones corresponding to a specific project.

I found a somewhat similar suggestion in issue #211 but it resulted in grouping users for right managements and not grouping zones.

**Comment by lchanouha** [comment]
I can do a +1. 
I splitted my networks on several distinct zones, but some users can access all zones throughout a VPN connexion, so they need local DNS records of all thoses.
Didn't ask because i think it cloud be very complex to implement.

**Comment by WillyXJ** [comment]
Thanks for the feature request.  I'll see how it could be implemented after 3.0 is released.

**Comment by WillyXJ** [comment]
I'm incorporating the groups into user access as well to make it easier to limit zone access. Only users with the super-admin role will be able to manage zone groups.

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 3.1](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by lchanouha** [comment]
Hello,
I have some time today to test this feature.
I just created a "Zone Group", selected two zones, then clicked on the "Save" button.
Then Associated domains remains empty on the tables, and when i re-edit the Group, "Associated Zones" is empty.

I see no errors in logs:
172.16.3.10 - - [22/Dec/2017:10:16:08 +0100] "POST /dnsManage/zones-groups.php HTTP/1.1" 302 28652 "https://xxxxx/dnsManage/zones-groups.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
172.16.3.10 - - [22/Dec/2017:10:16:08 +0100] "GET /dnsManage/zones-groups.php?map=groups HTTP/1.1" 302 28840 "https://xxxxx/dnsManage/zones-groups.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
172.16.3.10 - - [22/Dec/2017:10:16:08 +0100] "GET /dnsManage/zones-groups.php HTTP/1.1" 200 8517 "https://xxxxx/dnsManage/zones-groups.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"

Any idea ?

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.1.2](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by lchanouha** [comment]
@WillyXJ thanks for the patch, my 3 three zones are now affected in my group.
I didn't understood well @cahluor request (needed a master zone wich inherits records from 3 others zones), this is not exactly my usage, but your patch works 

best wishes for 2018 !
Louis
