### ISSUE TITLE
[ISSUE] Build config taking too long

### ISSUE THREAD

**Issue by julianmsanchez** [WillyXJ/facileManager#376]
fM Version : v3.0 beta2
fmDNS Version : v3.0-beta2

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**Expected Behavior:**
Not taking more than a minute.

**Actual Behavior:**
Choosing Build Config even for a single server take 1m 30s average to deploy and show results in the mean time shows "Processing Bulk Action"

**Steps to reproduce:**
Build Config 

Is a new installation, on Linux AMI (Amaozn/Centos based), servers nodes are connected trough SSH. 
I logged them manually from config manager server and time responses are real time. 
Web app work smoothly discarding MySQL slow response times.

Is there a way to debug build config process to see where the lag may come from?

Julian

**Comment by WillyXJ** [comment]
Two questions come to mind on this:

1. Approximately how many zones and records get built?
2. Do you have named checks enabled in the fmDNS settings? (This can take some time to complete if enabled)

**Comment by julianmsanchez** [comment]
Hi!
* There no zones configured yet despite the defaults one
* Enable named Checks is unchecked.

**Comment by WillyXJ** [comment]
With the settings and zones you've reported, there shouldn't be much time required for a config build.  The clients do make a http(s) call back to the management server.  Do you have any firewall rules in that direction that could be the problem?

You can run the config build manually on the clients via the CLI tool in debug mode.  I'm curious if it's just as slow.

`sudo /usr/local/facileManager/fmDNS/client.php -b -d`

**Comment by julianmsanchez** [comment]
Just run the command  locally in one node and took the same time 90 secs in give back result, in the mean time does not show anything. From my understanding result discard some communication problem between the node and the config manager.

**Comment by WillyXJ** [comment]
I'm not convinced it's an issue with the app as it's not reproducible in my test environments yet.  Do you have any firewall rules between your clients and server?  Have you tested the connection between your clients and web server?

**Comment by julianmsanchez** [comment]
Sure it's not discarded the issue could really in our deployment, I would like to let you know a little bit about how is deployed so may be you cold give us a hint:

The environment it's running on AWS, each VM has a shared security group, the DB runs in RDS instance. 

I've done SSH connections from the config manager and there are not any delay, also I connected manually to the RDS from the conf manager and run some queries to tests reply times. 

In general terms could you describe what does the client.php process do, and what do you think the problem may come from? 

Kind regards, 

Julián

**Comment by WillyXJ** [comment]
Regardless of the chosen update method, client.php will perform a HTTP POST to the following URL:

`$url = $proto . '://' . FMHOST . 'buildconf.php';`

It will then get either a string or an array returned based on several conditions (array of file contents is expected).

One quick http test to perform is from the client, run the following (replace FMHOST with your web server hostname/IP):

`curl -k -v "https://FMHOST/admin-accounts.php?verify"`

This should quickly return a serialized string of "Account is not found."  If it's not fast, then there's a communication issue between your clients and web server.  If it is fast, then I'd need some time to think about what else could be the problem. :)

**Comment by julianmsanchez** [comment]
Hi, thanks for the info. 

I've run the command over *http*:
`sudo time curl -k -v "http://myip/
dmin-accounts.php?verify"`

I got a quick reply 
```... 
</div>
* Curl_http_done: called premature == 0
* Closing connection 0
</body></html>0.00user 0.00system 0:00.23elapsed 1%CPU (0av
text+0avgdata 8376maxresident)k
0inputs+0outputs (0major+442minor)pagefaults 0swaps```

*0:00.23elapsed*

Do you think that the fact that the nodes does not have Internet access may be causing the issue?

**Comment by beza2000** [comment]
In this case, I assume, enabled recursion on, but the Internet is either not available or available only through the proxy server. 
The application tries to download named.root from http://www.internic.net/domain/named.root and therefore, so long the command is executed.

**Comment by julianmsanchez** [comment]
That's highly probable I'll give it a try.

**Comment by julianmsanchez** [comment]
After giving the DNS servers permission to reach internet the reload zone takes 15sec but the bould config still the same .

```sudo time php /usr/local/facileManager/fmDNS/client.php -b -d
==================================================
/etc/named.conf:
==================================================
// This file was built using fmDNS 3.0-rc1 on Wed, 23 Aug 2017 20:36:44
...
Reloading the server
server reload successful
Success.
0.01user 0.00system 1:20.65elapsed 0%CPU (0avgtext+0avgdata 15924maxresident)k
0inputs+56outputs (0major+5608minor)pagefaults 0swaps
```
**1:20.65elapsed**

**Comment by beza2000** [comment]
Do you open access from the DNS server to outside on port 80 ?

**Comment by julianmsanchez** [comment]
Yes the DNS server does have full access to outside.

```
[ec2-user@ns-mgr ~]$ curl http://www.internic.net/domain/named.root
;       This file holds the information on root name servers needed to
;       initialize cache of Internet domain name servers
;       (e.g. reference this file in the "cache  .  <file>"
;       configuration file of BIND domain name servers).
;
;       This file is made available by InterNIC
;       under anonymous FTP as
;           file                /domain/named.cache
;           on server           FTP.INTERNIC.NET
;       -OR-                    RS.INTERNIC.NET
...
```

**Comment by WillyXJ** [comment]
Does your fM web server have the same access?  http://www.internic.net/domain/named.root is actually downloaded by the fM server and not the fmDNS clients.

**Comment by julianmsanchez** [comment]
That previous test was done from the fM web server.

**Comment by WillyXJ** [comment]
Two years later and I'm reviewing this issue again.  Sorry about that!  Is this still an issue that needs further discussion and research?
