### ISSUE TITLE
[ISSUE] wrong SOA records in dump.db import - domain is appended on master server and email address fields

### ISSUE THREAD

**Issue by mister-wolf** [WillyXJ/facileManager#377]
fM Version : v3.0-beta2
fmDNS Version : Version 3.0-beta2

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(ISSUE) Expected Behavior:**
When importing a named_dump.db file, SOA records should be correctly parsed.

**(BUG | ISSUE) Actual Behavior:**
SOA records read from dump are written with domain appendix, e.g.:
`domainname.com. IN SOA master.ns.com.domainname.com. master.email.com.domainname.com.`

**(BUG | ISSUE) Steps to reproduce:**
Import a bind named_dump.db - tried on different servers.

PS: is there the possibility to bulk add a SOA template to all zones after zone creation?

Thank you

**Comment by mister-wolf** [comment]
Just checked the database and SOA records are correctly imported with the trailing dot. 

The problem is on field soa_append on table fm_dns_soa, as it was set to YES after import for each row.

**Comment by WillyXJ** [comment]
Thanks for the report.  This behavior also exists in 3.0-rc1 and a SOA import should always *not* append the domain.  This will be fixed in the next release.

**Comment by WillyXJ** [comment]
This is now fixed in [3.0](http://www.facilemanager.com/download/) and later.
