### ISSUE TITLE
[BUG] import tool : importation of NS record for hosts fail if no TTL is set in reverse zone

### ISSUE THREAD

**Issue by cahluor** [WillyXJ/facileManager#378]
fM Version : **2.3.3**
fmDNS Version : **2.2.6**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Import correct records with no explicit TTL

**(BUG | ISSUE) Actual Behavior:**

Import incorrect records with false TTL

**(BUG | ISSUE) Steps to reproduce:**

import a file in a reverse zone with delegated NS entry without explicit TTL

When importing a bind reverse zone file with NS records which are not for the zone but for a specific host, if there is no explicit TTL on the entry, the import tool take the last imported entry as new entry name and current entry as TTL.
Well the sentence is not clear so here is an example :

records in imported files :
100  IN PRT   some.host.domain.
101 IN NS   some.delegated.name.server.
102 IN NS   some.delegated.name.server.

records as interpretted by the import tool :
Record  TTL     CLASS  Type   Value
100                  IN         PTR     some.host.domain.
100       101     IN         NS      some.delegated.name.server.
100       102     IN         NS      some.delegated.name.server.

**Comment by WillyXJ** [comment]
Thanks for the report.  I'm not sure how to fix this so the import tool can automatically (and accurately) detect the record.  You can always edit the entry in the confirmation box before importing.  I'm also open to other ideas.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3](http://www.facilemanager.com/modules/fmdns/) and later.
