### ISSUE TITLE
[BUG]: fmFirewall - Not reloading new iptables on RHEL7

### ISSUE THREAD

**Issue by wzglc6** [WillyXJ/facileManager#379]
fM Version : **v2.3.3**
fmFirewall Version : **1.3.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Successful reload of new iptable rules on RHEL 7

**(BUG | ISSUE) Actual Behavior:**
Not reloading new iptable rules

**(BUG | ISSUE) Steps to reproduce:**
The return string on RHEL7 using lsb tools is: "RedHatEnterpriseServer"
The return string on RHEL7 NOT using lsb tools is: "Red"

lsb_release -a will always return the same string: "RedHatEnterpriseServer" on following RHEL versions: 5,6 & 7

The content of /etc/redhat-release is: "Red Hat Enterprise Linux Server release 7.3 (Maipo)" (and will change with every major OS upgrades). 

 684                 /** Redhat-based systems */
 685                 if (file_exists($filename = '/etc/redhat-release')
 686                         && $rh_release = file_get_contents($filename)) {
 687                          $rh_release = explode(' ', $rh_release);
 688                          return $rh_release[0];
 689                 }

Will return:
array(8) {
  [0]=>
  string(3) "Red"
  [1]=>
  string(3) "Hat"
  [2]=>
  string(10) "Enterprise"
  [3]=>
  string(5) "Linux"
  [4]=>
  string(6) "Server"
  [5]=>
  string(7) "release"
  [6]=>
  string(3) "7.3"
  [7]=>
  string(8) "(Maipo)"
};

**Comment by WillyXJ** [comment]
Thanks for the report.  The return value when not using lsb was fixed in the 3.0 pre-releases for fM-core.  The fix when using lsb is now fixed and will be included in the next release.

**Comment by WillyXJ** [comment]
This is now included in [3.0](http://www.facilemanager.com/download/) and later.
