### ISSUE TITLE
[BUG] fmFirewall not detecting firewall

### ISSUE THREAD

**Issue by air101** [WillyXJ/facileManager#383]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.0.1**
{Module Name} Version : **1.4.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:** Detect installed Firewall

**(BUG | ISSUE) Actual Behavior:** Detect Firewall and finish client setup

**(BUG | ISSUE) Steps to reproduce:** Latest Debian Jessie

When installing fmFirewall on a new system, this is what happens:

Please enter the serial number for xxx-my-serve (or leave blank to create
new): 695518096
  --> Adding xxx-my-server to the database...Success
  --> Detecting firewall...root@xxx:~#

**Comment by WillyXJ** [comment]
Confirmed bug and will be fixed in the next release.

**Comment by WillyXJ** [comment]
This is now fixed in [1.4.2](http://www.facilemanager.com/modules/fmfirewall/) and later.
