### ISSUE TITLE
[FEATURE REQUEST] fmDNS: allow to set Views with Templates too

### ISSUE THREAD

**Issue by internethering** [WillyXJ/facileManager#384]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.0.1**
{Module Name} Version : **3.0.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

* I'm using a router running by Openwrt and the DHCP/DNS server has as local domain configured `example.net`
* my server with facileManager and the router are connected by OpenVPN

in facileManager:
* I've two views: `ext` for requests from the internet & `int` for requests from the intranet/vpn
* I've a template called `tpl`, which is configured for _All Views_
* I added zone `example.net` with params: _Type_ `forward`, _Views_ `int`

**(FEATURE REQUEST) Actual Behavior:**

I want to add zone `example.net` with param: _Template_ `tpl`. Setting _Views_ isn't possible.
Building config fails with: 

> /var/bind/zones.conf.int:191: zone 'example.net': already exists previous definition: /var/bind/zones.conf.int:187

I had to create a Template `tpl2` with same config like `tpl` - only _Views_ `ext` is different. If I want change my template, I've to do it double times at the moment.

**(FEATURE REQUEST) Expected Behavior:**

Please allow to set _Views_ when using _Template_.

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 3.1](http://www.facilemanager.com/modules/fmdns/) and later.
