### ISSUE TITLE
[OTHER] Warning - ignoring session_start()

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#386]
fM Version : 3.0.2
fmdns Version : 3.0.3

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When I Upgrade or Build Config my server, I wouldn't like to get warnings in apache log.

**(BUG | ISSUE) Actual Behavior:**
I have warnings in error log.
ssl_access_log:
xxx.xxx.xxx.254 - - [09/Aug/2017:14:56:50 +0300] "POST /facileManager/server/admin-servers.php?upgrade HTTP/1.1" 500 -
ssl_error_log:
[Wed Aug 09 14:56:50.961625 2017] [:error] [pid 11459] [client xxx.xxx.xxx.254:33017] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/html/facileManager/server/fm-includes/i18n.php on line 33

**(BUG | ISSUE) Steps to reproduce:**
Config->Servers-> Upgrade or Build Config

**Comment by WillyXJ** [comment]
This is now fixed in [fM Core 3.0.3](http://www.facilemanager.com/download/) and later.
