### ISSUE TITLE
 [BUG] [ISSUE] Logging Method to syslog

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#387]
fM Version : 3.0.2
fmdns Version : 3.0.3

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---
I don't sure that it is bug.

**(BUG | ISSUE) Expected Behavior:**
If I set 'Logging Method' to 'syslog' and 'Syslog Facility' to  'syslog' , I wait that all messages are placed in the syslog and with the date & time.

**(BUG | ISSUE) Actual Behavior:**
I have the messages in 2 files and 2 formats.
It is good - /var/log/messages:
...
Aug  9 15:25:36 localhost facileManager:  --> Log Method: syslog
Aug  9 15:26:14 localhost fmDNS: Configuration Build was performed on server 'kermit.auriga.ru'.
...
I don't like it - /var/log/httpd/error_log:
...
facileManager:   --> Log Method: syslog
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not create directory '/usr/share/httpd/.ssh'.
...
Also 'Show Errors'  is set On.

**Comment by WillyXJ** [comment]
I don't see this as a bug or anything wrong.  When Show Errors is enabled, there will be more logging and output.
