### ISSUE TITLE
[FEATURE REQUEST] Add to support proxy-server

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#388]
fM Version : **3.0.2**
{Module Name} Version : **3.0.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

fmDNS: need to add the option of proxy server to download named.root from http://www.internic.net/domain/named.root if the Internet is available only through the proxy server in the local network.
In addition, the code required to download a file from the Internet using a proxy-server in function getLatestRootServers in file facileManager/server/fm-modules/fmDNS/classes/class_buildconf.php. Something like stream_context_set_default before get_headers.

**Comment by fruza** [comment]
Yes, we have the same problem. We are behind a corporate proxy and fmDNS try to download the file http://www.internic.net/domain/named.root and it timeouts. We are trying to set HTTP_PROXY environment variable in apache (redhat in /etc/sysconfig/httpd) with no luck.

**Comment by WillyXJ** [comment]
I see this support being added to the core with proxy settings defined in the General Settings.

**Comment by WillyXJ** [comment]
Commit has been added for the web server to use a proxy server.  A solution still needs to be implemented for the clients as they access the Internet only for client software updates.

**Comment by WillyXJ** [comment]
This is now implemented in [fM 3.4](http://www.facilemanager.com/download/) and later.
