### ISSUE TITLE
[ISSUE] Why is the key-file called named.conf.keys?

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#389]
fM Version : **3.0.2**
fmDNS Version : **3.0.3**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Define some key_id and control.
Do Build Config.
It is Ok.

**(BUG | ISSUE) Actual Behavior:**

Modal windows - Build Config Results:

kermit
 --> Configuration Build Results
 --> 		
 --> 		
 --> 		
 --> 
 --> [kermit] rndc: connection to remote host closed
 --> [kermit] This may indicate that
 --> [kermit] * the remote server is using an older version of the command protocol,
 --> [kermit] * this host is not authorized to connect,
 --> [kermit] * the clocks are not synchronized, or
 --> [kermit] * the key is invalid.
 --> [kermit] rndc: connection to remote host closed
 --> [kermit] This may indicate that
 --> [kermit] * the remote server is using an older version of the command protocol,
 --> [kermit] * this host is not authorized to connect,
 --> [kermit] * the clocks are not synchronized, or
 --> [kermit] * the key is invalid.

Complete. 

**Comments**

I use CentOS 7. 
rndc utility use the default key file - /etc/rndc.key (man RNDC(8)).
If I define a key in the fmDNS, the key is written in named.conf.keys.
When I do Build Config, the client invokes a command ("/bin/php /usr/local/facileManager/fmDNS/client.php buildconf"), in which rndc is invoked without the option "-k", i.e. rndc search and read the default key file - /etc/rndc.key

I don't understand - Why is the key-file called named.conf.keys?

**Comment by WillyXJ** [comment]
Sorry for the extremely late response...

fmDNS puts TSIG keys in named.conf.keys per https://bind9.readthedocs.io/en/v9_16_5/advanced.html#tsig which implies rndc.key would be managed outside of named.conf (and subsequently fmDNS).

**Comment by WillyXJ** [comment]
This is now improved in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by nikpael** [comment]
thanks for the work around. in reality I save in named.conf.key a key (key1) that I then use to update with nsupdate a zone (allow-update and value key1). it almost seems that since there is the named.conf.key file, whatever the content, the key for the rndc command is taken.
