### ISSUE TITLE
[BUG] Require Group Membership not working

### ISSUE THREAD

**Issue by fruza** [WillyXJ/facileManager#392]
fM Version : **3.0.2**
fmDNS Version : **3.0.3**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Hi, I have setup authentication with ldap in facileManager version: 2.3.3 and it's working correctly however, when I have configured in a new server exactly in the same way now with facileManager version: 3.0.2 it doesn't work. I cannot see any error in the apache logs, neither in the facileManager logs.

I have realized that without enable "Require Group Membership" it works fine but when I check and fill the following fields it doesn't work:

"Group Distinguished Name (DN)": cn=sysadm,ou=Groups,dc=sescam,dc=jclm,dc=es
"Group Member Attribute": memberUid

Our ldap logs shows the following when I try to login with my user "ffrr12":

> [13/Sep/2017:14:55:04 +0200] conn=347393 op=0 msgId=1 - BIND dn="uid=ffrr12,ou=Users,dc=sescam,dc=jclm,dc=es" method=128 version=2
> [13/Sep/2017:14:55:04 +0200] conn=347393 op=0 msgId=1 - RESULT err=0 tag=97 nentries=0 etime=0 dn="uid=ffrr12,ou=users,dc=sescam,dc=jclm,dc=es"
> [13/Sep/2017:14:55:04 +0200] conn=347393 op=1 msgId=2 - SRCH base="uid=ffrr12,ou=users,dc=sescam,dc=jclm,dc=es" scope=2 filter="(samaccountname=ffrr12)" attrs="dn"
> [13/Sep/2017:14:55:04 +0200] conn=347393 op=1 msgId=2 - RESULT err=0 tag=101 nentries=0 etime=0
> [13/Sep/2017:14:55:04 +0200] conn=347393 op=2 msgId=3 - SRCH base="" scope=0 filter="(objectClass=*)" attrs="memberUid"
> [13/Sep/2017:14:55:04 +0200] conn=347393 op=2 msgId=3 - RESULT err=0 tag=101 nentries=1 etime=0
> [13/Sep/2017:14:55:04 +0200] conn=347393 op=3 msgId=4 - UNBIND

It seems the search base for the "Group Member Attribute" is empty: SRCH base="".

As I said before, this worked fine in facileManager 2.3.3. Any clue or advise if I'm doing something wrong?, it seems a bug or change in this version.

Thanks in advanced for any reply. Regards.

Fernando.

**Comment by WillyXJ** [comment]
LDAP auth was changed in fM 3.0 based on #342 to support AD better. It seems this change works with AD, but not LDAP now.  I think I'll need to revert back to using ldap_compare() for LDAP connections and $this->checkGroupMembership() for AD connections.

**Comment by fruza** [comment]
Thanks WillyXJ. It works like a charm. Great!!

**Comment by WillyXJ** [comment]
Thank you for the quick test and confirmation.

**Comment by WillyXJ** [comment]
This is now fixed in [fM Core 3.0.3](http://www.facilemanager.com/download/) and later.
