### ISSUE TITLE
[ISSUE] Need use 'trim' for input fields.

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#394]
fM Version : **3.0.2**
fmDNS Version : **3.0.3**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
If I add new Domain Name with a whitespace at the end in Reverse Zones, it turns out error 'Invalid zone name'.

**(BUG | ISSUE) Actual Behavior:**
The whitespace at the beginning or end of the Domain Name should be removed.

When I copy the new Domain Name, accidentally I can be captured the whitespaces. The output error does not allow to understand where is the error. In such cases, it would be well, if it uses 'trim' of the Domain Name.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.0.4](http://www.facilemanager.com/modules/fmdns/) and later.
