### ISSUE TITLE
[FEATURE REQUEST] Add support to forward records to URLs

### ISSUE THREAD

**Issue by WillyXJ** [WillyXJ/facileManager#396]
fM Version : **3.0.2**
fmDNS Version : **3.0.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Some hosting companies provide DNS record to URL forwarding which is not a function of a DNS server.  However, this could be a handy feature to implement in fmDNS using httpd or nginx.

Example, foo.bar.com should send clients to www.foobar.com/some/landing/page.html

**Comment by chandro** [comment]
Yes please, this will be great :p

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 4.0-beta1](http://www.facilemanager.com/modules/fmdns/?t=3) and later. Testing is requested. Final release will come out later.

**Comment by WillyXJ** [comment]
[fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) has been released.
