### ISSUE TITLE
[ISSUE] fmDNS views - there is no mechanism to order views

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#397]
fM Version : **3.0.2**
fmDNS Version : **3.0.3**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

From http://www.zytrax.com/books/dns/ch7/view.html:
"view clauses are processed in the order in which they appear in the named.conf file. "

**(BUG | ISSUE) Expected Behavior:**
I have:
```
view "internal" {
	match-clients { localnets; localhost; };
	recursion yes;
	include "/etc/named/zones/zones.conf.internal";
};

view "external" {
	match-clients { any; };
	include "/etc/named/zones/zones.conf.external";
};
```

**(BUG | ISSUE) Actual Behavior:**
```
view "external" {
	match-clients { any; };
	include "/etc/named/zones/zones.conf.external";
};
view "internal" {
	match-clients { localnets; localhost; };
	recursion yes;
	include "/etc/named/zones/zones.conf.internal";
};
```

**(BUG | ISSUE) Steps to reproduce:**
I create view "external", then "internal".

In /etc/named.conf "view" are inserted in the order of their creation. 
If I have multiple "views" and decide to change their order, it will not be possible. To solve this problem in the current implementation I have to remove all the "view" and create them in the new order.

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 3.1](http://www.facilemanager.com/modules/fmdns/) and later.
