### ISSUE TITLE
[BUG]  Supports recursive lookups don't work when I use Views.

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#398]
fM Version : **3.0.2**
fmDNS Version : **3.0.3**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---
Excuse me that I repeat, but "fmDNS - Add support for named.root" is closed and my question remained unanswered.
**(BUG | ISSUE) Expected Behavior:**
When I use "recursion yes" in view, fmDNS should automatically build/include named.root to my /etc/named/zones/zones.conf.internal. 
```
view "internal" {
	match-clients { our_localnets; localhost; };
	recursion yes;
	include "/etc/named/zones/zones.conf.internal";
};

```
**(BUG | ISSUE) Actual Behavior:**
It doesn't work.
It works only I use  "recursion yes" in  Global Options.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.1](http://www.facilemanager.com/modules/fmdns/) and later.
