### ISSUE TITLE
[FEATURE REQUEST] external plaintext backup.

### ISSUE THREAD

**Issue by dayton967** [WillyXJ/facileManager#403]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **2.0.3**
fmDNS Version : **2.0.4**

Instead of doing the Database dump, creating an export of the configuration in something such as XML or JSON, that can be imported back into facileManager.  This would allow for any future changes such as supporting multiple database servers, or large changes by maria or mysql could be then ignored.

**Comment by WillyXJ** [comment]
I've finally been able to look at this request and what it would take to implement it.  phpMyAdmin supports exporting and importing databases in XML format.  Would that accomplish what you are looking for?
