### ISSUE TITLE
[BUG] Error in fmDNS/upgrade.php

### ISSUE THREAD

**Issue by gianlucagiacometti** [WillyXJ/facileManager#404]
fM Version : 3.1
{Module Name} Version : fmDNS

In raising this issue, I confirm the following:

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

(BUG | ISSUE) Expected Behavior:
Upgrade of fmDNS schema OK

(BUG | ISSUE) Actual Behavior:
Upgrade of fmDNS fails

(BUG | ISSUE) Steps to reproduce:
Upgrade from version 3.0.4

{replace this line with your issue content}

There a missed comma in the SQL code in server/fm-modules/fmDNS/upgrade.php
`group_status` enum('active','disabled','deleted') NOT NULL
should be
`group_status` enum('active','disabled','deleted') NOT NULL,

**Comment by WillyXJ** [comment]
Well, that's embarrassing!  Thanks for the quick report and this is now fixed in [fmDNS 3.1.1](http://www.facilemanager.com/modules/fmdns/) and later. You will most likely need to restore your DB back to 3.0.4 before upgrading to 3.1.1 now.
