### ISSUE TITLE
[BUG] facileManager username displayed in logs

### ISSUE THREAD

**Issue by Pierre-CHABREDIER** [WillyXJ/facileManager#405]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 3.1.0
fmDNS Version : 3.0.4

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
With the previous FM version (3.0.4) it was displayed which user performed which action.

**(BUG | ISSUE) Actual Behavior:**
With the actual fM version (3.1.0) now every action is attributed to facileManager (user wich doesn't exists).

**(BUG | ISSUE) Steps to reproduce:**
Update from facileManager 3.0.4 to 3.1.0, go to log tab, and view difference before and after update.

It's maybe related to the changelog entry : * Server - [improvement] fm_logs now stores the username instead of userid.

PS : Sorry for my bad English.

**Comment by WillyXJ** [comment]
I've confirmed the username displayed is 'facileManager' for entries/changes made after the upgrade.  The upgrade process does retain the usernames of the previous entries though.

**Comment by WillyXJ** [comment]
This is now fixed in [fM Core 3.1.1](http://www.facilemanager.com/download/) and later.
