### ISSUE TITLE
[FEATURE REQUEST] view all record types

### ISSUE THREAD

**Issue by masti93** [WillyXJ/facileManager#406]
Hello,

it will be great, if you can add a feature to view all records from a zone and offer the possibility to edit this entries.

It will be also great, if it is possible to add different record time at one time.

Thanks,
Martin

**Comment by WillyXJ** [comment]
Hi Martin,

Thanks for the suggestion.  Do you have any ideas for how the UI would look to accomplish this?  Right now the RR types are split because the form fields are different for each type of RR.

**Comment by adlp** [comment]
Hello,

@WillyXJ , I thinks a simple TEXTAREA of a zone dump may be very usefull for the begening !

**Comment by WillyXJ** [comment]
While I'm still figuring out how to support edits, you are able to preview a zone configuration by clicking the magnifying glass in the Actions column of the zones page. This functionality has been available since fmDNS 1.3 and perhaps is sufficient for the viewing request.

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 7.0.0-beta3](https://www.facilemanager.com/modules/fmdns/?t=3) and later.
