### ISSUE TITLE
DHCP Options - DNS Servers

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#407]
Trying to find the correct option in FM to set the DNS servers in a given subnet in DHCP. Sample config from ubuntu wiki is below, but the option for domain-name-servers seems to be missing.

Added: same thing with default gateways, specifically option routers

# Sample /etc/dhcpd.conf
default-lease-time 600;
max-lease-time 7200;
option subnet-mask 255.255.255.0;
option broadcast-address 192.168.1.255;
option routers 192.168.1.254;
option domain-name-servers 192.168.1.1, 192.168.1.2;
option domain-name "mydomain.example";

subnet 192.168.1.0 netmask 255.255.255.0 {
range 192.168.1.10 192.168.1.100;
range 192.168.1.150 192.168.1.200;
}

**Comment by WillyXJ** [comment]
Big oversight you found.  Not only is domain-name-servers missing, but routers is missing, too!

**Comment by wispr** [comment]
Ok, well glad I'm not crazy. We can manually add them to the conf file on the server and all works as it should. But as soon as the config change is written from FM, it overwrites and then it stops working. Push it in the next update and we'll keep testing.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.2](http://www.facilemanager.com/modules/fmdhcp/) and later.
