### ISSUE TITLE
Htaccess fails after changing pannel IP

### ISSUE THREAD

**Issue by zm0k4h** [WillyXJ/facileManager#410]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 3.1.1
FMDNS Version : 3.1.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

After i changed pannel IP and put behind nat the following message appear:

Requirement Error The required .htaccess file appears to not work with your Apache configuration which is required by facileManager. AllowOverride None in your configuration may be blocking the use of .htaccess.
Try Again

I checked permissions .htaccess and still ok

**Comment by WillyXJ** [comment]
I'm sorry for the lack of response.  Is this still an issue?  Changing IPs of the fM server shouldn't impact the rewrite rule.
