### ISSUE TITLE
[FEATURE REQUEST] sort reverse zone

### ISSUE THREAD

**Issue by cahluor** [WillyXJ/facileManager#411]
fM Version : **3.1.1**
fmDNS Version : **3.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Just as request #278 about hierarchical sorting of forward zones,
Would it be possible to have the same sort option for reverse zones.

** Expected Behavior:**
zones sorted like this

25.5.10.in-addr.arpa
25.100.10.in-addr.arpa
127.in-addr.arpa
100.168.192.in-addr.arpa
101.168.192.in-addr.arpa
230.168.192.in-addr.arpa
231.168.192.in-addr.arpa

** Actual Behavior:**
zones sorted like this

100.168.192.in-addr.arpa
101.168.192.in-addr.arpa
127.in-addr.arpa
230.168.192.in-addr.arpa
231.168.192.in-addr.arpa
25.100.10.in-addr.arpa
25.5.10.in-addr.arpa

**Comment by WillyXJ** [comment]
I need some help on this one as I haven't found a working MySQL query that will do that kind of sorting.

**Comment by CrazyLittle** [comment]
Since all subnets have an network IP and all IPs can be represented as decimal, perhaps store the reverse zone network address and the write your SQL query to sort based on that info?

**Comment by WillyXJ** [comment]
The issue with that idea is there would be a lot more processing time required for both the UI and client-server interaction for little gain. I'll keep thinking of a solution.

**Comment by cahluor** [comment]
Here is a working sql request to sort the reverse domains.
Tested with mariadb 10.3.22

SELECT domain_name,
       REGEXP_SUBSTR(domain_name, '\\K[0-9]+') AS digits1,
       REGEXP_SUBSTR(domain_name, '[0-9]+\.\\K[0-9]+') AS digits2,
       REGEXP_SUBSTR(domain_name, '[0-9]+\.[0-9]+\.\\K[0-9]+') AS digits3
FROM   `fm_dns_domains` WHERE domain_mapping = 'reverse'
ORDER BY digits3, digits2, digits1;

**Comment by WillyXJ** [comment]
@cahluor  I think that query has some potential, but unfortunately digits1, digits2, and digits3 all return NULL on MySQL v8.1.0 and MariaDB v10.5.8 for me.

**Comment by WillyXJ** [comment]
This query works in MariaDB 10.x, but not MySQL as the latter does not support \K regex.

```
SELECT domain_name,
LPAD(REGEXP_SUBSTR(domain_name, '\\K[0-9]+'),3,0) AS a,
LPAD(REGEXP_SUBSTR(domain_name, '[0-9]+.\\K[0-9]+'),3,0) AS b,
LPAD(REGEXP_SUBSTR(domain_name, '[0-9]+.[0-9]+.\\K[0-9]+'),3,0) AS c
FROM `fm_dns_domains` WHERE domain_mapping='reverse' ORDER BY c , b , a , `domain_name`;
```

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
