### ISSUE TITLE
process update get errors.

### ISSUE THREAD

**Issue by keith2008** [WillyXJ/facileManager#412]
fM Version : v3.1.1 
{Module Name} Version : v3.1.2

i added some Zones and config, when i process all updates,got the following errors:
------------------------------
Notice: Uninitialized string offset: 0 in /var/www/html/facileManager/fm-modules/fmDNS/classes/class_buildconf.php on line 712 Notice: Uninitialized string offset: 0 in /var/www/html/facileManager/fm-modules/fmDNS/classes/class_buildconf.php on line 712

Updates Results
localhost
 --> Configuration Build Results
 --> 		
 --> 		
 --> 		
 --> 			
 --> 				The webserver user (apache) on CDN1 does not have permission to run the following command:The following error ocurred:

All updates have been processed.
------------------------------------

and the bind config does not generate. 
can anyone help me? Any of your help will be appreciated! 
@WillyXJ

**Comment by WillyXJ** [comment]
What do you have for your fmDNS servers?  Line 712 is inside code that loops over all configured fmDNS servers and in your case is coming back empty.

**Comment by chandro** [comment]
Hello, i am having this issue right now.

i moved my panel to another hosting site, and now i am getting error

The webserver user (myuser) on my.server.com does not have permission to run the following command: -blank-

The following error ocurred: -blank-
