### ISSUE TITLE
[ISSUE] found DS RRset without NS RRset when configuring DNSSEC

### ISSUE THREAD

**Issue by MeCJay12** [WillyXJ/facileManager#419]
Please ignore till after the holiday. I am just trying to avoid family.

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 3.2
fmDNS Version : 3.2

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
I am trying to setup DNSSEC so I need to provide the NS/DS RR to my registrar. I expect this to be a file on the disk, an entry in the UI somewhere (ideal), or at least in the database somewhere.

**(BUG | ISSUE) Actual Behavior:**
"Found DS RRset without NS RRset" appears in config file. I recognize this is not an issue itself but that I need to add the NS records to my registrar. I just can't figure out where the record is.

**(BUG | ISSUE) Steps to reproduce:**
Generate key for zone, sign zone, enable DNSSEC on zone, issue will appear in viewable server config file.

**Comment by WillyXJ** [comment]
Are you letting fmDNS generate the key for the zone or providing your own key?  The former should then generate the DS RR.  It's also possible there is some missing logic...

**Comment by MeCJay12** [comment]
You'll have to forgive me, I did this a while ago so I don't remember exactly.

There was a package I had to install to speed up the process otherwise it would take days to generate the key. After that package was installed, yes, I had FM generate and install the keys/certs. When I went to my DNS provider to enter my records I couldn't find them in FM and I don't know where to look in the file structure.

**Comment by WillyXJ** [comment]
I appreciate you testing out the DNSSEC support in fmDNS while it's still experimental.  I have found in my test environment that the NS RRset is shown in the server config preview window for the zone (which ultimately is the same as the zone file on the DNS servers).  This may or may not be ideal.  Do you get the same results?  Essentially, it should be in the zone file after it's been signed.

**Comment by WillyXJ** [comment]
You made two points here:

1. This can be a feature request - DS RR should be available to provide to a registrar if the zone is the parent.
2. DNSSEC keys can be deleted, but only if they are not the current signing key or have been revoked.  The idea is to prevent accidental deletion of your active signing key.

Thanks!

**Comment by MeCJay12** [comment]
1. Yup. I'll get that posted.

2. I noticed that shortly after posting the comment.

 Thanks for the help!

**Comment by dssantos83** [comment]
Hello MeCJay12,
You said that "There was a package I had to install to speed up the process otherwise it would take days to generate the key."
Wich package is this?
I'm facing this problem.
Thanks

**Comment by MeCJay12** [comment]
> Hello MeCJay12,
> You said that "There was a package I had to install to speed up the process otherwise it would take days to generate the key."
> Wich package is this?
> I'm facing this problem.
> Thanks

Sorry for the delayed reply, I found the package back in November and I couldn't remember what it was. The package is haveged installed on Ubuntu with
`apt-get install haveged`
Good luck. hit me up with any other questions. I tried to layout my steps here because it wasn't well documented when I went through the process.

**Comment by dssantos83** [comment]
MeCJay12,
Thank you so much.
I have installed haveged e it worked like a charm.

**Comment by dssantos83** [comment]
Now I have the "found DS RRset without NS RRset" problem.
How have you solved this?
Tks

**Comment by MeCJay12** [comment]
That's because you need to put your DS record into your registrar. I can't really tell you exactly how to do that because it's different with each registrar but I can tell you how to get the info from FM. Go to the zone you are working on. In the options, one says add DNSSEC keys to parent zone with a drop down (or something like that). Pick another zone in the drop down (doesn't matter which zone). Click ok then go view the config for the other zone. All the way at the bottom there will be two lines with the info you need to give your registrar.

**Comment by dssantos83** [comment]
MeCJay12, thank you for your support.
I read again your comments above and I've just got it.
Now it's working.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3](http://www.facilemanager.com/modules/fmdns/) and later.
