### ISSUE TITLE
[BUG]fmDHCP peer declaration

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#421]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.2**
{fmDHCP} Version : **0.2**

**(BUG | ISSUE) Expected Behavior:**

Declaring a peer is not working in the correct way

A peer in isc-dhcp should look like this:

failover peer "dhcp-failover" {
  primary; # declare this to be the primary server
  address ip-of-primary;
  port 647;
  peer address ip-of-secondary;
  peer port 647;
  max-response-delay 30;
  max-unacked-updates 10;
  load balance max seconds 3;
  mclt 1800;
  split 128;
}

**(BUG | ISSUE) Actual Behavior:**
in fmDHCP it looks like this:

failover peer "dhcp-failover" {
  primary; # declare this to be the primary server
  address fqdn-primary;
  port 647;
  peer-address fqdn-secondary;
  peer-port 647;
  max-response-delay 30;
  max-unacked-updates 10;
  load balance max secs 3;
  mclt 1800;
  split 128;
}

isc-dhcp fails when there is a "-" between peer address and peer port statement.
Also the load balance max secs should be load balance max seconds

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.3](http://www.facilemanager.com/modules/fmdhcp/) and later.

**Comment by cm91** [comment]
Unfortunately the "load balance max secs"  is also included in fmDHCP 0.3. It should be "load balance max seconds".
