### ISSUE TITLE
[BUG] network declaration for dhcp peer

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#422]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.2*
{fmdhcp} Version : **0.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

network has to be declared befor the pool.

shared-network testlan {
        authoritative;
        default-lease-time 3600;
        max-lease-time 3600;
        option routers 10.10.0.1;
        option subnet-mask 255.255.255.0;
        option broadcast-address 10.10.0.255;
        option domain-name "test.lan";

        subnet 10.10.0.0 netmask 255.255.255.0 {

        pool {
                range 10.10.0.100 10.10.0.200;
                failover peer "dhcp-test";
        }

        }
}

**(BUG | ISSUE) Actual Behavior:**

When using dhcp peer option i have declared:

1. shared network 
2. network
3. pool

I assigned the network and the pool to the shared network and it looks like this:

shared-network testlan {
        authoritative;
        default-lease-time 3600;
        max-lease-time 3600;
        option routers 10.10.0.1;
        option subnet-mask 255.255.255.0;
        option broadcast-address 10.10.0.255;
        option domain-name "test.lan";

        pool {
                range 10.10.0.100 10.10.0.200;
                failover peer "dhcp-test";
        }

        subnet 10.10.0.0 netmask 255.255.255.0 {
        }
}

The Problem is, that the pool is declared before the network declaration --> isc.dhcp fails!

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.3](http://www.facilemanager.com/modules/fmdhcp/) and later.
