### ISSUE TITLE
[BUG] PHP Error with Add More Records

### ISSUE THREAD

**Issue by sheepsong** [WillyXJ/facileManager#423]
fM Version : **3.2.0**
fmDNS Version : **3.2.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:
Show more lines for input when clicking "Add more records" button in Zones as records inputs above.
**

**(BUG | ISSUE) Actual Behavior:
Showing lines without tr tags and notice undefined variable record_ptr_id in fm-modules/fmDNS/classes/class_records.php on line 464
**

**(BUG | ISSUE) Steps to reproduce:
Just click on button Add more records
**

Showing lines without tr tags and notice undefined variable record_ptr_id in fm-modules/fmDNS/classes/class_records.php on line 464.
```
463    /** Linked PTR */
464    				if ($record_ptr_id) {
465    					$field_values['data']['Value'] .= ' <a href="#" class="tooltip-right" data-tooltip="' . __('Linked PTR exists') . '"><i class="mini-icon fa fa-exchange"></i></a>';
466    				}
```
Maybe it is need to be sure $record_ptr_id is defined.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.2.1](http://www.facilemanager.com/modules/fmdns/) and later.
