### ISSUE TITLE
DHCP Peer: load balance max seconds

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#424]
Please prefix your issue title with one of the following: [BUG]

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.3**
{fmDHCP} Version : **0.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG) Expected Behavior:**

In DHCP Peer declaration there is a parameter for load balance max seconds.
The parameter should be "load balance max seconds"

**(BUG | ISSUE) Actual Behavior:**

In fmDHCP the parameter is "load balance max secs"
isc-dhcp does not understand that and fails.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.3.1](http://www.facilemanager.com/modules/fmdhcp/) and later.  Although, it may crop up because I think ISC changed the option between versions at some point.  I have yet to figure out which version though.

**Comment by cm91** [comment]
The parameter now get created with underscores:  load_balance_max_seconds 3;

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.3.2](http://www.facilemanager.com/modules/fmdhcp/) and later.  For real this time. :)

**Comment by cm91** [comment]
Thanks so much, now it work :)
Can you please tell me, how you fixed that? I tried to fix that by myself in an earlier version but always got stuck on that underscore issue.
