### ISSUE TITLE
[BUG]: Declaration of the secondary DHCP Peer

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#425]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.3**
{Module Name} Version : **0.31**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

===========================================================================
/etc/dhcp/dhcpd.conf:
===========================================================================
# This file was built using fmDHCP 0.3.1 on Sun, 16 Dec 2018 09:49:30 +0100 Europe/Berlin

## peer items ##
failover peer "failover" {
	secondary;
	peer address dhcp2.local;
	peer port 847;
	address dhcp1.local;
	port 647;
	max-response-delay 30;
	max-unacked-updates 10;
}

## shared items ##
shared-network 10.10.0.0 {
	authoritative;

	subnet 10.10.0.0 netmask 255.255.255.0 {
		authoritative;

		pool {
			range 10.10.0.10 10.10.0.20;
			failover peer "failover";
		}
	}
}

**(BUG | ISSUE) Actual Behavior:**

===========================================================================
/etc/dhcp/dhcpd.conf:
===========================================================================
# This file was built using fmDHCP 0.3.1 on Sun, 16 Dec 2018 09:49:30 +0100 Europe/Berlin

## peer items ##
failover peer "failover" {
	secondary;
	peer-address dhcp2.local;
	peer-port 847;
	address dhcp1.local;
	port 647;
	max-response-delay 30;
	max-unacked-updates 10;
}

## shared items ##
shared-network 10.10.0.0 {
	authoritative;

	subnet 10.10.0.0 netmask 255.255.255.0 {
		authoritative;

		pool {
			range 10.10.0.10 10.10.0.20;
			failover peer "failover";
		}
	}
}

**(BUG | ISSUE) Steps to reproduce:**
Create a dhcp failover peer

{This is related to BUG #421 . First of all i want to say thanks for fixing this.
In ticket #421 you already fixed a part of the dhcp peer declaration (peer port and peer address).
This now works for the primary dhcp server. Unfortunately the secondary dhcp failover peer members config gets created with the wrong config parameters}

**Comment by WillyXJ** [comment]
Sorry that was missed from the first request.  This is now fixed in [fmDHCP 0.3.2](http://www.facilemanager.com/modules/fmdhcp/) and later.
