### ISSUE TITLE
[BUG] fmDHCP + Raspberry Pi

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#426]
Please prefix your issue title with one of the following: [BUG]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.3**
{Module Name} Version : **0.3.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

ISC DHCP on Raspberry Pi should reload when building config.

**(BUG | ISSUE) Actual Behavior:**
Config Build fails.

**(BUG | ISSUE) Steps to reproduce:**
Build Config on RPi dhcp server

I found out, that the config build on Raspberry Pi fails.
The config file gets written, but the reload fails.

I think this is due to the osversion parameter which is checked by the clients functions.php

I could fix this by adding this line to the clients functions.php file:

 **'Raspbian'  => array(findProgram('service') . ' isc-dhcp-server restart', findProgram('systemctl') . ' restart isc-dhcp-server.service'),**

Maybe this could be included in future versions, or you find a better way to fix it  :)

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.4](http://www.facilemanager.com/modules/fmdhcp/) and later.
