### ISSUE TITLE
[BUG] fmDNS Editor works differently in Global Options and view Options

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#429]
fM Version : **3.1.1**
{fmDNS} Version : **3.1.2**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When I add options, I expexted the same editor to work in Global Options and view Options.

**(BUG | ISSUE) Actual Behavior:**
The editor in Global Options and view Options has different rules.

**(BUG | ISSUE) Steps to reproduce:**
In Global Options I can add:
allow-update key "dnsupdater";
When view Options I get only:
allow-update key;

Also in view Options I can not do
view "internal" {
 match-clients { !key external; 10.0.1/24; };
}
I receive only
view "internal" {
 match-clients { !key; 10.0.1/24; };
}

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3](http://www.facilemanager.com/modules/fmdns/) and later.
