### ISSUE TITLE
[BUG] Unable to filter zones list by groups since fmDNS 3.2.1

### ISSUE THREAD

**Issue by andrewhotlab** [WillyXJ/facileManager#430]
fM Version : **3.3**
fmDNS Version : **3.2.1**

**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**BUG Expected Behavior:**
Be able to filter zones list by using defined groups.

**BUG Actual Behavior:**
Groups have been defined, but when filtering the list, no result appears.

**BUG Steps to reproduce:**
Create a zone group, put in it a few zones, then try to filter the zone list.

I noticed this issue after updating to the latest fM/fmDNS releases.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by andrewhotlab** [comment]
Thanks very much: filtering is working again now!
