### ISSUE TITLE
FEATURE REQUEST Add support for install on Scientific Linux

### ISSUE THREAD

**Issue by fqberful** [WillyXJ/facileManager#431]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.3**
{Module Name} Version : Main module and fmDNS  

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

It would be great if support for installation on Scientific Linux boxes would be supported.  SL is a Redhat clone just like CENTOS, has an /etc/redhat-release  file that reads 

 Scientific Linux release x.xx (release-name)

**Comment by WillyXJ** [comment]
This is now implemented in [fM 3.4](http://www.facilemanager.com/download/) and later.
