### ISSUE TITLE
[BUG] ACL's are not displayed properly

### ISSUE THREAD

**Issue by wzglc6** [WillyXJ/facileManager#432]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.3**
fmDNS Version : **3.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
I create an ACL group with name test after that I add 2 ACL's with 192.168.1.2 and 10.100.1.4
The first ACL is getting displayed, all others not.

**(BUG | ISSUE) Actual Behavior:**
Provides a list of all ACL's

**(BUG | ISSUE) Steps to reproduce:**
I ran several installs from scratch and the acl's are not displayed at all.
I ran an update on an other instance (different server & db) and the ACL's are not being displayed.
I can not even edit the ACL anymore after creating it.

![screen shot 2019-03-04 at 20 43 58](https://user-images.githubusercontent.com/20779466/53777677-ce294e80-3ebf-11e9-9529-0f6603e69400.png)

**Comment by wzglc6** [comment]
Looks like the named.conf is getting created with the ACL's configs:

// acl group
acl "test" {
	192.168.1.2;
	10.100.1.2;
	10.100.1.4;

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3](http://www.facilemanager.com/modules/fmdns/) and later.
