### ISSUE TITLE
[FEATURE REQUEST] Add option 'server'

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#434]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.1.1**
fmDNS Version : **3.1.2**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
I want use option 'server' (http://ftp.isc.org/isc/bind/9.11.4/doc/arm/Bv9ARM.ch06.html#server_statement_grammar) in 'view' as in this example (https://kb.isc.org/docs/aa-00295):
```
view "internal" {
  match-clients { !key external; 10.0.1/24; };
  server 10.0.1.1 {
    /* Deliver notify messages to external view. */
    keys { external; };
  };
```

**(BUG | ISSUE) Actual Behavior:**
There is no 'server' when I add new options.

**Comment by WillyXJ** [comment]
Duplicate of #218.

**Comment by beza2000** [comment]
It is not duplicate.
I have 1 server with 2 views - "internal" & "external".
According to the manual (http://ftp.isc.org/isc/bind/9.11.4/doc/arm/Bv9ARM.ch06.html#server_statement_grammar), when I change some in "internal" view, I transfer zone and the key in "external" view on the same server.
```
view "internal" {
  match-clients { !key external; 10.0.1/24; };
  server 10.0.1.1 {
    /* Deliver notify messages to external view. */
    keys { external; };
  };
 zone "example.com" {
    type master;
    file "internal/example.db";
    allow-update { key mykey; };
    also-notify { 10.0.1.1; };
  };
};
...
view "external" {
  match-clients { key external; any; };
  zone "example.com" {
    type slave;
    file "external/example.db";
    masters { 10.0.1.1; };
    transfer-source { 10.0.1.1; };
  };
};
```
There are several servers in #218 and they have different IP. The suggested option #218 doesn't work in my case.

**Comment by WillyXJ** [comment]
I'm sorry, I did not catch that you were wanting to transfer the zone between views.  In fact, I did not know that was an option in BIND.  I've reopened this and will figure out how to support that use case.

**Comment by WillyXJ** [comment]
@beza2000 - Are you able to define the key you want to use in the "internal" view, create the 10.0.1.1 remote server and associate it with the previously defined key, and then define the masters and transfer-source options for your example.com zone in the "external" view?  I believe that would accomplish what you are asking for.

**Comment by beza2000** [comment]
No. This is a low priority for me, and I don't have  free time now.

**Comment by beza2000** [comment]
I found a solution. We need to use: also-notify {10.0.1.1 key "external"; ...}
Example:
```
view "internal" {
  match-clients { !key "external"; 10.0.1/24; };
  
 zone "example.com" {
    type master;
    file "internal/example.db";
    allow-update { key mykey; };
    also-notify {10.0.1.1 key "external"; ...}
  };
};
...
view "external" {
  match-clients { key external; any; };
  zone "example.com" {
    type slave;
    file "external/example.db";
    masters { 10.0.1.1; };
  };
};
```
