### ISSUE TITLE
[ISSUE] SOA record not created

### ISSUE THREAD

**Issue by torrycrass** [WillyXJ/facileManager#435]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4**
{DNS} Version : **3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When creating an SOA record via the web interface it shows the validate screen and then should save the record and display the SOA record if validation succeeded.

AND

Creation of the SOA template should also save a template of the SOA record being worked on.

**(BUG | ISSUE) Actual Behavior:**
SOA record is filled out, validation screen is shown, but the record is not saved.

AND

When performing the same function to create an SOA template no SOA entry is saved either.

**(BUG | ISSUE) Steps to reproduce:**
Log into web portal fm 3.4 / fmdns 3.3, open a forward zone file, it will state that an SOA record needs to be created. Fill in the requested data. Click on validate. Click on submit. Notice no record created.

The system appears to have a problem with SOA records. Attempting to use them in any way seems to fail out. I am using the SSH method of updating records (which was mentioned as a possible fix quite a while ago) but that does not appear to be helping. I can create A and NS records, import zone files as well but even on zone import the SOA record is not created.

Am I missing something that I would need to enable SOA to function properly? Thank you!

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3.1](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by chandro** [comment]
Hello, i have versions:

facileManager v3.5.7
fmDNS v3.4.1

and SOA is not being added to the zones, even if template is there, from all my  "localhost" is the only one with the SOA records, i am missing something?

**Comment by WillyXJ** [comment]
@chandro what steps can I take to reproduce this? I have tried the following which were successful:

1. Create a zone and specify a SOA template, click Save
2. Create a zone and specify a custom template, click Save. Then fill out the SOA form and save it.

After creating an NS record for the zone, I'm able to preview it and the SOA shows.

**Comment by chandro** [comment]
Hello WillyXJ, i had already the list of zones, when i do a backup from TOOLS, it seems it deletes all options and advanced options from each zone. 

now all the zones doesnt have any SOA record, even when the SOA template is there. so i need to delete and add each zone again to have the SOA??

**Comment by WillyXJ** [comment]
@chandro It sounds like this a different issue not related to the original issue reported by torrycrass.  It sounds like it's related to the backup functionality and maybe how you've restored it.  Please open a new issue for this and definitely include complete steps to reproduce the problem.  Thanks!
