### ISSUE TITLE
[Issue] Cannot install client 

### ISSUE THREAD

**Issue by yochaigal** [WillyXJ/facileManager#438]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.1**
{Module Name} Version : **3.3.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
php /usr/local/facileManager/fmDNS/client.php install should not result in an error. 

**(BUG | ISSUE) Actual Behavior:**
When running php /usr/local/facileManager/fmDNS/client.php install, I am prompted for the URL; it asks to generate a serial, and then I get:

Database error: [Field 'server_key' doesn't have a default value | Query: [REPLACE INTO `fm_dns_servers` (server_name, server_type, server_run_as_predefined, server_run_as, server_update_method, server_update_port, server_config_file, server_root_dir, server_chroot_dir, server_zones_dir, server_serial_no, account_id) VALUES ('servername.serverhost.com', 'bind9', 'bind', '', 'http', '80', '/etc/named.conf', '/var/named', '', '/etc/named/zones', '242540570', '1')]]

Ubuntu Server 18.04; BIND, MySQL, PHP and Apache are all installed. I have provided the dedicated db user with access to the facileManager database; the webUI works fine, except I cannot add servers to fmDNS there, or from the command line. Nor can I find more logging as to what is actually going on (mysql shows nothing). Debug option does not show anything different. 

What am I missing? 
Thanks!

**Comment by WillyXJ** [comment]
Hi,

It looks like this is from a new server installation of fmDNS v3.3.0-3.3.2 as the installer added a table field that is no longer required.  You can either wait until v3.3.3 or you can run this manually against your database to resolve the issue:

```
ALTER TABLE `fm_dns_servers` DROP `server_key`;
```

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3.3](http://www.facilemanager.com/modules/fmdns/) and later.
