### ISSUE TITLE
[FEATURE REQUEST] FMDNS add DANE RFC 6698 support

### ISSUE THREAD

**Issue by dre-** [WillyXJ/facileManager#439]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **v3.4.1**
{Module Name} Version : **fmDNS v3.3.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

Would like to use DANE RR's (TLSA and OPENPGPKEY) but they're missing in fmDNS v3.3.2.

**Comment by WillyXJ** [comment]
RFCs to reference when adding the RR support:
https://tools.ietf.org/html/rfc6698
https://tools.ietf.org/html/rfc7929

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.
