### ISSUE TITLE
Typo in install fmDNS

### ISSUE THREAD

**Issue by karambol** [WillyXJ/facileManager#440]
there is a missing semicolon on the end of
https://github.com/WillyXJ/facileManager/blob/7ebe57b32f8b08ece39ed554e80bbc50bcb1f858/server/fm-modules/fmDNS/install.php#L49

**Comment by WillyXJ** [comment]
Thanks for the report and it's embarrassing it missed my tests.  Since this is only for the installer, I've made the change and repackaged fmDNS v3.3.3 and facileManager-complete v3.4.1 without a version bump.
