### ISSUE TITLE
[ISSUE] Images for options fail to display in offline installation

### ISSUE THREAD

**Issue by torrycrass** [WillyXJ/facileManager#441]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.1**
{Module Name} Version : **fmDNS 3.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Options and images are displayed whether connected to the internet directly or in use in a non-internet connected (LAN) environment.

**(BUG | ISSUE) Actual Behavior:**
When using facileManager in an offline capacity graphic images for the **Actions** area and **Domain** area do not display making it difficult to use proper options in the platform when the system is not connected to the internet. These are two examples but this occurs in any menu that uses the same display mechanism.

**(BUG | ISSUE) Steps to reproduce:**
Install facileManager and desired modules while connected to the internet, then disconnect from the internet and refresh the page.

A workaround may be to download (and host/redirect to local) the missing objects. I do have this ability in the environment but have not yet found the specific code pulling these graphics into the system.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 3.4.2](http://www.facilemanager.com/download/) and later.
