### ISSUE TITLE
[ISSUE]Failed to write out "forwarders{ };" in the "zone.conf" files

### ISSUE THREAD

**Issue by ReiAyaya** [WillyXJ/facileManager#443]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.1**
{Module Name} Version : **fmDNS 3.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When specified no forwarder in the zones section, "zone.conf" files write out "forwarders{ };" code.

**(BUG | ISSUE) Actual Behavior:**
When setting Zones Options, failed to write out empty forwarders as "forwarders{ };" for "type master" in "zones.conf" files.

**(BUG | ISSUE) Steps to reproduce:**
Input an empty value in "Option Value" text box on "Add Option" dialog box.
But displayed disallowed message.
So tried to input like this comment "/*empty*/" instead empty value in "Option Value".
Although, can not write out it.

I already know # 299 and # 324, but I still looks like the same thing is happening.
Please check once.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.3.4](http://www.facilemanager.com/modules/fmdns/) and later.
