### ISSUE TITLE
[ISSUE]Failed to write out "forward only;" in the Zones Options "type forward"

### ISSUE THREAD

**Issue by ReiAyaya** [WillyXJ/facileManager#444]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.1**
{Module Name} Version : **fmDNS 3.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When setting "type forward" on the Zones Options, can select "forward only / first" and forwarders IP address.
And "zones.conf" files write out selected options.

**(BUG | ISSUE) Actual Behavior:**
When setting Zones Options, success to register "forward only;" on the WebUI.
But failed to write out to "zones.conf" files.

Also, failed to display define forwarders when editing it.

**(BUG | ISSUE) Steps to reproduce:**
When select Zone Map "forward" on the Zones Options, it can choice "first" or "only" and input define forwarders on the WebUI.
And display "Edit Zone" window and check "zone.conf" files.

**Comment by WillyXJ** [comment]
Hi. I'm unable to reproduce this issue.  Is the DNS server you are expecting the forward to be configured on defined as one of the DNS servers the zone is configured for within the UI? (Edit the zone and see what's in the "DNS Servers" section.)

**Comment by ReiAyaya** [comment]
Thank you for your reply.
I have multiple DNS Servers, but now I am using to only one DNS Server for trial test.
So does it occur this issue?
If I use "forward only;",  dose it mean that I need to define DNS server expecting the forward in the UI?

**Comment by WillyXJ** [comment]
When adding or editing a zone, the "DNS Servers" field is used to define which of your BIND servers the zone will be configured on. By default (and if you leave the field blank), the zone will be configured on all of your servers.

**Comment by ReiAyaya** [comment]
Hi, WillyXJ.
Thank you for your advice comment.

I tried to this method, and success to write out "forward only;" and forwarders IP Addresses.
I understood this method(specification) that is necessary to register all managed DNS Servers to fmDNS when using forward only feature.

But I am in control one of DNS Servers, and the other DNS Servers are managed by other administrators.
So it is difficult to install fmDNS client to all DNS Servers.

Finally, I would like to switch from "ISSUE" to "feature request".
Could you add to feature that manage forwarder DNS Servers without fmDNS?

Kind regards, Rei

**Comment by WillyXJ** [comment]
Hi Rei,

fmDNS can only manage the DNS servers with the client installed.  So, if you need the servers other administrators maintain to define a zone that forwards to your DNS server then those administrators will need to create the zone definition.

**Comment by ReiAyaya** [comment]
Hi, WillyXJ

Thank you for reply and some advices.
I close this ticket.

Regards, Rei
