### ISSUE TITLE
[BUG]  Сan't remove a variable from Masters

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#447]
fM Version : **3.4**
{fmDNS} Version : **3.3.1**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When I delete a variable in Config/Masters, it must be deleted.

**(BUG | ISSUE) Actual Behavior:**
![image](https://user-images.githubusercontent.com/5364251/58636909-02af7980-82fa-11e9-9082-ff98e0e4242e.png)

**(BUG | ISSUE) Steps to reproduce:**
1. Create a variable in Config/Masters.
2. Delete this variable in Config/Masters.

**Comment by WillyXJ** [comment]
Confirmed bug when no address lists are associated with the clause.  A workaround is to either disable the entry, or create an address list first and then delete the entire master clause.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.
