### ISSUE TITLE
[BUG] Dynamic reverse zone dump error file

### ISSUE THREAD

**Issue by fruza** [WillyXJ/facileManager#449]
fM Version : **3.4.2**
fmDNS Version : **3.3.4**

Hi!,

I've configured a reverse zone to support dynamic updates. Every time I try to enter to it to edit the records I get the typical error with the possible causes. Looking at the logs I see that it's trying to execute the following command:

`Jun  7 12:13:49 dnstomaster sshd[1185]: pam_unix(sshd:session): session opened for user fmuser by (uid=0)
Jun  7 12:13:50 dnstomaster sudo:  fmuser : TTY=unknown ; PWD=/home/fmuser ; USER=root ; COMMAND=/bin/php /usr/local/facileManager/fmDNS/client.php dump-zone -D 100.168.192.in-addr.arpa -f /var/named/chroot/etc/named/zones/master/db.100.168.192.in-addr.arpa.hosts
`

I think the **-f** parameter is wrong here. For reverse zones the files are ending in **.rev** instead of **.hosts**, right?

`[root@dnstomaster master]# ls -l /var/named/chroot/etc/named/zones/master/db.100.168.192.in-addr.arpa.hosts
ls: no se puede acceder a /var/named/chroot/etc/named/zones/master/db.100.168.192.in-addr.arpa.hosts: No existe el fichero o el directorio
[root@dnstomaster master]# ls -l /var/named/chroot/etc/named/zones/master/db.100.168.192.in-addr.arpa.rev 
-rw-r--r-- 1 named named 921 jun  7 12:10 /var/named/chroot/etc/named/zones/master/db.100.168.192.in-addr.arpa.rev
`

Best regards, Fernando.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.
