### ISSUE TITLE
[ISSUE] ERROR: Could not connect to MySQL. Please check your credentials.; Undefined variable: __FM_CONFIG

### ISSUE THREAD

**Issue by Dofamin** [WillyXJ/facileManager#452]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.2**
Centos-release: **7-6.1810.2.el7.centos.x86_64**
Kernel: **Linux 3.10.0-957.el7.x86_64**

**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Establishing a connection with mySQL (mariaDB)

**(BUG | ISSUE) Actual Behavior:**
ERROR: Could not connect to MySQL.
Please check your credentials.

Log from Apache
```shell
[Wed Aug 07 01:01:25.175590 2019] [:error] [pid 34604] [client 192.168.0.100:60371] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 278, referer: http://192.168.0.254/fm-install.php?step=2
[Wed Aug 07 01:01:25.175659 2019] [:error] [pid 34604] [client 192.168.0.100:60371] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 282, referer: http://192.168.0.254/fm-install.php?step=2
[Wed Aug 07 01:01:25.175680 2019] [:error] [pid 34604] [client 192.168.0.100:60371] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 286, referer: http://192.168.0.254/fm-install.php?step=2
[Wed Aug 07 01:01:25.192783 2019] [:error] [pid 34606] [client 192.168.0.100:60372] PHP Notice:  Undefined index: basename in /var/www/html/server/index.php on line 44, referer: http://192.168.0.254/fm-install.php?step=2
```

**(BUG | ISSUE) Steps to reproduce:**
```shell
yum -y update && yum -y upgrade
yum -y install cockpit
systemctl start cockpit
systemctl enable cockpit
firewall-cmd --permanent --zone=public --remove-service=ssh
firewall-cmd --permanent --zone=public --remove-service=dhcpv6-client
firewall-cmd --permanent --zone=work --remove-service=dhcpv6-client
firewall-cmd --permanent --zone=work --add-service=cockpit
firewall-cmd --permanent --zone=work --add-service=ssh
firewall-cmd --permanent --zone=work --add-service=http
firewall-cmd --permanent --zone=work --add-service=https
firewall-cmd --permanent --zone=work --add-source=192.168.0.0/24
firewall-cmd --reload
yum -y install cockpit-doc.x86_64 cockpit-packagekit.x86_64 cockpit-pcp.x86_64 cockpit-storaged.noarch net-tools nano yum-cron wget epel-release traceroute nmap dnsmasq lsof git 
cp /etc/yum/yum-cron.conf /etc/yum/yum-cron.conf.bak
sed -i -e 's/apply_updates = no/apply_updates = yes/g' /etc/yum/yum-cron.conf
systemctl start yum-cron
systemctl enable yum-cron
echo "clean_requirements_on_remove=1" >> /etc/yum.conf
echo "192.168.0.254 SRV-DNS SRV-DNS.localdomain" >> /etc/hosts
yum -y install net-tools nano yum-cron wget epel-release traceroute nmap dnsmasq bind bind-utils bind-devel bind-libs
yum -y install httpd
systemctl enable httpd
systemctl start httpd
sed -i -e 's/    DirectoryIndex index.html/    DirectoryIndex index.html index.php/g' /etc/httpd/conf/httpd.conf
cat <<EOF | sudo tee /etc/httpd/conf.d/dnsadmin.conf
Alias / /var/www/html/server/

<Directory /var/www/html/server/>

 Options FollowSymLinks
 AllowOverride All

# For Apache = 2.3:
# Order allow,deny
# allow from all

 # For Apache = 2.4
  Require all granted
</Directory>

EOF
setsebool -P httpd_can_network_connect 1
cd /opt
wget http://facilemanager.com/download/facilemanager-complete-3.4.2.tar.gz
tar -zxvf facilemanager-complete-3.4.2.tar.gz
cp -r /opt/facileManager/server/ /var/www/html/
rm -rf /opt/*
chown apache -R /var/www/html/
chmod 755 -R /var/www/html/
yum -y install php php-posix php-mysqli php-mysql
service httpd restart
```

**Comment by WillyXJ** [comment]
This looks the same as #450.  Have you ensured your web server can successfully authenticate with the database server as shown in that issue?

**Comment by Dofamin** [comment]
You are completely right, it really looks like this problem, however I used the solution provided in that problem.
setsebool -P httpd_can_network_connect 1
And it did not help.
Connection failed: Can't connect to MySQL server on '192.168.0.251' (113)
I also tried different versions.

**Comment by WillyXJ** [comment]
The issue lies below facileManager as your web server cannot communicate with your database server.  Have you tried disabling SELinux and any firewalls to find out where the communication between the systems is denied at?

**Comment by Dofamin** [comment]
Yes, I tried with turned off firewalld and selinux.
The problem remains in place.

**Comment by Dofamin** [comment]
Sorry, I was wrong.
The error was on the side of srv-db.
Thanks for the help.
And excuse me.
ISSUE close.
