### ISSUE TITLE
[ISSUE], Creating DNSSEC keys seems like not able to complete

### ISSUE THREAD

**Issue by karimie** [WillyXJ/facileManager#453]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 3.4.2
fmDNS Version : 3.3.4

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**
We have install facileManager on Centos 7, php5, apache 2.4. So far we can see other functions is working correctly except for creating DNSSEC keys to sign zone. When we create DNSSEC keys from facileManager interface it seems like loading without ending. there is no keys being created. 

**(BUG | ISSUE) Steps to reproduce:**

is there any other things need to be installed? like php extension or else? please advise.

**Comment by WillyXJ** [comment]
Your facileManager server needs to have the dnssec-keygen utility installed, but if it's not found then you would have received a message stating as such.  The key generation process uses dnssec-keygen to create the keys in $tmp_dir/fmDNS_XXXXXXX and then loads the contents into the database for future reference.

I am currently unable to reproduce this issue as key generation is working fine in my test environment.

Please check two things for me:
1. Are there any key files in your configured temporary directory (configured in the Settings page)?
2. Are there any errors in your apache logs?

**Comment by karimie** [comment]
after checking on my server i can confirm that dnssec-keygen can be found in the OS. the tmp directory also available for write by the system. i can confirm this as i can see there are folders being generated inside the tmp folder. 

apart from that i can see below are the command FM will use to generate the key.

`/sbin/dnssec-keygen -K /tmp/fmDNS_20190809180441/ -a rsasha256 -b 2048 -n zone mydomain.com`

i have try to run this command from the command line and can see that the process to generate the key is very slow and not even able to generate the keys like waiting forever. However, after googling some suggestion point out to use /dev/urandom instead the default which is /dev/random. i rerun the command again by specifying /dev/urandom.

`/sbin/dnssec-keygen -r /dev/urandom -K /tmp/fmDNS_20190809180441/ -a rsasha256 -b 2048 -n zone mydomain.com`

i can see that generation process able to complete within seconds. i believe that might be the cause of why the interface cannot complete the keys process.

**Comment by karimie** [comment]
i have edited the code inside class_keys.php and add -r /dev/urandom in the command and manage to get the keys generation to complete within seconds.

**Comment by karimie** [comment]
Hi @WillyXJ,

Just to update you. issue has been resolved. there is no need to change the code. What i need to do is just install haveged and make sure it is started. Previously i have installed this but forgot to check if it is running or not.

yum install haveged
systemctl enable haveged
systemctl start haveged

**Comment by WillyXJ** [comment]
I'm glad you got it sorted.
