### ISSUE TITLE
[BUG] fmDNS issue with PHP 7.3 on Debian 10

### ISSUE THREAD

**Issue by jisse44** [WillyXJ/facileManager#454]
fM Version : **3.4.2**
fmDNS Version : **3.3.4**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When adding a new A record, zone file is generated by cron

**(BUG | ISSUE) Actual Behavior:**
A PHP fatal error occurs

**(BUG | ISSUE) Steps to reproduce:**
Add new A record, run cron:
`/usr/bin/php /usr/local/facileManager/fmDNS/client.php cron`

OS: Debian 9 upgraded to Debian 10
PHP version: PHP 7.3 (PHP 7.3.4-2 from Debian 10 packages)

Error:
`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function fm_module_buildconf::buildZoneFile(), 1 passed in /var/www/fm-modules/fmDNS/classes/class_buildconf.php on line 1020 and exactly 2 expected in /var/www/fm-modules/fmDNS/classes/class_buildconf.php:921\nStack trace:\n#0 /var/www/fm-modules/fmDNS/classes/class_buildconf.php(1020): fm_module_buildconf->buildZoneFile(Object(stdClass))\n#1 /var/www/fm-modules/shared/pages/buildconf.php(58): fm_module_buildconf->buildCronConfigs(Array)\n#2 /var/www/index.php(51): include('/var/www/fm-mod...')\n#3 {main}\n  thrown in /var/www/fm-modules/fmDNS/classes/class_buildconf.php on line 921`

**Comment by jisse44** [comment]
When I downgrade PHP to 7.0 (via PHP Sury packages), it works again

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.
