### ISSUE TITLE
[BUG] Unable to delete ACL

### ISSUE THREAD

**Issue by serjichacko** [WillyXJ/facileManager#458]
fM Version : 3.4.2
FmDNS Version : 3.3.4

Am new to the FmDNS , While testing FMDNS module in one of our test environment we are getting error for removing the ACL that created for test.
Please guide me if am wrong.

![image](https://user-images.githubusercontent.com/38320449/64530517-65170d80-d31e-11e9-801c-9c4a9208f552.png)

**Comment by WillyXJ** [comment]
Until a fix is released, you can delete ACLs by adding one entry to them (using the small + next to the name) and then delete the ACL as a workaround.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4](http://www.facilemanager.com/modules/fmdns/) and later.
