### ISSUE TITLE
[ISSUE] unable to reload zones configuration

### ISSUE THREAD

**Issue by serafin-tech** [WillyXJ/facileManager#459]
fM Version : **3.4.2**
fmDNS Version : **3.3.4**

after update of the zone I confirm reload and I expect the zone will be refreshed. It worked this way in version 2 but stopped after upgrade to 3.4.2
Client script are run from cron in my installation

domain_reload flag is being set to yes for domain and this flag got back to no after `client.php cron` being run.
server_update_config is set and remian =yes after `client.php cron` being run.

I see empty messages in fm.log:
Sep 09 21:40:01 fmDNS: No updates found.
Sep 09 21:45:01 fmDNS: 
Sep 09 21:47:01 fmDNS: 

building full configuration works perfectly well

any hints for debugging this issue appreciated

TIA
Ser@fin

**Comment by WillyXJ** [comment]
I'm currently unable to reproduce this issue in my latest development branch. When you confirm to reload a zone, does an entry appear in fm_dns_track_reloads containing the right domain_id and server_serial_no? If so, does the entry get removed after the client process runs?

**Comment by SerafinSahary** [comment]
On 9/10/19 4:56 PM, WillyXJ wrote:
> I'm currently unable to reproduce this issue in my latest development 
> branch. When you confirm to reload a zone, does an entry appear in 
> fm_dns_track_reloads containing the right domain_id and 
> server_serial_no? If so, does the entry get removed after the client 
> process runs?
> 


the entry in fm_dns_track_reloads is being created, domain id and server 
serial no match.

root@WWW06:~# /usr/bin/php7.3 /opt/facilemanager.client/fmDNS/client.php 
cron
root@WWW06:~# echo $?
1

command finishes with 1 error code, no error message is reported

could you suggest where is the function responsible for domain 
reloading? I can try to add some debug messages. Unfortuantelly, when I 
add -d it does not show any extra messages

Thanks for your help,
Ser@fin

**Comment by WillyXJ** [comment]
When the client runs, it will execute https://github.com/WillyXJ/facileManager/blob/master/server/fm-modules/fmDNS/classes/class_buildconf.php#L960 on the server.  I see your client is using PHP 7.3.  Have you tried using a lower version of PHP for both your client and fM server?

With the two flags you've mentioned in the original post, I'm not yet sure why you'd get "No updates found."

**Comment by SerafinSahary** [comment]
Hi,

"no updates found" would be easy to explain - when I build the config application cleans statuses and the system can't find any update to be processed.
But I noticed something else - when I removed all records from fm_dns_track_reloads and fm_dns_track_builds client script generated full configuration successfully, even though I reloaded only one domain from the database. Weird

maybe tomorrow I'll find some time for debigging, in the meantime let me test the scripts with php 7.1

Thanks,

**Comment by eagle1maledetto** [comment]
Hi,

Debian9, PHP7.3 and same error.

I've noticed this problem while editing the main template of the domain. After reloading the zones the new values are present only in the database but the zone files stay the same. I've triple checked everything was in place (and it was), this is why I'm here.

I'll try to downgrade to PHP7.1

**Comment by eagle1maledetto** [comment]
Tested with the default PHP7.0 shipped in Debian9, works as intended.

Now when I edit a template and reload the zone, the cron works fine and update the zone files correctly. 

Fun fact:
- With PHP7.3 and pending updates to reload or config to rebuild I had a button near the search - button. Very handy!
- With PHP7.0 this button does not appear. Me sad.

Thank you folks

**Comment by SerafinSahary** [comment]
in fact I'm on recent Ubuntu LTS.

on the host where web part is installed I have PHP 7.2 from Ubuntu repo 
only, and on the box where Bind is located I have PHP 7.1 & 7.3 from 
Ondriej repo only.

thanks for your effor in debugging

**Comment by WillyXJ** [comment]
Are all of these examples using the cron update method?  So far, I'm unable to reproduce any issues with PHP 7.4 on either the server or client side.

**Comment by SerafinSahary** [comment]
@WillyXJ,  I was using CRON as update method. I have moved the setup to the cloud hence no longer experience the issue. Unfortunately can't help more with debugging it

What I remember from the experiments way back I had an issue with hostname resolution. For the historical reasons I had different names of the servers in database than in /etc/hostname - maybe that's the hint?

Anyhow - great job with facileManager!

Thanks,
