### ISSUE TITLE
[BUG] Error occurs while installing 

### ISSUE THREAD

**Issue by wesoma** [WillyXJ/facileManager#460]
fM Version : **3.4.2**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- X[] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Installation works without error. I can continue with the database connection

**(BUG | ISSUE) Actual Behavior:**
Installation stops after entering the database details. Database connection has been tested, but fM states that it's not working. Error Log shows:
[Tue Sep 10 16:32:25.627047 2019] [:error] [pid 11056] [client 20.1.1.10:64230] PHP Fatal error:  Call to undefined function buildPopup() in /var/www/html/dnsadmin/fm-modules/facileManager/js/facileManager.php on line 1176, referer: http://10.30.90.102/dnsadmin/fm-install.php?step=2
[Tue Sep 10 16:32:25.696343 2019] [:error] [pid 11056] [client 20.1.1.10:64230] PHP Notice:  Undefined index: basename in /var/www/html/dnsadmin/index.php on line 45, referer: http://10.30.90.102/dnsadmin/fm-install.php?step=2

**(BUG | ISSUE) Steps to reproduce:**

**Comment by WillyXJ** [comment]
Did you test your database connectivity via the MySQL CLI client or a PHP method similar to the one posted in https://github.com/WillyXJ/facileManager/issues/450#issuecomment-515459218 ?

**Comment by wesoma** [comment]
Yes. And showed me successfully connected.

**Comment by WillyXJ** [comment]
What are the steps to reproduce this issue? Please include the software versions of your environment, too (i.e. OS, PHP, MySQL, etc.). Please be complete as possible. Thanks.

**Comment by WillyXJ** [comment]
Are you able to provide the steps to reproduce this issue?
