### ISSUE TITLE
[BUG] Invalid .htaccess Error On Install

### ISSUE THREAD

**Issue by Mr-Mors** [WillyXJ/facileManager#461]
fM Version : **3.4.2**
fmDNS Version : **3.4.2**

**In raising this bug, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

It looks like issue 335 contained this report, but it was added after the bug was closed and was probably never noticed.

**Expected Behavior:**
When missing a proper host name, error should not point you at .htaccess

**Actual Behavior:**
After reaching page 6 of install I am presented a "Requirement Error" page. This does not indicate an issue with /etc/hosts, but with Apache.

**Steps to reproduce:**
With a fresh install if you the contents of **$_SERVER['SERVER_NAME']** is not in your /etc/hosts file you will receive the following error:

```
The required .htaccess file appears to not work with your Apache configuration which is required by facileManager. AllowOverride None in your configuration may be blocking the use of .htaccess.
```

I stumbled upon this issue when trying to setup the server in a Docker environment. Adding the Docker hosts name to /etc/hosts resolved the issue and allowed the installation to continue.

I feel this error could be updated to check for an entry in /etc/hosts, and if it does not exist give an error more fitting of said issue. I spent a few hours today tracing down .htaccess and Apache issues when the true issue was as simple as a hostname.

**Comment by WillyXJ** [comment]
This is now implemented in [fM 3.5](http://www.facilemanager.com/download/) and later.
