### ISSUE TITLE
[BUG] Adding multiple "clients" in fmDNS overrides previous clients leaving only 1 client active

### ISSUE THREAD

**Issue by thorsig** [WillyXJ/facileManager#463]
fM Version : **3.4.2**
fmDNS Version : **3.3.4**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
On DNS server no 1, running "php /usr/local/facileManager/fmDNS/client.php install" should install the first client and register the DNS server in facileManager. One DNS server is registered.
On DNS server no 2, running "php /usr/local/facileManager/fmDNS/client.php install" should install the second client and register the DNS server in facileManager. Two DNS servers are registered.

**(BUG | ISSUE) Actual Behavior:**
On DNS server no 1, running "php /usr/local/facileManager/fmDNS/client.php install" installs the first client and register the DNS server in facileManager. One DNS server is registered. "Config -> Servers" shows exactly ONE server registered - server no 1.
On DNS server no 2, running "php /usr/local/facileManager/fmDNS/client.php install" installs the second client and register the DNS server in facileManager. It overrides the first installation so now, only one server is still registered. "Config -> Servers" still shows exactly only ONE server registered, but now it's server no 2.
Repeating the install for no 1 means that the web interface now only shows server no 1 registered.
Repeat ad nauseum.

**(BUG | ISSUE) Steps to reproduce:**
Have a working installation of the web interface, create two fresh machines (eg. "lxc launch ubuntu:18.04 machine1 .. ), log into the machines, apt install php7.2 bind9 bind9utils, scp -r user@somegoodserver:/usr/local/facileManager /usr/local/facileManager and php /usr/local/facileManager/fmDNS/client.php install, repeat for machine2. after each completion, verify which nameserver is created/active in the web config. Observe that they will no coexist.

**Comment by WillyXJ** [comment]
In your scp command, are you copying /usr/local/facileManager/config.inc.php from one client to another?  That file contains the unique server serial number for the client and if you use the same number, your second client will overwrite the entry for the first.

**Comment by thorsig** [comment]
Feel free to visualize me doing a massive <facepalm/>.

Of course that was the problem :)

þri., 24. sep. 2019 kl. 01:20 skrifaði WillyXJ <notifications@github.com>:

**Comment by WillyXJ** [comment]
Nice! Glad it's resolved.
