### ISSUE TITLE
[ISSUE]  Missing database tables 

### ISSUE THREAD

**Issue by Dragnell87** [WillyXJ/facileManager#464]
fM Version : **3.4.2**
{fmDNS} Version : **3.3.4**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Sorting (rearrenge views) after creation

**(BUG | ISSUE) Actual Behavior:**
Sorting (rearrange views) after creation complain of a missing table in the database

**(BUG | ISSUE) Steps to reproduce:**
Create 2 views, try to change they order.
![Captura de pantalla de 2019-10-02 11-43-13](https://user-images.githubusercontent.com/8634449/66061177-ed976100-e50c-11e9-9d40-6dd7cdc298ab.png)

Using Centos 7 and php7.0, was using php7.2 until i stumble into the issue in #459

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4.1](http://www.facilemanager.com/modules/fmdns/) and later.
