### ISSUE TITLE
[BUG][ISSUE] Missing definitions for variables and properties

### ISSUE THREAD

**Issue by Dragnell87** [WillyXJ/facileManager#465]
fM Version : *3.4.2**
{fmDNS} Version : **3.3.4**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x]x I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Setting a master dns

**(BUG | ISSUE) Actual Behavior:**
Complaining about missing definitions for variables and properties

**(BUG | ISSUE) Steps to reproduce:**
Defining a master and rebuild the configurations of the servers.

![Captura de pantalla de 2019-09-23 20-56-06](https://user-images.githubusercontent.com/8634449/66061602-c9884f80-e50d-11e9-99c3-c130529198b9.png)

Using Centos 7 and php7.0, was using php7.2 until i stumble into  the issue in #459

**Comment by WillyXJ** [comment]
@Dragnell87 - I'm having a hard time reproducing this issue.  Would you please provide more information on your masters that you've defined?  Are they all "global" masters or server specific masters?  Are you specifying any ports?  Etc.  The more information the better to help me reproduce the issue.

**Comment by Dragnell87** [comment]
Thank for your time, the master was created under All Server, port 53 no DSCP. Right now i can't  delete the setting.
![Captura de pantalla de 2019-10-02 14-15-18](https://user-images.githubusercontent.com/8634449/66070335-1c1e3780-e51f-11e9-98b7-73135d3207b1.png)

**Comment by WillyXJ** [comment]
While you've reported this under fmDNS 3.3.4, I'm not able to reproduce it with v3.4.  The updated version also includes a fix for deleting the masters (#447).  I recommend you upgrade and then let me know if the issue remains in your environment or not. Thanks.

**Comment by Dragnell87** [comment]
Right, after update i was able to delete the setting for the master. I Will update later if i can create master setting as intended. Thanks for your  time

**Comment by WillyXJ** [comment]
Did v3.4 resolve this issue?
