### ISSUE TITLE
[BUG] database update loop after upgrade from 3.4 to 3.5

### ISSUE THREAD

**Issue by thorsig** [WillyXJ/facileManager#466]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG) Expected Behavior:**
facileManager downloads and installs the core, logs me off and offers to update on next login. Update finishes and I have an updated and functional system.

**(BUG) Actual Behavior:**
facileManager downloads and installs the core, logs me off and offers to update on next login. Update doesn't finish - instead the login prompt appears again, no errors are logged to the Apache logfiles and the database stays at the same version as before - version 47.

**(BUG | ISSUE) Steps to reproduce:**
Install facileManager 3.4, have only fmDNS active and allow facileManager to automagically update itself.

**Comment by WillyXJ** [comment]
To clarify, after you login and click upgrade, you're back to the login screen without seeing the upgrade status?

What's your web server environment?

**Comment by thorsig** [comment]
Correct - I get the login screen, db is still at 47 and next step from login is repeat.
![image](https://user-images.githubusercontent.com/7996651/66374829-64b07780-e99b-11e9-8053-671858aef8d2.png)

![image](https://user-images.githubusercontent.com/7996651/66374854-742fc080-e99b-11e9-916b-f1c71f924b2c.png)

Briefly appears "Processing, please wait" and then back to step 1.

My webserver is a Apache virtualHost on a Ubuntu 18.04 LTS ( the server serves other webs as well, fm got its own directory tree and all files belong to the webserver user).

**Comment by WillyXJ** [comment]
What version of Apache and PHP?

**Comment by thorsig** [comment]
root@cursus:~# php -version
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
root@cursus:~# apache2ctl -version
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-08-26T13:41:23

**Comment by WillyXJ** [comment]
Something isn't right with your screenshots.  They are missing the logo image - are you able to figure out why those are missing?  I'm wondering if there's something wrong with you apache vhost.

**Comment by thorsig** [comment]
Okay, that actually did the trick. No problem with the vhost itself, everything was installed under /var/www/fm, the directory directive pointed to /var/www/fm and the location to /. However, the installation expected to find everything under /fm (so /var/www/fm/fm/...) - solved by "cd /var/www/fm ; ln -s . fm"

And that fixed both the branding AND the upgrade.

Thanks.
