### ISSUE TITLE
[ISSUE] fmDNS not writing zones via ssh 

### ISSUE THREAD

**Issue by ChristianGaetcke** [WillyXJ/facileManager#467]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5**
{Module Name} Version : **fmDNS 3.4**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:*Zones will be passed to ssh-managed servers with client*

**(BUG | ISSUE) Actual Behavior:*only main server with facileManager get's new zone entries*

**(BUG | ISSUE) Steps to reproduce:*Debian 9.7, php 7.0.33, facileManager 3.5  => facileManager host with mariaDB. => creating additional forward Zones and writing config to host (dns1) and client (dns2) => changes show up on host but not on client*

Hi,
**please insert praise and the usual apology of a non-natural speaker in here** 
I went through the issues and maybe I am overreading or misunderstanding something, but in the above mentioned configuration I don't seem to be able to add the zones to the client server. According to admin=>test connections everything is fine and even the named.conf(local and options)-files are written properly, but somehow in /etc/bind/zones/master only the db.localhost, db.0.0.127 and the db....ip6 show up.

Could you advise? Everything else seems to work nice (besides updating dns1 and dns2 configurations simultaneously, but this could be something else)

Thank you in advance, Christian

**Comment by WillyXJ** [comment]
Hi Christian,

After you create the zones and records within the UI you need to build the configuration on the dns servers (clients).  This is done by either clicking in the "Process All Updates" button in the top title bar, going to Config -> Servers and clicking the "Build Config" button for each client, or going to Config -> Servers and ticking each box next to the clients and selecting "Build Config" from the drop down menu.

Have you done any of those?  If so and no errors are reported, you can also try running the following on the client via CLI to see if there are errors or unexpected output:

`sudo php /usr/local/facileManager/fmDNS/client.php -b -d`

**Comment by ChristianGaetcke** [comment]
Hi Willy,
Unfortunately (or better fortunately), all 3 GUI updates and the command seem to run properly (as I can see zones.conf.external, zones.conf.internal and db.localhost.hosts are being propagated to dns2 from  /etc/bind/zones/master/).
What doesn't work is the propagation of additional created zones e.g. db.domain.tld.hosts. If I compare /etc/bind/zones/master/ on both servers, the dns1 has the db.domain.tld.hosts-files, whereas the dns2 doesn't . Already checked if the connection from dns2 to dns1 is allowed, but that seems fine.

Thank you for your help

**Comment by WillyXJ** [comment]
Would you please verify what you have for "DNS Servers" configured for domain.tld? It sounds like you may only have dns1 selected.

**Comment by ChristianGaetcke** [comment]
arghs, you are so right. Will try it as soon as I am home. Brain was afk in this case. Apologies for bothering you.

Best, Christian
