### ISSUE TITLE
[BUG] Zonefiles of Views are written to the wrong filename

### ISSUE THREAD

**Issue by Inanias** [WillyXJ/facileManager#468]
fM Version : **3.5**
fmDNS Version : **3.4**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**Expected Behavior:**
After creating/updating dns records inside a zone with multiple views, zonefile at /etc/bind/zones/master/db.domain.tld.489.hosts is updated.

**Actual Behavior:**
New zonefile /etc/bind/zones/master/db.domain.tld489..hosts is created with updated content and therefore change is not active.

**Steps to reproduce:**
Create or update record in a zone with multiple views and reload zones.

If the zonefiles are deleted and created by Config -> Servers -> Build Config everything is fine.

I tried a client reinstall with `php /usr/local/facileManager/fmDNS/client.php reinstall`, which executed without errors, but did not fix this.

This started happening after the recent update to fM 3.5 and fmDNS 3.4.

**Comment by WillyXJ** [comment]
This is a result of adding #456 as a feature. I'll have a fix for the next release.

**Comment by Inanias** [comment]
Thanks for the quick response and fix.

I can confirm that the fix works.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 3.4.1](http://www.facilemanager.com/modules/fmdns/) and later.
