### ISSUE TITLE
[BUG] Cannot use passwords including quotes

### ISSUE THREAD

**Issue by edvalley** [WillyXJ/facileManager#469]
fM Version : **v3.5.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Normally use any character for a password

**(BUG | ISSUE) Actual Behavior:**
Cannot use quotes (single or double) for a password

**(BUG | ISSUE) Steps to reproduce:**
A) Simply try to create a user, use a password including quotes, after clicking 'Save', user is not created and an error says: 'Passwords do not match.'
B) Configure LDAP authentication, it only works if the password doesn't include quotes. (Hint: Quotes are backslash escaped before reaching LDAP server)

Thanks for the great job you're doing.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 3.5.2](http://www.facilemanager.com/download/) and later.
