### ISSUE TITLE
[BUG][ISSUE] Database password is not quoted/escaped when passed to mysqldump

### ISSUE THREAD

**Issue by edvalley** [WillyXJ/facileManager#470]
fM Version : 3.5.2

In raising this issue, I confirm the following:

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Everything works fine, but we cannot make database backups.

**(BUG | ISSUE) Expected Behavior:**
- Go to Admin/Tools and click 'Backup Database'. The 'Save File' dialog appears prompting for where to save the backup file on the local disk.

**(BUG | ISSUE) Actual Behavior:**
- Go to Admin/Tools and click 'Backup Database'. The web page turns completely blank and nothing else happens.

**(BUG | ISSUE) Steps to reproduce:**
- Install mysql using a root password which include for example a ')' symbol.
- Install facileManager the usual way.
- Confirm the system works the right way.
- Go to Admin/Tools and click 'Backup Database'
- The web page turns completely blank and nothing else happens

httpd error log contains the following lines:

`sh: -c: line 0: syntax error near unexpected token `)'`
`sh: -c: line 0: `/bin/mysqldump --opt -Q -h localhost -u fm -p........ facileManager > /tmp/facileManager_....-..-.._.........sql 2>/tmp/facileManager_....-..-.._.........err'`

I can confirm that quoting the password in `fm-modules/facileManager/classes/class_tools.php` solves the problem and the backup is successfully done. Of course, this way password can't include quotes.

Passing passwords on the command line is generally referred as a bad practice. I think it should be better to write the password to a temporary mysql configuration file with safe permissions/owner/group, direct mysqldump to use it, and then delete it. See --defaults-extra-file command line argument for mysql/mysqldump.

Thank you very much your great job.

**Comment by WillyXJ** [comment]
Thanks for the report and tip about --defaults-extra-file as I did not know about that option and never had liked passing the password with the command.

**Comment by edvalley** [comment]
> Thanks for the report and tip about --defaults-extra-file as I did not know about that option and never had liked passing the password with the command.

You're welcome.
Everything for good open-source software.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 3.5.3](http://www.facilemanager.com/download/) and later.
