### ISSUE TITLE
[BUG][ISSUE] Fatal error: Uncaught Error:

### ISSUE THREAD

**Issue by Dragnell87** [WillyXJ/facileManager#472]
fM Version : 3.5.5
{fmDNS} Version : 3.4.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Crating a ACL for a group of sever (master-slave) 

**(BUG | ISSUE) Actual Behavior:**
PHP Fatal error: Uncaught Error:  Crash ot he UI

**(BUG | ISSUE) Steps to reproduce:**
Create a Server Group for master slave, try to create a ACL for this group

{replace this line with your issue content}
![fmdns groupacl error](https://user-images.githubusercontent.com/8634449/72085451-54c66d80-32d3-11ea-99c1-d7896522960b.png)

Using Centos 7 and php7.0

**Comment by WillyXJ** [comment]
Thanks for the report. The ACL still gets created, but the associated servers don't get flagged to build their configs.

**Comment by Dragnell87** [comment]
> Thanks for the report. The ACL still gets created, but the associated servers don't get flagged to build their configs.

That is correct. Thanks you again for the fast response and effort.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 3.5.6](http://www.facilemanager.com/download/) and later.
