### ISSUE TITLE
[ISSUE] Zone configuration skipping a server

### ISSUE THREAD

**Issue by Dragnell87** [WillyXJ/facileManager#473]
fM Version : 3.5.6
{fmDNS} Version : 3.4.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Adding zone to a new server, configurations build task should reflect changes in the preview
**(BUG | ISSUE) Actual Behavior:**
Adding zone to a new server, configurations build task make not change for the server, but it ask for a update

**(BUG | ISSUE) Steps to reproduce:**
This is a tricky one, this only happen with one server, the soley difference is that it reside in a different network. Other than that same php version as other client 7.0, same bind version, same OS.

Firewall allow all acces over tcp and upd on all ports. no ICMP

Any help how to debug further is appreciated.

**Comment by WillyXJ** [comment]
If I understand the issue correctly, you've created a new zone, but it's not getting built on all of your DNS servers.

1. Is the DNS server in question one of the DNS servers listed in the zone configuration?
2. Does the same thing happen when performing a "bulk" build config on that server from Config -> Servers?
3. Does the same thing happen when building the config from the CLI on the DNS server?

**Comment by Dragnell87** [comment]
No, the zone  already exist, i am just adding a new server to the zone.

1 Yes,
2 Yes,
3 sudo php /usr/local/facileManager/fmDNS/client.php -b from the client ? Then yes.

**Comment by WillyXJ** [comment]
So far I'm unable to reproduce this issue.  The steps I took are as follows:

1. Ensure serverA and serverB exist
2. Ensure zone1 "DNS Servers" include only serverA
3. Add serverB to the "DNS Servers" list of zone1
4. Build Config for serverB

Have you tried removing serverB from your zone config and then adding it back?
