### ISSUE TITLE
[FEATURE REQUEST] Multiple MAC addresses

### ISSUE THREAD

**Issue by filith** [WillyXJ/facileManager#474]
fM Version : **3.5.6**
fmDHCP Version : **0.4.3**

I don't know if this is a bug or a feature ;)

When i try to migrate my current DHCP config i notice that fmDHCP does not allow multiple MAC addresses for a specific ip address in different host entries.

ISC DHCP server generally allows this. I need this for using the same ip address  as well as on the ethernet interface and the wireless interface.

As a solution, the check for multiple IPs or MACs maybe could be disabled on a specific host entry ?

**Comment by WillyXJ** [comment]
Interesting use case that was not originally thought about.  This should be able to be implemented.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.4.4](http://www.facilemanager.com/modules/fmdhcp/) and later.
