### ISSUE TITLE
[FEATURE REQUEST] noninteractive resign dnssec enabled zone

### ISSUE THREAD

**Issue by dre-** [WillyXJ/facileManager#476]
fM Version : 3.5.1
fMDNS Version : 3.4.1 

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

ISSUE Expected Behavior:
Automatically resign zone before expiration without "build configuration" interaction.

ISSUE Actual Behavior:
Zone is resigned as soon as the server's configuration is rebuilt.

ISSUE Steps to reproduce:
Wait for expiration of DNSSEC signed zone without rebuilding server configuration.

Trying to resign dnssec enabled zones without user interaction, but didn't find a solution.
Option1: use of auto-dnssec and inline-signing to let bind take care of zone-resigning results in a nonsigned zone configuration where no DNSKEY and no RRSIG exists. rndc sign "zone" IN authoritative-view gives no error but where would it find the zone's keyfiles?
Option2: use of dnssec-signzone fails even with -S because the keys are stored in the mysql table fm_dns_keys and not in a key-directory where bind would perform a search.

At this time (at least for me) I have no idea on how to get automatic zone resigning work without interaction of any user that clicks on "rebuild configuration". Please let me know if there is a solution or if it's a missing feature for which I could ask for implementation.

**Comment by WillyXJ** [comment]
I've turned this into a feature request.

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 4.0-beta1](http://www.facilemanager.com/modules/fmdns/?t=3) and later. Testing is requested. Final release will come out later.

**Comment by WillyXJ** [comment]
[fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) has been released.
