### ISSUE TITLE
[BUG] FmFirewall DB Update issue

### ISSUE THREAD

**Issue by hendrikb101** [WillyXJ/facileManager#477]
Please prefix your issue title with one of the following: [BUG].

fM Version : **3.5.6**
FMFirewall Version : **2.0.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Want to add objects (hosts and groups) add new > enter name and IP > click on add, nothing happens, not even error message in any logs.

**(BUG | ISSUE) Actual Behavior:**

I have a brand new install of FacileManager and FmFirewall, I actually have installed it twice to test, I can add servers to the manager to manage but can't add any objects, entry not going to DB at all, but I can create policy templates, so it's not a db issue.

**(BUG | ISSUE) Steps to reproduce:**

Well on my brand new reloaded server I go to objects > add object > enter name and IP > click add, nothing loaded. What version of PHP should I be using btw?, tried both 70 and 72.

Other than that this product is awsome, I use the DNS Manager as well and it works perfectly.

**Comment by WillyXJ** [comment]
Confirmed v2.0.0 introduced this bug.

**Comment by WillyXJ** [comment]
This is now fixed in [fmFirewall 2.0.2](http://www.facilemanager.com/modules/fmfirewall/) and later.
