### ISSUE TITLE
[BUG] Installation fails on creating super-admin account

### ISSUE THREAD

**Issue by kkostin** [WillyXJ/facileManager#478]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5.6**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Super-admin created and installation continues

**(BUG | ISSUE) Actual Behavior:**

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('SuperSecurePa55w0rd!'), 'test@test.tld', 'a:1:{s:13:"facileManager";a:1:{s:13:' at line 1 | Query: [INSERT INTO `dns`.fm_users (user_login, user_password, user_email, user_caps, user_ipaddr, user_status) VALUES('admin', password('SuperSecurePa55w0rd!'), 'test@test.tld', 'a:1:{s:13:"facileManager";a:1:{s:13:"do_everything";i:1;}}', '192.168.133.59', 'active')]

**(BUG | ISSUE) Steps to reproduce:**

Use mysql  Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)
Start installation in browser, get to 'Create super-admin' step

**Comment by WillyXJ** [comment]
This is now fixed in [fM 3.5.7](http://www.facilemanager.com/download/) and later.
