### ISSUE TITLE
[ISSUE] add mutilple clients problem

### ISSUE THREAD

**Issue by marksmansj** [WillyXJ/facileManager#483]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5.7**
{Module Name} Version : **fmDNS**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

{I have installed the management server  (192.168.0.10) and installed client1 (192.168.0.20) by run php /usr/local/facileManager/fmDNS/client.php install , then I found the client1 appears in named servers of management server  . then I want to install client2(192.168.0.30) by run php /usr/local/facileManager/fmDNS/client.php install , at last I found only client2 appears in name servers of management server , and client1 disappeared  . if I reinstall client1 and client2 disappeared . as if only one client can be used . I wonder why }

**Comment by WillyXJ** [comment]
Are you letting the installer automatically generate a serial number or are you entering one in?  If all clients are installed with the same serial number then you will experience the behavior you've described.

If you are not using the same serial number, please provide detailed steps to reproduce this issue.

**Comment by marksmansj** [comment]
I used the same serial number . solved the problem at last . thank you so much
