### ISSUE TITLE
[FEATURE REQUEST] Bulk add hosts to ACL

### ISSUE THREAD

**Issue by marksmansj** [WillyXJ/facileManager#484]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5.7*
{Module Name} Version : *fmDNS*

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

{Hello. If I want to add  1000 of ip addresses into the one of the acls 
such as :
acl "acl_hk" {
	192.168.1.1;
        192.168.2.1;
        192.168.3.1;
         .........
};

， How can I do it ?  thanks a lot }

**Comment by WillyXJ** [comment]
You will have to add them one at a time in the UI or directly add the records to the database via SQL.

**Comment by marksmansj** [comment]
Thank you so much. will you add this function in the UI in future's version ?

**Comment by WillyXJ** [comment]
I've changed this to a feature request.

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 4.0-beta1](http://www.facilemanager.com/modules/fmdns/?t=3) and later. Final release will come out later.

**Comment by WillyXJ** [comment]
[fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) has been released.
