### ISSUE TITLE
[FEATURE REQUEST] SSL encrypted connections to database

### ISSUE THREAD

**Issue by edvalley** [WillyXJ/facileManager#485]
Can you please add this feature?
I would like facileManager to use a client certificate and key for the SSL connection, and be able to use a CA certificate to validate the server certificate.
From this 7 years old stackoverflow answer (https://stackoverflow.com/a/13960720), it doesn't seem to be so hard to code. Forgive me if I'm wrong. Sadly I'm not a PHP programmer to submit a well tested and working PR.
Thanks a lot for this great open source software.

**Comment by WillyXJ** [comment]
This is has been implemented in [fM 4.0.0](http://www.facilemanager.com/download/) and later.  The installer now has additional fields to specify the certificate information and the config.sample.inc.php has configuration parameters to uncomment on existing installations.
