### ISSUE TITLE
[ISSUE] fmDNS buildconf not working (but zone reload ok)

### ISSUE THREAD

**Issue by c3h5o9n** [WillyXJ/facileManager#487]
fM Version : 3.5.7
fmDNS Version : **3.4.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- X[] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Config on client should build

**(BUG | ISSUE) Actual Behavior:**
Config does not build. Message "Processing config build ..." never stops until I refresh the page.
 However zone update and reload is working perfectly.

**(BUG | ISSUE) Steps to reproduce:**
Any change that needs a server config build does not work.

More detailed description:
Building server conf used to work. I use ssh client update.
I wanted to add a second bind DNS server: client install is OK, on server UI i can see the new DNS server. But when I try to make update for this server config does not build.
When I try to make some changes to the first bind DNS server the config does not build anymore. However zone update still works perfectly.
On server side when I make a change at server level and I try to make a preview the windows is blank.
It is as if there is no data created on server side after a change has been done ...
On client side:
- publickey ssh connection is OK
- sudo COMMAND=/usr/bin/php /usr/local/facileManager/fmDNS/client.php buildconf is OK
- curl -k -v "https://FMHOST/admin-accounts.php?verify" replies immediately with HTTP/1.1 200 OK
- php /usr/local/facileManager/fmDNS/client.php -b -d takes 1'30'' and does not show anything, nothing happens

Any help to diagnose would be appreciated.
Thanks.

**Comment by WillyXJ** [comment]
What version of PHP are you using?

**Comment by c3h5o9n** [comment]
For facileManager I'm using:
apache2 2.4.38-3+deb10u3
libapache2-mod-php7.3 7.3.14-1~deb10u1

On the same server I also do have:
nginx 1.10.3-1+deb9u2
php7.3-fpm 7.3.14-1~deb10u1

At first facileManager was setup with nginx but since I got the issue I switched to apache which is the way it is supposed to work. However same behaviour with both.

**Comment by WillyXJ** [comment]
There have been several reports with funky behavior when using PHP 7.3+.  Try downgrading as see if the problem persists.

**Comment by c3h5o9n** [comment]
OK, not easy to downgrade PHP on the server where it is installed.
I keep in in mind there are issues with 7.3+.
Thanks for your help.
