### ISSUE TITLE
Zone Records not being updated in the bind server

### ISSUE THREAD

**Issue by sidantaa** [WillyXJ/facileManager#490]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **X.X.X**
{Module Name} Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Zone Record is added and it is also reloaded.

**(BUG | ISSUE) Actual Behavior:**
I was trying to integrate bind with the GUI FMDNS; i am now in trouble...the FMDNS gui is not pushing  the data to the bind zones file from its database.. I cross checked the cron jobs and everything is fine there.. The zone records added from GUI is not being updated in the bind server's  
/etc/bind/zones/master/zones/db.abc.com.hosts. Everything was fine before; once i tried the option enforce ssl and here due to some reason i couldn't acess through https://.......  and hence i deleted the entry https in database so after that i am facing this issue.. Else i haven't done anything with the configuration. Everything seems fine ; records do get added successfully and then it is asked for reload and will popup the record will be added in next cron job. i do also saw cron job running in its actual time but the record is not being updated in the bind server's zone file. Anyone here who have already worked with FMDNS? Please help me. I have tried everything so i am here to ask for help. 

Here in some of the post; i found problem regarding php version. Do this create problems?

In my case the php version is:

**In FMDNS Server:**
PHP 7.0.33 (cli) (built: May 12 2020 08:41:35) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies

**In Bind installed server (ubuntu)**

PHP 7.4.3 (cli) (built: May  5 2020 12:14:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**(BUG | ISSUE) Steps to reproduce:**

{replace this line with your issue content}

**Comment by WillyXJ** [comment]
Hello. It’s likely an issue with PHP 7.4. The software is untested with that version. Try downgrading to 7.2 or under and see it that resolves the issue.

**Comment by sidantaa** [comment]
> Hello. It’s likely an issue with PHP 7.4. The software is untested with that version. Try downgrading to 7.2 or under and see it that resolves the issue.

Thanks for the reply but the problem is still the same.. I tried first downgrading the client from php version 7.4 to 7.2; this didn't worked and again downgraded it to php 7.0.33 as of the server; it didn't worked as well. Both the server and client is running in php version 7.0.33 but still the record is not being updated in bind server.. Besides , every record will be added in fmdns database but not being updated to the client side i.e. bind server although the cron job is executing at its defined time.

**In FMDNS Server**
PHP 7.0.33 (cli) (built: May 12 2020 08:41:35) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies

**In Bind Server i.e. client**

PHP 7.0.33-29+ubuntu20.04.1+deb.sury.org+1 (cli) (built: May 14 2020 09:10:15) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-29+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies


**Please help me. I am roaming around this problem since past two weeks. There is no any error so i am unable to step forward to troubleshoot.**

**Comment by WillyXJ** [comment]
What happens when you run the client manually in debug mode?

`sudo client.php cron debug`

Or

`sudo client.php buildconf debug`

**Comment by sidantaa** [comment]
> sudo client.php buildconf debug

It says  "sudo: client.php: command not found" on both cases.

**root@RIJAL-HOME:/# sudo client.php cron debug
sudo: client.php: command not found

root@RIJAL-HOME:/# sudo client.php buildconf debug
sudo: client.php: command not found**

**Comment by sidantaa** [comment]
FYI...

The records have been added in the database.

**Comment by WillyXJ** [comment]
Sorry. Bad assumption on my part. 

`sudo /usr/local/facileManager/fmDNS/client.php cron debug`

And the same for buildconf.

**Comment by WillyXJ** [comment]
Do you have any other php scripts you can run on the cli? It seems something might be wrong with your environment as both of those should output something.

**Comment by sidantaa** [comment]
> Do you have any other php scripts you can run on the cli? It seems something might be wrong with your environment as both of those should output something.

Sorry this didn;t worked though:

root@RIJAL-HOME:~# sudo /usr/local/facileManager/fmDNS/client.php cron debug
sudo: /usr/local/facileManager/fmDNS/client.php: command not found
root@RIJAL-HOME:~# sudo php /usr/local/facileManager/fmDNS/client.php cron debug            root@RIJAL-HOME:~#

and i tested one simple script of php here  and it worked!!!

**root@RIJAL-HOME:**/tmp/phptest# php testcheck.php
Great !!!! The script Worked

**Comment by WillyXJ** [comment]
Ok, change line 34 of /usr/local/facileManager/fmDNS/client.php to the following and run it again.

`error_reporting(E_ALL);`

I'm hoping this will display a fatal error that will indicate what is wrong.

**Comment by sidantaa** [comment]
> Ok, change line 34 of /usr/local/facileManager/fmDNS/client.php to the following and run it again.
> 
> `error_reporting(E_ALL);`
> 
> I'm hoping this will display a fatal error that will indicate what is wrong.

Thanks for your support. I have now encountered what really did happened in my case. This problem have ruined my entire days and nights. And the simple silly mistake was on my server side. I was conscious about the enforce ssl option in FMDNS gui and hence i deleted the configuration from its database but i forgot to disable https in my apache server. So whenever the client runs the cron job ; it tried to have a https connection with server so this all mess begun. 

I encountered this problem while i was trying to reinstall my fmdns package in client side. 

It displayed that " Installation failed. Could not communicate properly with x.x.x.x (ip address of the server) . Failed to acess  https:// <x.x.x.x>/dnsadmin/admin-accounts.php?verify.

And it all got fixed after disabling https in server side.
![redirect tp https fmdns](https://user-images.githubusercontent.com/35427754/82736061-6b330a00-9d46-11ea-8591-109e95368eb6.png)


Anyway thanks for your support!!!!

**Comment by WillyXJ** [comment]
Great! Thanks for the report and I'll work on a fix for the client so it won't be so quiet.

**Comment by sidantaa** [comment]
> Great! Thanks for the report and I'll work on a fix for the client so it won't be so quiet.

Thanks. Will you please instruct me on how to configure it with https?? if i again try to configure with https same thing gonna happen...please instruct me how to do it.

Also, can we run the cron jobs in less than 1 minute?? how to do it?? Currently it's running in every 1 minute. Thanks

**Comment by WillyXJ** [comment]
Enable https on the server. Then on the client you can update FMHOST in /usr/local/facileManager/config.inc.php with your https host. Alternatively, you can delete config.inc.php and then run `client.php reinstall`

1 minute is the fastest interval crond supports.

**Comment by sidantaa** [comment]
Thanks i will do it now🙂🙂🙂

**Comment by sidantaa** [comment]
> Enable https on the server. Then on the client you can update FMHOST in /usr/local/facileManager/config.inc.php with your https host. Alternatively, you can delete config.inc.php and then run `client.php reinstall`
> 
> 1 minute is the fastest interval crond supports.

Hello, Everything is working like a charm now!!! I am here to ask you one question. Is there any way to change the time format of FMDNS in my country's pattern so that i can analyze logs easily?

**Comment by WillyXJ** [comment]
It looks like on your client the location of fM would be https://192.168.11.200/dnsadmin

If the web interface is not displaying correctly, please make sure the rewrite rules/.htaccess is setup.

**Comment by sidantaa** [comment]
> It looks like on your client the location of fM would be https://192.168.11.200/dnsadmin
> 
> If the web interface is not displaying correctly, please make sure the rewrite rules/.htaccess is setup.

What should be the location in FMHOST then?/ i am confused with the process.

**Comment by WillyXJ** [comment]
Based on your screenshots, https://192.168.11.200/dnsadmin, or whatever the URL is for fM.

**Comment by sidantaa** [comment]
> Based on your screenshots, https://192.168.11.200/dnsadmin, or whatever the URL is for fM.

I kept https://192.168.11.200/dnsadmin in FMHOST but don't know why it's not working.. should we also need to work on redirect urls like http request to https in virtual host of web servers such as apache or may be sth else??
