### ISSUE TITLE
[ISSUE] Is there any way to include a public file ?

### ISSUE THREAD

**Issue by marksmansj** [WillyXJ/facileManager#493]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.5.7**
{Module Name} Version : **3.4.1**

Hello. I have a question about $INCLUDE in zone file. for example  my domain name is liz.com. I have four views and I create zone liz.com in every view.  if I want to add a record that like cdn provide me a CNAME record. I don't care the view problem . now I need to add this record at every zone of the four views . it's a tricky job. so I want to know is there any way that I create a public file and all zones(liz.com) of the four views include the public file.  so I just add the public record into the public file  and then all zones(liz.com) of the four views all can have this record.

**Comment by WillyXJ** [comment]
I can think of two ways:

1. For each zone you can configure additional options by clicking the slider icon next to each zone name. From there you can use the "include" parameter and define the file you want bind to include (the file will have to get to the bind servers outside of fmDNS though).
2. Utilize the concept of clone zones. Here, you define one zone like normal, then you can click the small plus next to the name to create a clone of it. Each clone can be associated with a different view. The clones will inherit the records of the parent automatically and can be overridden or excluded on an individual basis.

**Comment by marksmansj** [comment]
you mean the first way  after I set the "include" parameter . if I want to add a public record . I need to edit public file  by vim and then scp this file to bind master server ?  how about slave server ?  and if after I update this file . how can I reload all the zones ?

**Comment by WillyXJ** [comment]
Any changes to your dns servers outside of fmDNS will need to be dealt with manually. You can, however, force a configuration build of servers at any time through the web interface at the Config->Servers page.

**Comment by marksmansj** [comment]
thank you so much
