### ISSUE TITLE
URL was not found on this server

### ISSUE THREAD

**Issue by sidantaa** [WillyXJ/facileManager#495]
Hello all, recently i had installed FMDNS in centos server and it was all fine there. I have been trying to install and configure in ubuntu server for one of the client. I am getting error as url not found.. I have provided the permission to directory and file too but its not working yet. Please help me... I have done everything as i used to do in centos server but don't know what's happening here in ubuntu server. Please help me
![errorfmdns](https://user-images.githubusercontent.com/35427754/85619956-caa47280-b682-11ea-98cb-d6c2f259b00c.jpg)

**Comment by WillyXJ** [comment]
Do any of these solutions help you?

https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+admin-modules.php

**Comment by sidantaa** [comment]
> Do any of these solutions help you?
> 
> https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+admin-modules.php

Thanks the issue was due to virtual host configuration. I changed the configuration from:

_<VirtualHost *:80>
  DocumentRoot /var/www/html/dnsadmin

  AllowEncodedSlashes NoDecode
  <Directory "/var/www/html/dnsadmin/">
    <IfModule mod_php5.c>
    php_admin_flag engine on
    </IfModule>
    Require all granted
   # AllowOverride All
    Options FollowSymLinks MultiViews
  </Directory>
</VirtualHost>_


TO:

_Alias /dnsadmin /var/www/html/dnsadmin

<Directory /var/www/html/dnsadmin/>

 Options FollowSymLinks
 AllowOverride All

# For Apache = 2.3:
 Order allow,deny
 allow from all

 # For Apache = 2.4
 # Require all granted
</Directory>_


Now, its working. Thanks.
