### ISSUE TITLE
[ISSUE] PfSense BIND Install Errors

### ISSUE THREAD

**Issue by MeCJay12** [WillyXJ/facileManager#496]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 3.5.7
fmDNS Version : 3.4.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Standard DNS requests handled and FM reporting build successful.

**(BUG | ISSUE) Actual Behavior:**
DNS requests beings returned REFUSED and FM error when pushing config: 
rndc: neither /usr/local/etc/namedb/rndc.conf nor /usr/local/etc/namedb/rndc.key was found

If I run rndc-confgen, copy the key into /usr/local/etc/namedb/rndc.key, and restart named I get a different error. I also tried moving the sample rndc.conf file into the /usr/local/etc/namedb/ directory and got the same error.
Key that I copied:
key "rndc-key" {
	algorithm hmac-sha256;
	secret "6QlIfhsVRBkzCvuxjqk1dbYz273zypMlwnqaJRxHVQ0=";
};
New error:
rndc: connection to remote host closed
This may indicate that
* the remote server is using an older version of the command protocol,
* this host is not authorized to connect,
* the clocks are not synchronized,
* the key signing algorithm is incorrect, or
* the key is invalid.

**(BUG | ISSUE) Steps to reproduce:**
Install pfSense then add the sudo package and the bind package then run through the standard FM install procedure.

**Comment by WillyXJ** [comment]
I finally had a look at this issue.  Were you able to get it working? I'm not yet seeing this as an issue with fmDNS, but rather potentially with the rndc config for BIND on pfSense.

**Comment by MeCJay12** [comment]
I was unable to get this working. I spent about a week working with this before abandoning it for Quagga/iptables/Ubuntu.
