### ISSUE TITLE
[BUG] Some DHCP global options added without word "option"

### ISSUE THREAD

**Issue by Kelivan** [WillyXJ/facileManager#497]
fM Version : **3.5.7**
fmDHCP Version : **0.4.4**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
option domain-name
option domain-name-servers

**(BUG | ISSUE) Actual Behavior:**
domain-name
domain-name-servers

**(BUG | ISSUE) Steps to reproduce:**
Just add this options in global config.

Some DHCP global options added without word "option".

**Comment by oshlykov** [comment]
up

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.4.5](http://www.facilemanager.com/modules/fmdhcp/) and later.
