### ISSUE TITLE
[ISSUE] fmdns: "installation aborted  not an active module"

### ISSUE THREAD

**Issue by vsuay** [WillyXJ/facileManager#499]
fM Version : 3.5.7
fmDNS Version : 3.4.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

We installed FacileManager in our management server, then installed fmDNS Module and activvated it from the web console.

We installed fmDNS client in two additional DNS servers running BIND. Installation was fine and we were able to register them successfully in the Management server.

However next day, following the same procedure in a similar additional server, we were not able to finish the installation of the fmDNS client, when arriving to the serial number part we leave it blank:

------------output start----------------
Please enter the serial number for servername (or leave blank to create
new):
--> Generating new serial number: failed

Installation aborted. is not an active module.
------------output end----------------

Please note that the message does not indicate a module name, Instead of "fmDNS is not an active module." it only says "[empty string] is not an active module", just in case this was significant.

We still don´t understand how this could initially work and then fail, and we are investigating if any actual changes took place in our server. However, we would like to understand why this happens in order to prevent it,

Thanks for your help and regards

**Comment by WillyXJ** [comment]
@vsuay That's an odd one.  The $module_name variable gets populated from client.php based on the directory structure its in.  Are you able to confirm the client files were in /usr/local/facileManager?  What PHP version was used on both clients?

**Comment by vsuay** [comment]
Dear WillyXJ,

Sorry for the late reply, yes this is really a weird issue that we have not always found while installing/uninstalling/reinstalling.
I confirm the client was in the indicated path /usr/local/facileManager, and that the PHP version was in both cases 7.2.24

Thanks for your support and best regards,

______________________________
Victor SUAY
Systems Technician
Data Centre Support Unit

[cid:image001.png@01D6AB9A.9BA4CB30]    + 034 (96) 199 3856

[ICC_Certified]<https://www.unicc.org/Pages/Home.aspx>

**Comment by WillyXJ** [comment]
I have looked further and cannot find an explanation for this behavior. What OS is your client and do you have a vanilla PHP installation or does it have modifications?

**Comment by vsuay** [comment]
Hello,

Sorry for the late answer, our OS version is CentOS Linux release 8.2.2004, and PHP is 7.2.24 without modifications.
Fortunately, we haven’t experienced the issue again so far, but we could not figure out an explanation why it happened.

Thanks for your help and best regards,

______________________________
Victor SUAY
Systems Technician
Data Centre Support Unit

[cid:image001.png@01D6CA17.243BDD90]    + 034 (96) 199 3856

[ICC_Certified]<https://www.unicc.org/Pages/Home.aspx>
