### ISSUE TITLE
[BUG] Application cannot locate certificate when using LDAPS

### ISSUE THREAD

**Issue by vsuay** [WillyXJ/facileManager#500]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

fM Version : 3.5.7
fmDNS Version : 3.4.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

We installed certificates generated by our PKI in order to use LDAPS authentication for fmDNS. Root CA certificate was installed too, however, authentication does not work, apparently because the code is not able to find the Root CA cert.

We actually did it work by specifying where connection to LDAPS is initiated in file:
/var/www/html/dnsadmin/fm-modules/facileManager/classes/class_logins.php

by adding this line:

ldap_set_option(NULL, LDAP_OPT_X_TLS_CACERTFILE, "/etc/pki/tls/certs/ca-bundle.trust.crt");

We think that for some reason application is not able to find the root certificate, even though it is located in a well-known path.

Thanks and best regards,
V.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.0-beta1](http://www.facilemanager.com/download/?t=3) and later. Final release will come out later.

**Comment by vsuay** [comment]
Dear WillyXJ,

Thank you very much for fixing the issue, we will test it in our DEV environment, but wait for final release to deploy in production.

Best regards,

______________________________
Victor SUAY
Systems Technician
Data Centre Support Unit

[cid:image001.png@01D6AB9A.DAEA4DB0]    + 034 (96) 199 3856

[ICC_Certified]<https://www.unicc.org/Pages/Home.aspx>

**Comment by WillyXJ** [comment]
I should mention that the fix is by adding two more options in Admin -> Settings to define the certificate(s) under the LDAP authentication section.

**Comment by WillyXJ** [comment]
[fM 4.0.0](http://www.facilemanager.com/download/) has been released.
