### ISSUE TITLE
 [FEATURE REQUEST] Implement RFC8162 (SMIMEA)

### ISSUE THREAD

**Issue by magl8** [WillyXJ/facileManager#501]
Please implement SMIMEA resource records according to RFC8162.

The DNS syntax for SMIMEA is identical to TLSA and OPENPGP records which are both available in beta4.0.0.

Publishing SMIMEA records would enable any administrator to create his own S/MIME certificates for mail encryption.
This solves the issue of secure key publishing as the DNS entries are verified by DNSSEC. 
The "quick win" is that current users of any S/MIME maildomain encryption solution can publish their existing certificate in DNS and skip the usual TOFU process for all their new mail encryption partners.

---
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
