### ISSUE TITLE
[ISSUE] Trying to add domain to named.conf with fmDNS module

### ISSUE THREAD

**Issue by equintana-dtic** [WillyXJ/facileManager#502]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : tried **3.5.1** and **4.0.0-beta1**
{Module Name} Version : tried **3.4.1** and **4.0.0-beta1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
When adding new domains on Zones > Forward, expect a "Your configuration is loadable." when updating build on servers configured.

**(BUG | ISSUE) Actual Behavior:**
When adding new domains on Zones > Forward, we are getting this error on master server config build: 
"Your configuration contains one or more errors:

entropy.c:23: fatal error: RAND_bytes(): error:24064064:lib(36):func(100):reason(100)"

**(BUG | ISSUE) Steps to reproduce:**
We are getting this only trying to add a domain on  Zones > Forward

{Your configuration contains one or more errors:

entropy.c:23: fatal error: RAND_bytes(): error:24064064:lib(36):func(100):reason(100)}

Our bind is installed from source, to get the latest version "9.16.8"
Our configuration is based on a chrooted bind. The chroot jail is created with the following commands:

- mkdir -p /srv/named && cd  /srv/named && mkdir -p dev etc/named/ usr/lib/engines var/run/named && mknod /srv/named/dev/null c 1 3 && mknod /srv/named/dev/urandom c 1 9 && chmod 666 /srv/named/dev/{null,urandom} && cp /etc/localtime etc

**Comment by WillyXJ** [comment]
This is definitely not an issue with the code in fM or it’s modules, but rather with the environment they are on. fmDNS will execute the named-checkconf and named-checkzone utilities on the fM server where the web interface is installed. If you’re able to run those utilities manually without error then PHP ought to be able to run them as well.

**Comment by equintana-dtic** [comment]
Thank's for your quickly answer.
We will try to investigate from where is this issue. I seems that there is some kind of problem with random and urandom devices on the jail.
Thank you anyway ;)
