### ISSUE TITLE
[ISSUE] Updating to newer Version

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#503]
fM Version : **3.5.7**
{fmDNS} Version : **3.4.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:** Click Update and get the newest version available.

**(BUG | ISSUE) Actual Behavior:** It says: Unable to download file.

**(BUG | ISSUE) Steps to reproduce:**

Click Update

FM told me, that there is a new Version for Core and fmDNS. I tried to update via FM and it tells me "Unable to download file."

This seems to be caused by a wrong Link to the file that should be downloaded.

When clicking on Update it tries to query the file: http://www.facilemanager.com/download/facilemanager-core-4.0.tar.gz, which results into a 404.

From the facilemanager.com i got the following download link: http://www.facilemanager.com/download/facilemanager-core-4.0.0.tar.gz

This also affects the update of the fmDNS module:

Downloading http://www.facilemanager.com/download/module/fmdns-4.0.tar.gz
Unable to download file.

http://www.facilemanager.com/download/module/fmdns-4.0.0.tar.gz

Thanks for your help,
Christian

**Comment by WillyXJ** [comment]
Oops. This is fixed now from the facilemanager.com web server.

**Comment by cm91** [comment]
Thanks, now it's working.
