### ISSUE TITLE
[ISSUE] mysql upgrade breaks on fmFirewall

### ISSUE THREAD

**Issue by wispr** [WillyXJ/facileManager#504]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.0**
fmFirewall Version : **2.0.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Working on upgrading to the 4.x line from FM 3.5.7 and fmDNS but having an issue on the upgrade. Attached screenshot. Also receive duplicate column name errors for policy_name and policy_template_id. Attempted to remove the duplicate columns called out in the errors and can finally get to this error, but not sure how to fix the root cause or how to resize the column appropriately. I have a good backup from before the upgrade and have attempted to perform the upgrade again on the original database with no luck.

![Capture](https://user-images.githubusercontent.com/7743948/99412669-d864c980-28a9-11eb-87af-08fbc80e0ade.PNG)

**Comment by WillyXJ** [comment]
What version of fmFirewall did you have installed prior to upgrading?

**Comment by wispr** [comment]
Not 100% sure, generally all of the modules are upgraded together, but the fmfirewall wasn't in active use.

**Comment by WillyXJ** [comment]
What's the output of this query on your database?

```
SELECT DISTINCT policy_type FROM `fm_fw_policies`
```

**Comment by wispr** [comment]
mysql> SELECT DISTINCT policy_type FROM `fm_fw_policies`;
+-------------+
| policy_type |
+-------------+
| rules       |
+-------------+
1 row in set (0.00 sec)

mysql> SELECT option_value FROM `fm_options` WHERE module_name='fmFirewall' AND option_name='version';
+--------------+
| option_value |
+--------------+
| 1.7.1        |
+--------------+
1 row in set (0.00 sec)

**Comment by WillyXJ** [comment]
Your results are peculiar to me given the code as I do not see how you could have that combination.  However, here's a manual fix for you.  Run the following SQL statement manually and then perform the upgrade.

```
UPDATE `fm_fw_policies` SET `policy_type`='filter' WHERE `policy_type`='rules';
```

**Comment by wispr** [comment]
Still not quite getting it. The upgrade process complains about duplicate columns for policy_name and policy_template_id. We can manually remote those, run the command you provided, and still get this one. 
![Capture](https://user-images.githubusercontent.com/7743948/99577390-1dfbc200-2990-11eb-8fea-476c91bc4acf.PNG)

**Comment by WillyXJ** [comment]
That's bizarre. Did you try restoring your database from your backup, running the SQL statement manually, and then running through the upgrade process?

**Comment by wispr** [comment]
yeah, that's exactly what I did the first time after the upgrade failed. restored the db and tried it again...

**Comment by WillyXJ** [comment]
I don't yet understand why you're receiving those failures as they shouldn't exist. Would you please run those two SELECT statements again and provide me with the results?

**Comment by wispr** [comment]
commands prior to re-running the manual fix option:

```
mysql> SELECT DISTINCT policy_type FROM `fm_fw_policies`
    -> ;
+-------------+
| policy_type |
+-------------+
| rules       |
+-------------+
1 row in set (0.00 sec)

mysql> SELECT option_value FROM `fm_options` WHERE module_name='fmFirewall' AND option_name='version';
+--------------+
| option_value |
+--------------+
| 1.7.1        |
+--------------+
1 row in set (0.00 sec)
```

running these commands after the upgrade fails again:
alter table fm_fw_policies drop column policy_template_id;
alter table fm_fw_policies drop column policy_name;
UPDATE `fm_fw_policies` SET `policy_type`='filter' WHERE `policy_type`='rules';

and then you get the following again:
```

mysql> SELECT DISTINCT policy_type FROM `fm_fw_policies`;
+-------------+
| policy_type |
+-------------+
| rules       |
+-------------+
1 row in set (0.00 sec)

mysql> SELECT option_value FROM `fm_options` WHERE module_name='fmFirewall' AND option_name='version';
+--------------+
| option_value |
+--------------+
| 1.7.1        |
+--------------+
1 row in set (0.01 sec)
```

**Comment by WillyXJ** [comment]
It does not look like any records were changed during the manual UPDATE statement. After running it, you should no longer see 'rules' as a policy_type as it should set all records to policy_type='filter'.  Did you receive any errors when you applied that SQL statement?  Did it report any records getting changed?

**Comment by WillyXJ** [comment]
Fixes to the installer/upgrader have been added to [fmFirewall 2.0.3](http://www.facilemanager.com/modules/fmfirewall/).

**Comment by wispr** [comment]
Restored from backup, updated to the most recent full release on the server, ran the update again and getting this slightly different error. I'm assuming this is all server side at this point and nothing needs to be done on the client yet.

![Capture](https://user-images.githubusercontent.com/7743948/100628110-b5d8a480-32dc-11eb-9301-aadedfe8980d.PNG)

**Comment by WillyXJ** [comment]
It doesn't look like your database is actually getting updated like it's supposed to. Basically, older versions of fmFirewall allowed only 'rules' to be a value for policy_type. 1.4 and later would change the structure to support 'filter', update all records from 'rules' to 'filter', and then drop support for 'rules'. When you get a "Data truncated" error, it's usually because the table structure does not support the values being applied or the current values do not allow the structure to be changed.

We may have to apply some changes manually to see if they even get applied.

Please run this to see what the current structure is for policy_type:

```
DESC fm_fw_policies;
```

In theory you should see something like this for fm_fw_policies:

```
| policy_type                   | enum('rules','filter')     | NO   |     | filter  |                
```

If it's not, you can run this to set the structure and then run the above to see if the structure actually got set:

```
ALTER TABLE `fm_fw_policies` CHANGE `policy_type` `policy_type` ENUM('rules','filter') NOT NULL DEFAULT 'filter';
```

Once rules and filter are listed, then run the following which will tell you what values are currently in your records:

```
SELECT DISTINCT policy_type FROM `fm_fw_policies`;
```

You can then set all records to 'filter' with the following:

```
UPDATE `fm_fm_policies` SET `policy_type`='filter' WHERE `policy_type`='rules';
```

Check to see if they actually got updated:

```
SELECT DISTINCT policy_type FROM `fm_fw_policies`;
```

If they did, then you can try the upgrade process again which should continue and complete. If they did not get updated, then you'll need to find out why your database is not updating its records.

**Comment by wispr** [comment]
Those steps worked perfect. policy_type was still set to rules for whatever reason. the manual steps above fixed it and I was able to run the standard upgrade process and have it fully complete.
