### ISSUE TITLE
[BUG] column missing from fm_dns_acls table

### ISSUE THREAD

**Issue by Puohis** [WillyXJ/facileManager#505]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.0**
fmDNS Version : **4.0.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Addresses can be added to ACLs

**(BUG | ISSUE) Actual Behavior:**
Error message (below) is shown and adding addresses fails.

Could not add the ACL because a database error occurred.

Database error: [Unknown column 'acl_bulk' in 'field list' | Query: [INSERT INTO `fm_dns_acls` (acl_id, acl_parent_id, server_serial_no, acl_bulk, acl_addresses, acl_comment, account_id) VALUES ('0', '78', '0', '', 'xxx.xxx.xxx.xxx', '', '1')]]

**(BUG | ISSUE) Steps to reproduce:**
1. Create new ACL
2. Add address to it

or

1. Add address to existing ACL

{replace this line with your issue content}

**Comment by WillyXJ** [comment]
As a workaround, you can add your ACL entries in in bulk (Confiure multiple addresses in bulk »).

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 4.0.1](http://www.facilemanager.com/modules/fmdns/) and later.
