### ISSUE TITLE
[BUG] fmWifi - crontab entry

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#506]
fM Version : **4.0.0**
fmWifi Version : **0.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

fmWifi client creates a crontab entry and this should run without a problem

"* * * * * /usr/bin/php client.php status-all"

**(BUG | ISSUE) Actual Behavior:**

fmWifi client creates a crontab entry and this fails because the full path to client.php is missing

**(BUG | ISSUE) Steps to reproduce:**

install fmWifi client

I have recently tried out fmWifi with a Raspberry Pi as access point.
The access point is working, so the configuration itself seems to be okay.
In the facileManager the Dashboard stayed empty. I could not see connected clients.
At first i thought this is maybe not fully implemented yet.

Then i noticed, that the cron daemon is sending lots of Mail like this:

From: Cron Daemon <root@ap1>
To: root@ap1
Subject: Cron <root@ap1> /usr/bin/php client.php status-all

Could not open input file: client.php

The fmWifi Client is located under /usr/local/facileManager/fmWifi, so if i change the cron entry to the full path, the cronjob
runs properly and on the facileManager Dashboard i can also see connected clients now.

This is my crontab entry now:

"* * * * * /usr/bin/php /usr/local/facileManager/fmWifi/client.php status-all"

I'm not sure if this is related to my setup or if this is a general problem.

**Comment by WillyXJ** [comment]
You are correct. The full path is required for the crontab entry. This occurred because client.php was called without the full path. This is fixed in the next release.

**Comment by WillyXJ** [comment]
This is now fixed in [fmWifi 0.3.1](http://www.facilemanager.com/modules/fmwifi/) and later.
