### ISSUE TITLE
[BUG] - rndc reload complains about named.conf.keys when in use

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#514]
fM Version : **4.0.2**
fMDNS Version : **4.0.2**

**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**Expected Behavior:**
Keys would load

**Actual Behavior:**
RNDC fails to reload with the key file:

**Steps to reproduce:**
Add a key and reload through fM

---------------------
Ubuntu 20.04 LTS
PHP 7.4.3
BIND 9.16.1-Ubuntu

When adding a key to the keys sections of fMDNS I'm seeing reload errors:
```
--> [hostname] rndc: 'reload' failed: permission denied
```
Using systemctl status named:
```
received control channel command 'freeze'
freezing all zones: success
received control channel command 'reload'
loading configuration from '/etc/bind/named.conf'
/etc/bind/named.conf.options:3: open: /etc/bind/named.conf.keys: permission denied
reloading configuration failed: permission denied
```
Key file gets created with write access to root:
```
ls -lach /etc/bind/named.conf.keys
-r-------- 1 root root 179 Jan  6 11:17 /etc/bind/named.conf.keys
```
No idea if this is correct but keys at the moment are completely unusable for me.

**Comment by WillyXJ** [comment]
When you edit your server properties, is your "Run-As Account" set to root or something else?

<img width="500" alt="Screen Shot 2021-01-06 at 8 29 10 AM" src="https://user-images.githubusercontent.com/1309591/103786378-9cbcc500-4ff9-11eb-923f-579d4ee64d65.png">

If it's set as root then you probably need to change it to whatever account named is running as on your server.

**Comment by Lormen** [comment]
Thanks! That solved the problem!

For others:
```
ps aux |grep named
bind       31419  0.0  1.8 690092 72556 ?        Ssl   2020   4:10 /usr/sbin/named -f -u bind
```
-u is user so user is bind.

Thanks again for the quick response.
