### ISSUE TITLE
[FEATURE REQUEST] chaos class

### ISSUE THREAD

**Issue by pedro6161** [WillyXJ/facileManager#516]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.2**
fmdns Version : **4.0.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

may i know how to create CH or chaos for SOA ? and i'm also tried to create CH class in TXT record but showing error on below 

/etc/named/zones/master/db.example.net.12.hosts:20: class 'CH' != zone class 'IN'
zone example.net/IN/internet-chaos: loading from master file /etc/named/zones/master/db.example.net.12.hosts failed: bad class
zone example.net/IN/internet-chaos: not loaded due to errors.

cat /etc/named/zones/master/db.example.net.12.hosts
; This file was built using fmDNS 4.0.2 on Mon, 01 Feb 2021 11:19:01 +0000 UTC

$TTL 60
example.net. IN SOA a.example.net. admin.example.net. (
		2021020104	; Serial
		900		; Refresh
		900		; Retry
		1800		; Expire
		60 )		; Negative caching of TTL

; Name servers
example.net.                       IN   NS   a.example.net.
example.net.                       IN   NS   b.example.net.

; Host addresses
a.example.net.                   IN   A   1.1.1.1
b.example.net.                   IN   A   2.2.2.2

; TXT records
authors.example.net.               CH   TXT	("trial. :)")
version.example.net.               CH   TXT	("testing")

**Comment by WillyXJ** [comment]
This is an oversight as the class is hardcoded in the SOA.  I've changed this issue to a feature request.

**Comment by WillyXJ** [comment]
In addition, you can simply set the version that BIND reports by defining the "version" global option.

**Comment by pedro6161** [comment]
> In addition, you can simply set the version that BIND reports by defining the "version" global option.

i did already but as you know regarding security reason :)

**Comment by WillyXJ** [comment]
Based on https://tools.ietf.org/id/draft-sullivan-dns-class-useless-02.html which explains that classes are rarely used and not well supported, record class support will be dropped so only the INternet class will be supported in future versions of fmDNS.
