### ISSUE TITLE
[BUG] Can't change forwarder in forward domain after it was established

### ISSUE THREAD

**Issue by twildATgmxde** [WillyXJ/facileManager#518]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.3**
fmDNS Version : **4.1.0**

---

**Can't change an parameter in a forward domain after it was established**

**No change inside the forward domain is possible anymore**

**Create a forward domain, save it, than try to change anything**

**Comment by WillyXJ** [comment]
Thanks for the report. Here is a workaround until a fix is in place:

1. Go to Zones -> Forward
2. Take note of the ID of the forward zone to change (example 522)
3. Manually go to /config-options.php?domain_id=<ID> (example /config-options.php?domain_id=522)
4. Edit the forwarder options

**Comment by twildATgmxde** [comment]
Hello 

many thanks. it worked out!

**Comment by WillyXJ** [comment]
This bug impacts slave and stub zones as well.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
