### ISSUE TITLE
recursion yes without zone . root hits

### ISSUE THREAD

**Issue by pedro6161** [WillyXJ/facileManager#520]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.3**
<fmDNS> Version : **4.1.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

it's possible or not if i enable options recursion yes without zone . or root hits ? because my setup is cache dns and forwarder dns will be separate server and only forwarder can query root hits or zone type hits

**Comment by WillyXJ** [comment]
It is not possible to enable recursion without the root hints.

**Comment by pedro6161** [comment]
@WillyXJ thanks for your confirmations
