### ISSUE TITLE
[ISSUE] fmDNS Manager: ssh connection reports: client file is not present

### ISSUE THREAD

**Issue by am155** [WillyXJ/facileManager#521]
fM Version : 4.0.3
fmDNS Version : 4.1.0

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Server should be able to execute ssh command on named server

**(BUG | ISSUE) Actual Behavior:**
Error Message: SSH Login:     client file is not present

**(BUG | ISSUE) Steps to reproduce:**

Server: Ubuntu 20.04 with NGINX, and apache2, php 7.4
DNS Server: Ubuntu 20.04, bind9, php-cli 7.4

1. SSH Connection from server with user: fm_user can connect to the DNS server.
2. sudoers entry has been create by the client installation program
3. the fm_user can execute the script: /usr/bin/php /usr/local/fmDNS/fmDNS/client.php -b -d

But: Connectivity Test result shows
Running tests for ns4.domainname.eu
	Ping:          success
	Remote Port:   success (tcp/22)
	SSH Login:     client file is not present
	DNS:           failed (tcp/53)

Zone Server - build config reports:
  Failed: Client file is not present - is the client software installed?

**Comment by WillyXJ** [comment]
The server expects the client.php file to be in /usr/local/facileManager/<module-name>/client.php. If you rename /usr/local/fmDNS to /usr/local/facileManager and update your sudoers line to reflect that, then it should work as expected.

**Comment by am155** [comment]
brilliant - working now.

Thank you for your effort.
