### ISSUE TITLE
[ISSUE] Admin -  "add new user" fails - SAVE does't submit

### ISSUE THREAD

**Issue by am155** [WillyXJ/facileManager#522]
fM Version : 4.0.3
fmDNS Version : 4.1.0

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
fM Admin GUI to create new users: SAVE new user is not execute - GUI stalled

**(BUG | ISSUE) Actual Behavior:**
fM Admin GUI to create new users: SAVE should submit and create new user
**(BUG | ISSUE) Steps to reproduce:**

Nginx + Apache running PHP 7.4
Initial admin user super-fm is working fine.
Create new user fails, due to SAVE is not execute - GUI interface stalled. Modal window doesn't report eror in firefox or chrome debugger.
No PHP error message in server log files.

**Comment by WillyXJ** [comment]
What fields have you filled out in the form?  The save button is disabled if the username and password fields (if using Built-in Authentication) are empty.

**Comment by am155** [comment]
All fields are filled in. Settings - Authenication Method - is set to Build-in Authentication.
Don't know why that submit is NOT working - adding groups or other stuff like zones is working perfect.

I will check nginx header settings, because they are very strict ...

**Comment by WillyXJ** [comment]
It sounds like the Save button is still in a disabled state. The state of the button is governed by jQuery and the app has been tested in recent versions of Chrome, Firefox, and Safari. After you fill in the fields, inspect the page in your browser and see if the save button has the disabled attribute:

```
<input type="submit" id="submit" name="submit" value="Save" class="button primary" disabled>
```

If it looks like the above, you can delete the "disabled" text so you can click Save.

**Comment by am155** [comment]
Exactly - found the < ... disabled=""> in the html input. After removing the disabled: saving "new user" is working.

May be it has something to do with the browser console message:

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://fmdns.xxxxxxxx.eu/fm-includes/js/jquery-1.9.1.min.js
Source-Map-Adresse: jquery.min.map

**Comment by WillyXJ** [comment]
Yes. You need to get that 404 resolved in your environment as the jquery files included in the tar file gets used for just about everything.
