### ISSUE TITLE
[BUG] - fmDHCP doesn't allow next-server / filename for more than one subnet

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#524]
fM Version : **4.0.3**
fmDHCP Version : **0.4.6**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG) Expected Behavior:**
Create a next-server entry and filename entry for any subnet

**(BUG) Actual Behavior:**
Message of "This record already exists."

**(BUG) Steps to reproduce:**
Create multipe subnets and attempt to add a next-server or filename in either of them

As I wasn't sure if this was a bug or by design I edited the DB to include a next-server and filename config for both subnets and it built and worked correctly. It will also not let you edit the record through the dashboard with the same error message.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.5.0](http://www.facilemanager.com/modules/fmdhcp/) and later.
