### ISSUE TITLE
List Domain and detail informations include views from API

### ISSUE THREAD

**Issue by pedro6161** [WillyXJ/facileManager#526]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **X.X.X**
<fmDNS> Version : **4.1.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
N/A

**(BUG | ISSUE) Actual Behavior:**
N/A

**(BUG | ISSUE) Steps to reproduce:**
N/A

how to List all Domain and detail informations include views from API ?

**Comment by WillyXJ** [comment]
There is currently no way of doing that through the very limited API.
