### ISSUE TITLE
[BUG] fmDNS DNSSEC "The selected key size is invalid." 

### ISSUE THREAD

**Issue by JRMoret** [WillyXJ/facileManager#527]
fM Version : 4.0.3
fmDNS : 4.1.0

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

[BUG] the creation of DNSSEC keys does not work.
 In the management of dnssec keys.
    Config \ Keys -> DNSSEC -> Add New
 I chose the zone concerned, leave the other fields empty for the automatic generation of the keys then I save.
 At this time, I am waiting for the KSK and ZSK keys to be created.
 But I have a message "The selected key size is invalid.".
 I tested with "Configure Additional Options" different "Key Size" for the same result. 

After some research in the code, I commented out, for testing, line 533 in "class_keys.php" 
`// if (!in_array($post['key_size'], $__FM_CONFIG['keys']['avail_sizes'])) return __('The selected key size is invalid.');`
The creation of keys is going well.

I think the error is the `$post['key_size']` variable which I don't understand where it came from.
So I replaced it with `$data['key_size']`.
`if (!in_array($data['key_size'], $__FM_CONFIG['keys']['avail_sizes'])) return __('The selected key size is invalid.');`
After test, the keys are created well

Do you confirm that this is the bug fix?

have a good day

**Comment by WillyXJ** [comment]
Are you able to make a pull request?

**Comment by JRMoret** [comment]
Hello,
  no I don't know how to do it.
Have a good day

**Comment by trinv** [comment]
> Are you able to make a pull request?

Hi, i have the same problem. I can not gen DNSSEC Key.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
