### ISSUE TITLE
[BUG] fmDNS DNSSEC "Notice: Undefined property: stdClass::$cfg_data ...." 

### ISSUE THREAD

**Issue by JRMoret** [WillyXJ/facileManager#528]
fM Version : 4.0.3
fmDNS : 4.1.0

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

[BUG] When creating a new DNS zone, a php error in the header of the result window
Hello,
  I have php errors when creating new zones.
    `Notice: Undefined property: stdClass::$cfg_data in /var/www/html/facileManager/fm-modules/fmDNS/classes/class_buildconf.php on line 2467`
  This error has no effect on new and old zones.
 
  After some research, these errors are there because I have some zones with DNSSEC and several groups of servers with some DNS servers in common.
  Example: 	group1 = Master NS1, NS2, NS3
			group2 = Master NS1, Slave NS2

  I did a bit of debugging on the page "class_buildconf.php" around the php error and I think I found the error.
  Page : class_buildconf.php
  Line : 2459
  The original line:  `$server_group_ids_sql = (is_array($server_group_ids)) ? ", 'g_" . implode(", 'g_", $server_group_ids) . "'" : null;`
	Result a quote is missing : `$server_group_ids_sql = ", 'g_1, 'g_2'"`
  The corrected line : `$server_group_ids_sql = (is_array($server_group_ids)) ? ", 'g_" . implode("', 'g_", $server_group_ids) . "'" : null;`
	Result all the quotes are there : `$server_group_ids_sql = ", 'g_1', 'g_2'"`

  After this correction, I no longer have errors and my DSNSEC zones are no longer a problem for me.

cordially

**Comment by WillyXJ** [comment]
Are you able to make a pull request?

**Comment by JRMoret** [comment]
Hello,
  no I don't know how to do it.
Have a good day

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
