### ISSUE TITLE
fmDHCP server delete not working

### ISSUE THREAD

**Issue by msilveirabr** [WillyXJ/facileManager#529]
[ISSUE]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.3**
fmDHCP Version : **0.4.6**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Unable to delete server, error 'The associated table records could not be removed because a database error occurred.'

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

I'm not a developer, so here's my diff to possible fix, instead of a git pull.

PS: Fresh install

```
--- facileManager/fm-modules/fmDHCP/classes/class_servers.php.org	2021-06-25 00:45:24.295635038 -0300
+++ facileManager/fm-modules/fmDHCP/classes/class_servers.php	2021-06-25 00:40:57.183513958 -0300
@@ -213,9 +213,9 @@
 		basicGet('fm_' . $__FM_CONFIG[$_SESSION['module']]['prefix'] . 'servers', $server_serial_no, 'server_', 'server_serial_no');
 		if ($fmdb->num_rows) {
 			/** Delete associated records from other tables */
-			if (updateStatus('fm_' . $__FM_CONFIG[$_SESSION['module']]['prefix'] . 'table1', $server_serial_no, 'prefix_', 'deleted', 'server_serial_no') === false) {
-				return __('The associated table records could not be removed because a database error occurred.');
-			}
+	//		if (updateStatus('fm_' . $__FM_CONFIG[$_SESSION['module']]['prefix'] . 'table1', $server_serial_no, 'prefix_', 'deleted', 'server_serial_no') === false) {
+	//			return __('The associated table records could not be removed because a database error occurred.');
+	//		}
 			
 			/** Delete server */
 			$tmp_name = getNameFromID($server_id, 'fm_' . $__FM_CONFIG[$_SESSION['module']]['prefix'] . 'servers', 'server_', 'server_id', 'server_name');
```

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.5.0](http://www.facilemanager.com/modules/fmdhcp/) and later.
