### ISSUE TITLE
[ISSUE] Slow user manager page load (Admin / User & Groups)

### ISSUE THREAD

**Issue by edvalley** [WillyXJ/facileManager#530]
fM Version : 4.0.3

In raising this issue, I confirm the following:

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
The user manager page must load rapidly

**(BUG | ISSUE) Actual Behavior:**
The user manager page loads slowly

**(BUG | ISSUE) Steps to reproduce:**
Login to facileManager and go to Admin / User & Groups

A request to `/admin-users.php` takes a long time. The problem is in the call to `gethostbyaddr` at `class-users.php`, line 468. It keeps trying for 30 seconds to get a host name for the users' IP addresses.

Thanks

**Comment by WillyXJ** [comment]
Does your fM server use a DNS server for lookups? If it does, then I wouldn't expect the long timeouts even if the record doesn't exist.

Perhaps an app setting to toggle the resolution of IP addresses should be implemented.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.4.0](http://www.facilemanager.com/download/) and later.
