### ISSUE TITLE
[OTHER] Is it possible to use `include` statements in the server configuration written in `/etc/named.conf`?

### ISSUE THREAD

**Issue by imilos** [WillyXJ/facileManager#532]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.0.3**
fmDNS Version : **4.1.0**

Is it possible to use `include` statements in the server configuration written in `/etc/named.conf`? For example, a default CentoOS 7 config contains something like this:
```
zone "." IN {
	type hint;
	file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
```
How one is supposed to specify these in the GUI?

**Comment by WillyXJ** [comment]
Under Global Options you can specify the include statement and define the file path to include. fmDNS will not manage the external files so you’ll need to ensure they are properly loaded on the dns server.

**Comment by imilos** [comment]
Many thanks for your quick response! Now I notice "Define outside of global options clause".
