### ISSUE TITLE
[FEATURE REQUEST] Certificate File/Root CA Certificate make as optional options

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#534]
fM Version : **4.0.3**
fmDNS Version : **4.1.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
If the Certificate File/Root CA Certificate parameters are missing I expect that they are not used.

**(BUG | ISSUE) Actual Behavior:**
The Certificate File/Root CA Certificate parameters are mandatory when ssl connection is used.

**Comment by WillyXJ** [comment]
Is this for the LDAP authentication configuration?

**Comment by beza2000** [comment]
Yes. It's for LDAPS.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.1.0](http://www.facilemanager.com/download/) and later.
