### ISSUE TITLE
[BUG] Little information about the error

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#535]
fM Version : **4.0.3**
fmDNS Version : **4.1.0**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Not a very important problem.
If there is no necessary program, more specific information is expected.
For example:
> The webserver user (apache) on testbz.xxxxx.ru does not have permission to run the following command:
> 
> /bin/sudo **named-checkzone** -t /var/www/facileManager/tmp/fmDNS_20210811135127/ 0.0.127.in-addr.arpa /etc/named/zones/master/db.0.0.127.in-addr.arpa.hosts 2>&1
> The following error ocurred:....

**(BUG | ISSUE) Actual Behavior:**
My bug - info: 

> The webserver user (apache) on testbz.xxxxx.ru does not have permission to run the following command:
> 
> /bin/sudo  -t /var/www/facileManager/tmp/fmDNS_20210811135127/ 0.0.127.in-addr.arpa /etc/named/zones/master/db.0.0.127.in-addr.arpa.hosts 2>&1
> The following error ocurred:....

**(BUG | ISSUE) Steps to reproduce:**
1. Delete the named-checkzone program
2. Click the Preview Config button in Config->Servers

Problem: the findProgram function (facileManager/server/fm-modules/facileManager/functions.php) doesn't return anything if it didn't find anything.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
