### ISSUE TITLE
[FEATURE REQUEST] Add 'validate-except' to bind options list

### ISSUE THREAD

**Issue by basicmonkey** [WillyXJ/facileManager#537]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 4.0.3
fmDNSVersion : 4.1.0

In raising this issue, I confirm the following (please check boxes, eg [X]):

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Can you please add 'validate-except' to the list of fmDNS bind options please.

Many thanks,

James

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 5.0.0](http://www.facilemanager.com/modules/fmdns/) and later.

**Comment by basicmonkey** [comment]
Thank you! Seems to be working.
