### ISSUE TITLE
[ISSUE] RateLimit options not being written to named.conf.options

### ISSUE THREAD

**Issue by oiLvAcciNe** [WillyXJ/facileManager#542]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.1.2**
fmDNS Version : **5.1.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Ratelimit options set via web and in sql db should be written to named.conf.options.

**(BUG | ISSUE) Actual Behavior:**
The dns ratelimit options are not visible or sent to named.conf.options during BuildConfig.

{replace this line with your issue content}

As you can see 
Conf is visible on web/DB .. but not sent to conf files-
![fmDNSratelimit](https://user-images.githubusercontent.com/93989004/142911029-74ad88b0-fc7e-4bb5-a4cc-b458c0786378.jpg)

**Comment by oiLvAcciNe** [comment]
[AROUND ISSUE]

IN
fm-modules/fmDNS/classes/class_buildconf.php

#### line 1961 
		"$ratelimits .= $this->formatConfigOption($cfg_name, $cfg_info, $cfg_comment);"
		#### should include "$this->server_info"
		$ratelimits .= $this->formatConfigOption($cfg_name, $cfg_info, $cfg_comment, $this->server_info);
		#### because ratelimit option definition require a minimum bind version


#### in line 2027 "function formatConfigOption"
	if ($server_info) {
	###it requires this in order to build config array with $cfg_info
	


Probably there is other modules or options were this is required.
For now have found this

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.2.0](http://www.facilemanager.com/modules/fmdns/) and later.
