### ISSUE TITLE
[FEATURE REQUEST] fmdns unable to add acl inside acl configuration

### ISSUE THREAD

**Issue by oiLvAcciNe** [WillyXJ/facileManager#544]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.1.2**
fmDNS Version : **5.1.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

It should be possible to add once acl into another in bind ocnfiguration

acl teste1{
    2.2.2.2;
  };

acl teste1{
    1.1.1.1;
    teste2;
  };

**(BUG | ISSUE) Actual Behavior:**

You can actually and a name like a ip

![image](https://user-images.githubusercontent.com/93989004/147123250-5cbe3ab4-d7d7-43fc-87e2-8d352c31867b.png)

But when you click save it gives you a error because it is expecting a IP input formatted like.

![image](https://user-images.githubusercontent.com/93989004/147123374-8238852b-4b73-464d-9cc7-207aef691687.png)

**(BUG | ISSUE) Steps to reproduce:**
Create two acls, try to add one into another

![image](https://user-images.githubusercontent.com/93989004/147122648-998fff5a-aece-4ffa-aaa5-3907754fa310.png)

![image](https://user-images.githubusercontent.com/93989004/147123250-5cbe3ab4-d7d7-43fc-87e2-8d352c31867b.png)

{replace this line with your issue content}

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.2.0](http://www.facilemanager.com/modules/fmdns/) and later.
