### ISSUE TITLE
Is there a manual? [Other]

### ISSUE THREAD

**Issue by online-stuff** [WillyXJ/facileManager#547]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.2.0**
fmDNS Version : **5.2.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

Hello,

Is there a manual available somewhere?

GitHub shows 4.0.0 as most recent, facileManager.com shows 4.2.0..  Is github still used?

I am new to facileManager..  Is there a manual somewhere for it?  Kind of lost with the interface..  I can see where to set ACLs for example and a simple Recursion Yes/No, but how do these get implemented?  Can I combine them to allow authority lookups and recursion lookups from different sets of IP addresses?

How do I reorder the listed ACLs?

Lastly, for an actual bug, fmDNS accepts 127.0.0.8/8 for an ACL, but BIND9 refuses to start afterwards, because it should be 127.0.0.0/8

**Comment by WillyXJ** [comment]
> Is there a manual available somewhere?

There still isn't a manual or documentation outside of the built-in help of the application. #455 and #307 desire the same.

> GitHub shows 4.0.0 as most recent, facileManager.com shows 4.2.0.. Is github still used?

All app updates come through facilemanager.com so I create releases for there and I keep forgetting to create complete releases on github for those that prefer to initially download from here. v4.2.0-complete has been created.

> I am new to facileManager.. Is there a manual somewhere for it? Kind of lost with the interface.. I can see where to set ACLs for example and a simple Recursion Yes/No, but how do these get implemented? Can I combine them to allow authority lookups and recursion lookups from different sets of IP addresses?

Yes, you would be looking for adding the "allow-query" and/or "allow-recursion" options at the Global Options level (Config->Options) or at a View level (Config->Views).

> How do I reorder the listed ACLs?

When defining ACLs, the order in which they are defined should not matter.  However, the order in which they are referenced would matter and that is done when you select them in the Options (with allow-query for example below). The order gets defined by the order in which you select them for reference.

![Screen Shot 2022-01-26 at 5 43 21 PM](https://user-images.githubusercontent.com/1309591/151270684-9eaabd7f-20d6-4e25-a1be-16524a576209.png)

> Lastly, for an actual bug, fmDNS accepts 127.0.0.8/8 for an ACL, but BIND9 refuses to start afterwards, because it should be 127.0.0.0/8

Noted, thanks.

**Comment by online-stuff** [comment]
Still experimenting, thank you for the response.  Good hints for what to look for going forward.

I have fmDNS on a separate server from the BIND servers, not sure if this matters for my next question or not..

What is the suggested way to have DHCP client leases pushed from a DHCP server?

DHCP assigns 192.0.2.54 to WIN-559458HD.example.com

What is the best (suggested) way for the DHCP server to update the example.com zone with 192.0.2.54  WIN-559458HD?

**Comment by WillyXJ** [comment]
The DNS zones would need to support updates from the DHCP servers.  You'd likely need to enable/configure the `allow-update` option on the zone(s) you want to be updated.  Perhaps one or more of [these results](https://www.google.com/search?q=bind+dynamic+dns+dhcp&oq=bind+dns+dhcp&aqs=chrome.2.69i57j0i22i30l3.10039j0j7&sourceid=chrome&ie=UTF-8) can help you.

**Comment by online-stuff** [comment]
'nsupdate' seems the proper way, but not sure how to get nsupdate to interact with fmDNS.

**Comment by WillyXJ** [comment]
nsupdate will update the zone on the DNS server itself (dynamic updates).  In order to see those record changes, you'll need to enable the dynamic update support on the zone within fmDNS:

<img width="609" alt="Screen Shot 2022-02-08 at 6 10 09 PM" src="https://user-images.githubusercontent.com/1309591/153102964-8897b8c2-fcee-4a5e-bb84-769158c1f79f.png">

**Comment by WillyXJ** [comment]
The ACL bug is now fixed in [fmDNS 5.3.0](http://www.facilemanager.com/modules/fmdns/) and later.
