### ISSUE TITLE
[BUG] Undefined variable in fm-install.php

### ISSUE THREAD

**Issue by MeCJay12** [WillyXJ/facileManager#548]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 4.2.0

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Connects to MySQL database  successfully and completes install

**(BUG | ISSUE) Actual Behavior:**
DB connection web page says "ERROR: Could not connect to MySQL" and apache error.log says "[Wed Feb 02 04:45:08.308153 2022] [php7:notice] [pid 11243] [client 192.168.2.10:58070] PHP Notice:  Undefined variable: install_enable_ssl in /var/www/html/fm-install.php on line 289, referer: http://power.cshaheen.tech/fm-install.php"

**(BUG | ISSUE) Steps to reproduce:**
Starting with a fresh install of Ubuntu 20:
sudo apt -y update 
sudo apt-get -y install tar wget tzdata php php-curl php-mysql apache2
sudo mkdir /tmp/fm
sudo wget http://facilemanager.com/download/facilemanager-complete-$Version.tar.gz
sudo tar -xzf facilemanager-complete-$Version.tar.gz -C /tmp/fm/
sudo rm -r /var/www/html
sudo mv /tmp/fm/facileManager/server /var/www/html
sudo rm -r /tmp/fm
sudo a2enmod rewrite
sudo systemctl restart apache2

**Comment by WillyXJ** [comment]
Thanks for the PHP error notice.  That will be fixed in the next release.  However, the error is only a notice and it does not prevent the app from connecting to MySQL.  I've tested the clean install successfully.  This looks like your webserver cannot connect to the MySQL server (firewall, MySQL not running, etc.).

**Comment by MeCJay12** [comment]
You're right
