### ISSUE TITLE
Install ssh key might not always work

### ISSUE THREAD

**Issue by Poehli** [WillyXJ/facileManager#553]
At the following place, the grep function should be checked against the whole word (-w option), because otherwise it might match multiple passwd entries. I noticed on my raspberry pi where I have a user pi and pihole. Both are matching pi, which lead to problems.
 
https://github.com/WillyXJ/facileManager/blob/ea159f5f6112727de8422c552aa05b6682aa4d79/client/facileManager/functions.php#L962

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.3.0](http://www.facilemanager.com/download/) and later.
