### ISSUE TITLE
[BUG] leases given by DHCP server can't be shown

### ISSUE THREAD

**Issue by shake-spear** [WillyXJ/facileManager#555]
fM Version : v4.2.0
fmDHCP Version :  v0.5.0

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

show a list of leases given by DHCP server (call menu "Leases" / select a DHCP server)
(communication to client via ssh)

**(BUG | ISSUE) Actual Behavior:**

PHP Error is shown:
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function fm_dhcp_leases::displayRow(), 2 passed in /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_leases.php on line 86 and exactly 3 expected in /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_leases.php:122 Stack trace: #0 /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_leases.php(86): fm_dhcp_leases->displayRow('', Array) #1 /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_leases.php(202): fm_dhcp_leases->rows(Array) #2 /var/www/html/facileManager/fm-modules/fmDHCP/pages/leases.php(86): fm_dhcp_leases->getServerLeases('877658085') #3 /var/www/html/facileManager/index.php(57): include('/var/www/html/f...') #4 {main} thrown in /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_leases.php on line 122`

**(BUG | ISSUE) Steps to reproduce:**
call menu "Leases" / select a DHCP server

Problem can be solved by removing parameter $result from declaration of function displayRow():

current: function displayRow($ip, $lease, $result) { ...
works:   function displayRow($ip, $lease) { ...

**Comment by WillyXJ** [comment]
Are you able to provide a pull request?

**Comment by shake-spear** [comment]
> Are you able to provide a pull request?

I tried :) - hope I did everything the correct way

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.6.0](http://www.facilemanager.com/modules/fmdhcp/) and later.
