### ISSUE TITLE
[ISSUE] URL redirection not working

### ISSUE THREAD

**Issue by chandro** [WillyXJ/facileManager#559]
Hello, i have enabled the URL redirection on my panel, adding 2 ips from server i install to use as url-only.

facileManager v4.3.0
fmDNS v5.2.1

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.3.0**
<fmDNS> Version : **5.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
URL to be working, or redirected.

**(BUG | ISSUE) Actual Behavior:**
Not working, just poiting to url-only ip default page.

**(BUG | ISSUE) Steps to reproduce:**

When server was installed, it was added to Config > Servers but it has an error about method and run as, if you try to correct them it gives sql error problem.

i corrected them on the SQL directly, and when update a zone it shows like this:

; URL redirects
domain.wa.                 IN   A   78.my.url.only.ip

and when i enter the domain, it opens the IP and an apache image about "Apache2 Debian Default Page". not redirection being done. i am missing something?

**Comment by WillyXJ** [comment]
I could use more details to help with this issue.

1. How was the url-only server installed?  Through the UI or client installer?
2. What errors did you receive?
3. Was the configuration built on the url-only server?

**Comment by chandro** [comment]
Hello, i installed a new server using the same files, just on this step i did the url-only

php /usr/local/facilemanager/fmDNS/client.php install url-only

it do a apache2 check, about documentroot fixed in apache2.conf then it says is done.

when i add an URL on a zone in the panel it ask for reload the zone.

if i go to server list and check the config it shows like this.

19 ; URL redirects
20 muelles.bufalo.             180   IN   A   ip.23.ip.ip ; pagina bufalo
21 www.bufalo.                 180   IN   A   ip.23.ip.ip

is just an A redirection, and it shows the simple html page from server, doing nothing else.

**Comment by WillyXJ** [comment]
Are are the specs of your url server?  i.e. OS, PHP version, apache2 version
