### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by zsmith357** [WillyXJ/facileManager#560]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **X.X.X**
<Specify Module Name> Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [] I have checked that the issue I'm posting isn't already reported.
- [] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

**(BUG | ISSUE) Actual Behavior:**

**(BUG | ISSUE) Steps to reproduce:**

I enabled SSL redirect in "general" settings and now I can't access the GUI. from HTTP or HTTPS

**Comment by chandro** [comment]
at least you should complete what is needed to open a issue.

**Comment by chandro** [comment]
enter to your sql database go to table "fm_options" then find enforce_ssl, change it to "0" (zero)
