### ISSUE TITLE
[OTHER] LDAP auth in 4.3.0

### ISSUE THREAD

**Issue by sergor75** [WillyXJ/facileManager#565]
fM Version :  4.3.0
fmDNS Version : 5.2.1

I upgraded the fM server from version 4.1.1 to version 4.3.0 by unpacking the archive and moving the new facileManager/server directory to the /var/www/html/facileManager directory, connected via the web interface with the "super-admin" user and performed the schema upgrade DB.
After that, the interface of the new version normally opened.

However, I cannot connect with another user via LDAP, which I easily connected in version 4.1.1.

Here are the logs from the web server:

[Tue Nov 08 13:14:30.246056 2022] [php7:notice] [pid 13272] [client 10.232.9.42:65036] PHP Notice:  Undefined property: fmdb::$last_result in /var/www/html/facileManager/fm-modules/facileManager/classes/class_logins.php on line 262, referer: https://10.XXX.YYY.ZZZ/facileManager/
[Tue Nov 08 13:14:30.246080 2022] [php7:notice] [pid 13272] [client 10.232.9.42:65036] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/facileManager/fm-modules/facileManager/classes/class_logins.php on line 262, referer: https://10.XXX.YYY.ZZZ/facileManager/
[Tue Nov 08 13:14:30.246083 2022] [php7:notice] [pid 13272] [client 10.232.9.42:65036] PHP Notice:  Trying to get property 'user_login' of non-object in /var/www/html/facileManager/fm-modules/facileManager/classes/class_logins.php on line 262, referer: https://10.XXX.YYY.ZZZ/facileManager/
[Tue Nov 08 13:14:30.264936 2022] [php7:warn] [pid 13272] [client 10.232.9.42:65036] PHP Warning:  ldap_search(): Search: No such object in /var/www/html/facileManager/fm-modules/facileManager/classes/class_logins.php on line 676, referer: https://10.XXX.YYY.ZZZ/facileManager/

**Comment by sergor75** [comment]
[diff_output.txt](https://github.com/WillyXJ/facileManager/files/9960933/diff_output.txt)

**Comment by sergor75** [comment]
I checked the upgrade of fm 4.1.1 to fm 4.3.0 on CentOS 7.9 (I cloned the virtual machine from CentOS and upgraded it) -- the same error: I can't log in to the web interface of the new version as a user via LDAP, local super-admin user I connect normally.

**Comment by sergor75** [comment]
I try upgrade from fM 4.1.1 (LDAP logins worked OK)  to fM 4.2.0 and LDAP logins failed again

[Fri Nov 25 12:20:30.669016 2022] [php7:warn] [pid 23410] [client 10.XXX.YYY.NNN:51946] PHP Warning:  ldap_search(): Search: No such object in /var/www/html/facileManager/fm-modules/facileManager/classes/class_logins.php on line 676, referer: https://10.XXX.YYY.ZZZ/facileManager/

**Comment by WillyXJ** [comment]
If AD is being used (I have a notion it is), please try changing https://github.com/WillyXJ/facileManager/blob/master/server/fm-modules/facileManager/classes/class_logins.php#L569 to read:

`if (isset($ldap_group_search_dn) && !empty($ldap_group_search_dn)) {`

I think this will fix the problem, but I don't have a working AD environment to test with at the moment.

**Comment by sergor75** [comment]
Yes, i've Active Directory as my LDAP env.

I tried your patch and it works at least on version 4.2.0, TYVM

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.4.0](http://www.facilemanager.com/download/) and later.
