### ISSUE TITLE
GUI (initial configuration) not working 

### ISSUE THREAD

**Issue by sidantaa** [WillyXJ/facileManager#567]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.3.0**
FMDNS Version : **5.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

 I am unable to access GUi after setting all things such as apache , mysql etc installation. I am using ubuntu 22.04
 It just opens a white window with redirected url i.e. X.X.X.X/fm-install.php. I doubted this might be issue of php version 8.1 and also downgraded to 7.4 and tried accessing GUI ; the issue is still same. Please, help me and also do have a look at attached screenshot.

{replace this line with your issue content}
![fmdns-issue](https://user-images.githubusercontent.com/35427754/209428645-4ed917b1-92c5-426b-be94-8e06b3ef0ca9.png)

**Comment by adlp** [comment]
Have you any kind of log ? (because you have probably verify that your browser is not freeze ?)

**Comment by sidantaa** [comment]
> Have you any kind of log ? (because you have probably verify that your browser is not freeze ?)

I tried accessing from chrome browser too but it didn't worked. And i don't have any kind of logs. I got stucked at the very first step of configuration; unable to access GUI for database credential page and other installation steps.

**Comment by adlp** [comment]
What about your apache access and error logs ?!?

**Comment by sidantaa** [comment]
> What about your apache access and error logs ?

Thank you @adlp sir for guiding me towards log section. There is one error log mentioned below. Please, assist me on this.


[Sat Dec 24 17:27:44.595454 2022] [proxy_fcgi:error] [pid 4523] [client 10.35.35.16:52379] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: sort(): Argument #1 ($array) must be of type array, null given in /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php:109\nStack trace:\n#0 /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php(109): sort()\n#1 /var/www/html/dnsadmin/fm-modules/facileManager/functions.php(71): include('...')\n#2 /var/www/html/dnsadmin/fm-includes/init.php(30): require_once('...')\n#3 /var/www/html/dnsadmin/fm-install.php(47): require_once('...')\n#4 {main}\n  thrown in /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php on line 109'

**Comment by adlp** [comment]
So !
FacileManager need OLD php release : No php 8. (I'm not able to find where I get this information, but you may find this one in the issue. You can participate too, to make FacileManager running under php8 !)
At this time my FacileManager environement user php 7.4.28.
But, with  7.4 It may not work in your environement but not with the same error than now.

Have a nice evening ;)

**Comment by sidantaa** [comment]
> So ! FacileManager need OLD php release : No php 8. (I'm not able to find where I get this information, but you may find this one in the issue. You can participate too, to make FacileManager running under php8 !) At this time my FacileManager environement user php 7.4.28. But, with 7.4 It may not work in your environement but not with the same error than now.
> 
> Have a nice evening ;)

Hi,

Thanks for the information. I was guessing the same thing regarding PHP versions but even though i downgrade to 7.4, it didn't worked for me. I don't know the actual cause.

**Comment by adlp** [comment]
Issue #558 say : no php8.1
Please, before opening issue read other issues ( Hey in the begining of you issue, 4th box ;) )

And never forget to read you logs.

**Comment by sidantaa** [comment]
> Issue #558 say : no php8.1 Please, before opening issue read other issues ( Hey in the begining of you issue, 4th box ;) )
> 
> And never forget to read you logs.

Sorry. I again downgraded to 7.4 but no luck. Same error again:

[Sat Dec 24 20:06:00.764691 2022] [proxy_fcgi:error] [pid 9292] [client 10.35.35.16:52270] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: sort(): Argument #1 ($array) must be of type array, null given in /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php:109\nStack trace:\n#0 /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php(109): sort()\n#1 /var/www/html/dnsadmin/fm-modules/facileManager/functions.php(71): include('...')\n#2 /var/www/html/dnsadmin/fm-includes/init.php(30): require_once('...')\n#3 /var/www/html/dnsadmin/fm-install.php(47): require_once('...')\n#4 {main}\n  thrown in /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php on line 109'

**Comment by adlp** [comment]
You keep exactly the same error.
So, IMHO, you have keep the same version.
Several way to control 
  * Verify wich php apache call in his module
  * Verify wich php packages (en version) a reinstalled on your machine
  * Use the function phpinfo()
But I'm sure that all thoses test have been done...

**Comment by sidantaa** [comment]
> You keep exactly the same error. So, IMHO, you have keep the same version. Several way to control
> 
>     * Verify wich php apache call in his module
> 
>     * Verify wich php packages (en version) a reinstalled on your machine
> 
>     * Use the function phpinfo()
>       But I'm sure that all thoses test have been done...

Thanks, I go it now. There were several php alternatives. So, i removed everything related to php.* and again reinstalled the version 7.4.33 and now everything is working. Thank you so much
