### ISSUE TITLE
[FEATURE REQUEST]  dnssec-policy

### ISSUE THREAD

**Issue by oiLvAcciNe** [WillyXJ/facileManager#568]
fM Version : 4.3.0
fmDNS Version : 5.2.1

---
Can't seem to configure dnssec-policy in fmDNS.

BInd Feature Changes
_"The auto-dnssec option has been deprecated and will be removed in a future BIND 9.19.x release. 
Please migrate to dnssec-policy. [GL #3667]"_

https://kb.isc.org/docs/dnssec-key-and-signing-policy

**Comment by WillyXJ** [comment]
Thanks for bringing this up.

https://bind9.readthedocs.io/en/v9_18_8/reference.html#namedconf-statement-dnssec-policy will be used/referenced during development to support this feature.

**Comment by internethering** [comment]
I get this issue too, please fix

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.  However, at this time only internal policies are supported. Defining custom policies is targeted for 6.1.0.

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 6.1.0](http://www.facilemanager.com/modules/fmdns/) and later.
