### ISSUE TITLE
ISSUE: FacileManager Performance / fmDNS / as restricted user

### ISSUE THREAD

**Issue by am155** [WillyXJ/facileManager#569]
fM Version : **4.3.0**
fmDNS Version : **5.2.1**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
---

**ISSUE Expected Behavior:**
Loading the fmsDNS page (Dashboard or Zones section) as a Admin user takes 0,5 - 1 sec. 

**ISSUE Actual Behavior:**
If you create a user (non admin) with resticted Domain access ( 5 out of 421 ) and restricted user rights it will take 5 - 10 sec. per page to display.
Adding this user to the Admin Group will increase performance to  0,5 - 1 sec until the page is loaded.

**ISSUE Steps to reproduce:**
![Bildschirm­foto 2023-01-26 um 12 16 51](https://user-images.githubusercontent.com/6449883/214823027-ec943895-987d-47c4-b44e-c8fb30786bcd.jpg)

Already checked the Apache2 and Nginx log files for errors. Could not find any issue.

Backend FacileManager runs on a Ubuntu 20.04.5 LTS virtualized platform.

Thanks,
Andreas

**Comment by WillyXJ** [comment]
So far I am unable to reproduce this problem.  I've created 450 zones based on a template, created a user, created a user group, and restricted the group to five of the zones.  Are there any other details you can provide to help reproduce this performance issue?

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1309591/218574761-c4fe0154-a738-4c7d-9e60-778773c15255.png">

**Comment by am155** [comment]
Please do create a Group of domain within the Zones sektion and add 3 domains to this group.
Within your test-group do not add the domain individually, but as a zone group.

As soon as you are using a Zone-Group for that test-user, the performance is degraded !!!

**Comment by WillyXJ** [comment]
I created a zone group with three of the 450 zones, associated it with the user group, and associated my test user with the user group.  I'm still not seeing any performance degradation when logging in as the test user and managing the zone data.  My current test fM environment consists of:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

~$ apache2 -v
Server version: Apache/2.4.55 (Ubuntu)
Server built:   2023-01-19T19:55:14

~$ php -v
PHP 8.2.2 (cli) (built: Feb  7 2023 11:28:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.2, Copyright (c), by Zend Technologies

~$ mysql -V
mysql  Ver 15.1 Distrib 10.3.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
