### ISSUE TITLE
fmDNS: Create PTR doesn't work

### ISSUE THREAD

**Issue by millallo** [WillyXJ/facileManager#573]
If you create an A record with the 'Create PTR' flag, the sql insert of the PTR record into its reverse zone fails.
I noticed that in the 'Add Record' form the 'record class' field is neither present nor hidden. This absence is carried forward to the zone-records-validate.php page and then to the zone-records-write.php where the insert fails. The sql error is not reported and everything seems to have gone well but no PTR records have been added.
I temporarily fixed it by commenting this line which causes mariadb to insert the default value 'IN' for the 'record_class' field.

https://github.com/WillyXJ/facileManager/blob/dac516d1d6f2b16a2b80d8cbb2c3fff5c516d474/server/fm-modules/fmDNS/pages/zone-records-write.php#L190

This is the sql error:
``
INSERT INTO fm_dns_records (domain_id, record_type, record_name, record_ttl, record_class, record_value, record_comment, account_id) VALUES (278, 'PTR', '6', '', '', 'snm6.test.org.', '', '1');
ERROR 1265 (01000): Data truncated for column 'record_class' at row 1
``

fmDNS: 5.2.1
MariaDB: 10.5.18
PHP: 7.4.33
OS: Debian 11

**Comment by WillyXJ** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.3.1](http://www.facilemanager.com/modules/fmdns/) and later.
