### ISSUE TITLE
[BUG] fmDNS: Can't add more than 4 A records

### ISSUE THREAD

**Issue by millallo** [WillyXJ/facileManager#575]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : 4.3.0
fmDNS Version : 5.3.1

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
I would like to add more than 4 A records in a zone

**(BUG | ISSUE) Actual Behavior:**
Only last 4 records in the 'Add Records' block are validated

**(BUG | ISSUE) Steps to reproduce:**
Add 5 records to the 'Add Records' form and validate them, only the last 1 record is validated.

I think this commit broke the correct behaviour:
https://github.com/WillyXJ/facileManager/commit/34774b680e6c3fa14f7866f0c5f74ebb19131e49

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 5.3.2](http://www.facilemanager.com/modules/fmdns/) and later.
