### ISSUE TITLE
[BUG] SOA of reverse zone not updated after A record deletion

### ISSUE THREAD

**Issue by millallo** [WillyXJ/facileManager#580]
fM Version : 4.5.0
fmDNS: v5.3.3 
- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
The deletion of an A record with linked PTR, should trigger SOA update of the reverse zone and the reload config hint.

**(BUG | ISSUE) Actual Behavior:**
The deletion of an A record with linked PTR, deletes A and PTR records correctly, but updates only the SOA of the forward zone. 

**(BUG | ISSUE) Steps to reproduce:**
Create an A record with 'Create PTR' checkbox and deploy new configuration.
Delete the A record just created.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
