### ISSUE TITLE
Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated

### ISSUE THREAD

**Issue by gianlucagiacometti** [WillyXJ/facileManager#583]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].
(I suggest to add something for these cases, like DEPRECATED or PHP-ALERT, since it's neither a bug nor a real issue)

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.5.0**
fmDNS Version : **5.3.4**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---
I'm using Ubuntu 22.04 with PHP 8.1

Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in /web/sites/dns.isqweb.it/public/fm-modules/fmDNS/classes/class_buildconf.php on line 2018

**Comment by sergor75** [comment]
I confirm, I also saw similar messages on the same software versions
<img width="796" alt="fM_4 5 0_err2018" src="https://github.com/WillyXJ/facileManager/assets/90454573/91dc3d19-d08a-4d94-b7cf-9acbbd861fdd">
This message hangs and is not removed, if you close the browser tab and restart, you can see that the config building is successful

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
