### ISSUE TITLE
[OTHER] Updated GitHub releases

### ISSUE THREAD

**Issue by edvalley** [WillyXJ/facileManager#584]
Can you please provide updated GitHub releases? It would be great, but even a plain directory listing will work for me. I use fM in a network without Internet access. I need a way to detect new releases (latest version) to automate downloading them. Even if parsing HTML from www.facilemanager.com, downloads have no timestamp (no last-modified header) to use to avoid downloading the same file over and over again. Thank you very much.

**Comment by WillyXJ** [comment]
The current version has now been added as a release.  I forget to create Github releases about 97% of the time.  Since the app is on www.facilemanager.com, it simply has not been in my release workflow.  I'll try to incorporate it better.

**Comment by edvalley** [comment]
Thank you!
