### ISSUE TITLE
[ISSUE] New Installation - Error "Failed to load resource [...] /fm-modules/facileManager/js/facileManager.php?ver=4.5.0"

### ISSUE THREAD

**Issue by vaenner-net** [WillyXJ/facileManager#586]
Hi, 

I installed facileManager from this Github repo (Master) on a fresh FreeBSD 13.2 installation with 
* apache24
* mysql80
* php82

Initial set-up works fine until step 4 (super-user). This dialog I am not able to submit. Nothing seems to happen.

The developer consoles of Safari (version 16.6) and Firefox (version 117) give some hints: Both show the error message in the title. Firefox even gives some more information:

"This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [fm-install.php](http://1.2.3.4/fm-install.php?step=6)
Loading failed for the <script> with source “http://1.2.3.4/fm-modules/facileManager/js/facileManager.php?ver=4.5.0”. [fm-install.php:18:112](http://10.200.0.9/fm-install.php?step=6)"

Any tips on how to solve that?

Thanks & Best regards,
  Mark

**Comment by WillyXJ** [comment]
This looks like it's coming from the jquery version used by fM and your web browser is preventing it.  Odd issue and so far I'm unable to reproduce it with Safari 17 or Chrome 117.
