### ISSUE TITLE
PHP 7.4 is End-Of-Life

### ISSUE THREAD

**Issue by internethering** [WillyXJ/facileManager#587]
please release a php 8 compatible release. php 7.4 is EOL and got dropped from various linux distributions like gentoo. this is a critical bug now ;)

**Comment by WillyXJ** [comment]
#558 - PHP8 compatible version was released over a year ago.

**Comment by internethering** [comment]
ah ok. may updating the frontpage? this says -7.4 ;)

**Comment by WillyXJ** [comment]
Oops. :) Thanks and updated.
