### ISSUE TITLE
[BUG] Password reset can inadvertently expose email address

### ISSUE THREAD

**Issue by drdelaney** [WillyXJ/facileManager#592]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.5.0**
fmDNS Version : **5.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:** Display generic message, like it does for an invalid user to not expose a user or email

**(BUG | ISSUE) Actual Behavior:** Displays email address for the user if valid, report issue to logs instead, or maybe throw a generic SMTP error up for the user (maybe for all users even if invalid, otherwise this can be used to verify valid accounts)

**(BUG | ISSUE) Steps to reproduce:** Break your email setup so messages will not be relayed.

When trying to reset my password for my admin, I noticed it would say it sent me an email when the user was invalid (should probably say email will be sent if user is valid, but that is out of scope for this issue)

But when I used a valid user, but with SMTP broken, I got the following:

Mailer Error: SMTP Error: The following recipients failed: myvalid@email.here
SMTP server error: 4.7.1 : Relay access denied

**Comment by WillyXJ** [comment]
Thanks for the report. Since fM uses PHPMailer and the errors come from that class, the next version will contain a fix to hide mailing errors unless the "Show Errors" setting is enabled.

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.6.0](http://www.facilemanager.com/download/) and later.
