### ISSUE TITLE
can't change my superadmin password

### ISSUE THREAD

**Issue by internethering** [WillyXJ/facileManager#595]
hello, I've only one account with superadmin rights and I use builtin authentification. But when I want to change my password, it says: "Sie sind nicht berechtigt, diese Änderungen vorzunehmen." - what?

**Comment by WillyXJ** [comment]
I can change the admin password all day long. Please fill out the new issue form so I know how to reproduce this.

**Comment by internethering** [comment]
using password rest function helped me
