### ISSUE TITLE
[ISSUE] DNS Server Not Updating for large amount of records

### ISSUE THREAD

**Issue by generobruno** [WillyXJ/facileManager#597]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.5.0**
fM DNS Version : **5.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Hi. I am trying to upload a big amount of PTR records to the master DNS server that i am managing (i.e: 65000 records).

**(BUG | ISSUE) Actual Behavior:**
The records are correctly uploaded to the database using the webserver, however, once i try to build the config of the Master DNS server, the records of the given zone don't get updated.

**(BUG | ISSUE) Steps to reproduce:**
First i upload the records using either the zone import tool, or directly to the database using a sql script. Then i build the config of the server using the web GUI. After that i can either wait for the crontab to update my server or do it manually using the command "/bin/php /usr/local/facileManager/fmDNS/client.php cron debug" (with "error_reporting(E_ALL);"). 
I tried uploading the records in chunks, but the server stops updating at around 40k records.

**Comment by WillyXJ** [comment]
This sounds similar to #585.

**Comment by generobruno** [comment]
Yes, i've already changed the .htaccess file with the following and still have the same problem:

php_value post_max_size 100M
php_value upload_max_filesize 100M
php_value max_input_vars 2000400
php_value max_execution_time 3600
php_value max_input_time 3600

**Comment by generobruno** [comment]
I checked the server error logs and found the following:

```
[Fri Jan 05 08:20:22.941121 2024] [php:error] [pid 111822] [client 172.23.32.109:28676] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/dnsadmin/fm-modules/fmDNS/classes/class_buildconf.php on line 1345
```

So i was able to make it work by increasing the php memory limit in the script "class_buildconf.php" (using ini_set('memory_limit', '256M'); ). I also had to do this to the scripts "zones-reverse.php" and "zone-records-validate.php" when i tried to modify one of the records in these large zone files.

**Comment by WillyXJ** [comment]
I would think adding the php_value to .htaccess would work so you don't have to modify the php files themselves.

**Comment by generobruno** [comment]
Yes, that also works fine. Thanks.
