### ISSUE TITLE
[ISSUE] You do not have permission to make these changes

### ISSUE THREAD

**Issue by PbIC9TuHa** [WillyXJ/facileManager#598]
[ISSUE]

 
fM Version : **v4.5.0**
fmDNS Version : **v5.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**After creating a user, it is not possible to change the user's permissions
![image](https://github.com/WillyXJ/facileManager/assets/38468357/fd750872-892c-488a-a21a-b659f608d795)
If I want to grant additional permissions, the system gives a message (even to Super admin)
![image](https://github.com/WillyXJ/facileManager/assets/38468357/bee7522d-5a53-4077-8aec-17e8e83e6a1d)**

**Comment by PbIC9TuHa** [comment]
Doesn't anyone have this problem? I've reinstalled everything 5 times already and the problem persists

**Comment by WillyXJ** [comment]
What are your exact steps to reproduce this issue? I'm currently unable to reproduce it in my lab or production systems.

**Comment by PbIC9TuHa** [comment]
Problem solved. updated PHP to version 8.1 and everything solved by itself

**Comment by PbIC9TuHa** [comment]
Problem solved

**Comment by PbIC9TuHa** [comment]
updated PHP to version 8.1
