### ISSUE TITLE
Several Security Issues Identified

### ISSUE THREAD

**Issue by jmrcsnchz** [WillyXJ/facileManager#599]
[SECURITY]

## Security Issues

Hi, we are a group of security consultants / researchers and we've identified a number of security issues in this project (ranging from SQL injection, XSS, to Account Privilege Escalation). We would like to disclose these vulnerabilities responsibly and we're hoping to get in touch with the repo maintainer. Please don't hesitate to reach out via my [email](mailto:jmsanchez275@gmail.com). Thanks!

**Comment by WillyXJ** [comment]
Thanks for the report!

This is now fixed in [fM 4.5.1](http://www.facilemanager.com/download/) and later.

**Comment by jmrcsnchz** [comment]
Hi! Nice work for the very quick fixes. May I ask if you requested CVE for
them?

**Comment by WillyXJ** [comment]
Yes, I did request CVEs for each of them. Expectations are to have assignments later this week.
