### ISSUE TITLE
[BUG] Adding DNS records via api is broken on PHP8.1

### ISSUE THREAD

**Issue by ValeriiVozniuk** [WillyXJ/facileManager#600]
fM Version : **4.5.0**
fmDNS Version : **5.3.3**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
I'm able to create a DNS record via api call

**(BUG | ISSUE) Actual Behavior:**
Script silently finishes

**(BUG | ISSUE) Steps to reproduce:**
Try to add a DNS record via console, for example
php /usr/local/facileManager/fmDNS/client.php setHost id=10 action=add type=A name=www value=172.10.33.1 status=active

The issue is in https://github.com/WillyXJ/facileManager/blob/master/client/facileManager/fmDNS/client.php#L82, function call_user_func_array
https://www.php.net/manual/en/function.call-user-func-array.php
```
8.0.0 | args keys will now be interpreted as parameter names, instead of being silently ignored.
```
changing the line to `call_user_func_array('array_merge', array_values($api_params))` seems fixes the issue, but I'm not sure if this is matches the code intentions/correct way to fix it.

PS: there is another call to this function in https://github.com/WillyXJ/facileManager/blob/master/server/fm-modules/facileManager/classes/class.phpmailer.php#L2934, and it may need to be fixed too.

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
