### ISSUE TITLE
[FEATURE REQUEST] Display View name in UI when editing domain records

### ISSUE THREAD

**Issue by ValeriiVozniuk** [WillyXJ/facileManager#602]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.5.0**
fmDNS Version : **5.3.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---
It would be nice to have Bind View name(s) displayed in UI after the domain if they are defined. Like "Domain:   dns-demo.com (Views: us_dc, apac_dc)" or "Domain:   dns-demo-a.com (All Views)".
![image](https://github.com/WillyXJ/facileManager/assets/44667626/dab8773d-905d-430d-ab04-c822b9ba43db)
Usually you open the domain knowing which views it serves, but sometimes you can be distracted with other task or request. And when you returns, you may not remember which view you've opened, so you need to go back to the domains UI and see what that domain was. Having view information directly in UI would eliminate such additional actions :).

**Comment by WillyXJ** [comment]
This is now added in [fmDNS 6.0.0](http://www.facilemanager.com/modules/fmdns/) and later.
