### ISSUE TITLE
[ISSUE] Debugging facileManager/fmDNS sometimes break applying changes in client.php

### ISSUE THREAD

**Issue by ValeriiVozniuk** [WillyXJ/facileManager#603]
fM Version : **4.5.0**
fmDNS Version Version : **5.3.3**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Adding correct debug statements to fM/fmDNS code is not breaking its functioning

**(BUG | ISSUE) Actual Behavior:**
Some statements could break gzip encoding leading to errors like
`PHP Warning:  gzuncompress(): data error in /usr/local/facileManager/fmDNS/functions.php on line 126`

**(BUG | ISSUE) Steps to reproduce:**
I don't have solid steps, because it happened somewhere in the middle of debugging. I've narrowed down the source of the issue to behavior described here
https://stackoverflow.com/questions/15578271/apache-or-php-generating-prepending-line-feed-character
After checking curl_exec output in https://github.com/WillyXJ/facileManager/blob/master/client/facileManager/functions.php#L489 and comparing it to the sent data, I indeed found an extra newline in curl_exec output.

**Proposed fix**: change https://github.com/WillyXJ/facileManager/blob/master/client/facileManager/functions.php#L494 from
```
return $result;
```
to
```
return ltrim($result);
```
It would remove the starting newline which is breaking gzuncompress() call. Testing this on clean deployment showed no regressions.
Calling full trim() function, on other hand, breaking the output too. Thus calling ltrim() is right way to fix :).

**Comment by WillyXJ** [comment]
Can you submit a pull request for this?

**Comment by ValeriiVozniuk** [comment]
Like this?
https://github.com/WillyXJ/facileManager/pull/606

**Comment by WillyXJ** [comment]
PR replaces this issue.
