### ISSUE TITLE
[FEATURE REQUEST] Fully automated client install

### ISSUE THREAD

**Issue by ValeriiVozniuk** [WillyXJ/facileManager#605]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.5.0**
fmDNS Version : **5.3.3**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Be able to run `php /usr/local/facileManager/fmDNS/client.php install` from automated scripts

**(BUG | ISSUE) Actual Behavior:**
There is a prompt for `get updates via cron, ssh, or http(s) [c|s|h]?`

**(BUG | ISSUE) Steps to reproduce:**
1. Deploy config.inc.php file with proper content for node connection.
2. Run `php /usr/local/facileManager/fmDNS/client.php install`
3. Expect to have node installed automatically, but got input prompt.

Per what I see the issue comes from https://github.com/WillyXJ/facileManager/blob/master/client/facileManager/functions.php#L811 having $update_method = null, and not taking it from DEFINEs in config.inc.php. It would be nice to have this parameter present in config too.

{replace this line with your issue content}

**Comment by WillyXJ** [comment]
I think the prompt is something that could be done as a CLI parameter and should be simple to implement.

**Comment by WillyXJ** [comment]
This is now implemented in [fM 4.7.0](http://www.facilemanager.com/download/) and later.
