### ISSUE TITLE
[BUG] Client function.php, processUpdateMethod function definition is using deprecated form

### ISSUE THREAD

**Issue by racribeiro** [WillyXJ/facileManager#608]
fM Version : **4.5.1**
core Version : **4.5.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

When action over client, it should perform the action.

**(BUG | ISSUE) Actual Behavior:**

The message "It appears %s does not have php configured properly within httpd or httpd is not running." is presented

**(BUG | ISSUE) Steps to reproduce:**

Using PHP 8, the request fails because function processUpdateMethod is defined as:

function processUpdateMethod($module_name, $update_method = null, $data, $url)

and should be defined as:

function processUpdateMethod($module_name, $update_method = null, $data = [], $url = "")

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.6.0](http://www.facilemanager.com/download/) and later.
