### ISSUE TITLE
[ISSUE] Zone reload php-warning appear BUT zone does not reload

### ISSUE THREAD

**Issue by sergor75** [WillyXJ/facileManager#610]
fM Version : 4.6.0
fM DNS Version : 6.0.1

Today I updated my test installation (fm server and client) to version 4.6.0

I change the TTL of an arbitrary entry in one of the zones, reload the zone - a warning window appears (see attachments), but the zone is not reloaded and updates do not arrive to the client
<img width="960" alt="fm_4 6 0_zone_reload_warning" src="https://github.com/WillyXJ/facileManager/assets/90454573/78ff25e1-8a6a-4a9b-8b0d-75b653205232">
<img width="637" alt="fm_4 6 0_zone_reload_warning2" src="https://github.com/WillyXJ/facileManager/assets/90454573/4452fe82-2ab2-4f70-8310-2574085aa470">

**Comment by sergor75** [comment]
![image](https://github.com/WillyXJ/facileManager/assets/90454573/fb556b74-e191-41a2-9a4c-6e64a72cd472)

**Comment by WillyXJ** [comment]
Are you using server groups for that zone?

**Comment by WillyXJ** [comment]
If you use server groups, the fix will be to replace https://github.com/WillyXJ/facileManager/blob/0017d8c885c064f33cda8a26b035a1b015a0288c/server/fm-modules/fmDNS/classes/class_zones.php#L1369 with 

`		$name_servers = $this->getNameServers($domain_name_servers, array('masters'));`

This will be included in the next release. If server groups are not being used then I'll need to find a different solution.

**Comment by sergor75** [comment]
yes, this fix helped, thank you very much

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.2](http://www.facilemanager.com/modules/fmdns/) and later.
