### ISSUE TITLE
[BUG] PHP 8.2 str_replace() deprecation warning in config build

### ISSUE THREAD

**Issue by imyller** [WillyXJ/facileManager#612]
fM Version : **4.6.1**
fmDNS Version : **6.0.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

* Build server config with named checks enabled in settings and configured in client
* Enable `Show errors` in settings
* `Server reload successful` response from all servers

**(BUG | ISSUE) Actual Behavior:**

`
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/facileManager/fm-modules/fmDNS/classes/class_buildconf.php on line 1083
`

<img width="1152" alt="fmdns-deprecated" src="https://github.com/WillyXJ/facileManager/assets/1898870/782cdb6a-4f57-49a5-8957-7cdf4ec0bcb3">

**(BUG | ISSUE) Steps to reproduce:**

* Debian 12 (Bookworm)
* PHP 8.2.7
* Apache 2.4.57
* Install server and client
* Configure client sudoers to allow calling of ´named-checkconf´ and ´named-checkzone´ 
* Enable `Show errors` in settings
* Enable bamed checks in fmDNS settings
* Build config

**(BUG | ISSUE) Workaround:**

* Disable `Show errors` in settings

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.4](http://www.facilemanager.com/modules/fmdns/) and later.
