### ISSUE TITLE
[BUG] Create PTR option causes fatal error: Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by imyller** [WillyXJ/facileManager#613]
fM Version : **4.6.1**
fmDNS Version : **6.0.3**

* Debian 12 (Bookworm)
* PHP 8.2.7
* Apache 2.4.57

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Operation succeeeds and forward A record is created.

(If reverse zone is not already created it can either be created or `Create PTR` option will be ignored with warning?)

**(BUG | ISSUE) Actual Behavior:**

* `Create PTR` option checked for A record
* No manually created reverse zone
* Server responds with http/500:

`Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/facileManager/fm-modules/fmDNS/classes/class_zones.php:1850 Stack trace: #0 /var/www/facileManager/fm-modules/fmDNS/classes/class_zones.php(126): fm_dns_zones->validatePost() #1 /var/www/facileManager/fm-modules/fmDNS/functions.php(1312): fm_dns_zones->add() #2 /var/www/facileManager/fm-modules/fmDNS/functions.php(1272): autoCreatePTRZone() #3 /var/www/facileManager/fm-modules/fmDNS/pages/zone-records-validate.php(250): checkPTRZone() #4 /var/www/facileManager/fm-modules/fmDNS/pages/zone-records-validate.php(141): validateEntry() #5 /var/www/facileManager/fm-modules/fmDNS/pages/zone-records-validate.php(69): createOutput() #6 /var/www/facileManager/index.php(57): include('...') #7 {main} thrown in /var/www/facileManager/fm-modules/fmDNS/classes/class_zones.php on line 1850`

**(BUG | ISSUE) Steps to reproduce:**

* Enable `Show errors` in settings
* Create forward zone (e.g. example.com)
* Do NOT create reverse zone for IP (e.g 10.in-addr.arpa.)
* Try to create A record (e.g. test A 10.0.0.0) with `Create PTR` option checked
* http/500 error from server

(without `Show errors` setting, UI responds with blank page and silent http/500)

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.4](http://www.facilemanager.com/modules/fmdns/) and later.
