### ISSUE TITLE
[BUG] API not working with PHP > 8

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#614]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.1.1**
fmDNS Version : **5.1.0**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---
I try to use on client:
`php /usr/local/facileManager/fmDNS/client.php setHost id=4 action=add type=TXT name=test232 value=some_thing`

**(BUG | ISSUE) Expected Behavior:**
The record is changing.

**(BUG | ISSUE) Actual Behavior:**
Nothing.

**(BUG | ISSUE) Steps to reproduce:**
This worked in php 7.2.4
But does not work in php 8.0 or 8.1.14.
Research has shown that the **call_user_func_array** function in php 8 works differently compared to php 7 and does not work in a file /usr/local/facileManager/fmDNS/client.php.

**Comment by beza2000** [comment]
Fixed in fmDNS 6.0

**Comment by WillyXJ** [comment]
PHP 8 support was added in fM 4.4.0 and fmDNS 5.3.0.
