### ISSUE TITLE
[BUG] PHP deprecation warning when editing zone without NS records

### ISSUE THREAD

**Issue by imyller** [WillyXJ/facileManager#616]
fM Version : **4.6.1**
fmDNS Version : **6.0.3**

* Debian 12 (Bookworm)
* PHP 8.2.7
* Apache 2.4.57

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Zone is opened for edit with warning, but without PHP deprecation error.

**(BUG | ISSUE) Actual Behavior:**

`Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/facileManager/fm-modules/fmDNS/classes/class_records.php on line 922`

<img width="1107" alt="phpdepreditzone" src="https://github.com/WillyXJ/facileManager/assets/1898870/9b66a2cd-f90a-4f83-b2c4-7113b6b07ce2">

**(BUG | ISSUE) Steps to reproduce:**

* Enable `Show errors` in settings
* Open zone for editing (without active name servers)
* PHP deprecation warning and normal nameserver warning error pops up

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.4](http://www.facilemanager.com/modules/fmdns/) and later.
