### ISSUE TITLE
[BUG] Uncaught TypeError when adding new group

### ISSUE THREAD

**Issue by imyller** [WillyXJ/facileManager#621]
fM Version : **4.6.1**
fmDNS Version : **6.0.4**

Debian 12 (Bookworm)
PHP 8.2.7
Apache 2.4.57

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Group add dialog opens without error.

**(BUG | ISSUE) Actual Behavior:**

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /opt/facileManager/server/fm-modules/facileManager/functions.php:873 Stack trace: #0 /opt/facileManager/server/fm-modules/facileManager/classes/class_users.php(705): buildSelect() #1 /opt/facileManager/server/fm-modules/facileManager/ajax/getData.php(103): fm_users->printUsersForm() #2 {main} thrown in /opt/facileManager/server/fm-modules/facileManager/functions.php on line 873`

<img width="1091" alt="grouptyperr" src="https://github.com/WillyXJ/facileManager/assets/1898870/142f8da1-5b3c-4ce7-a4e1-2b1f4d95c90e">

**(BUG | ISSUE) Steps to reproduce:**

* Fresh installation
* Go to Users/Groups
* Go to Groups
* Click `Add new`
* Fatal PHP error is displayed

**Comment by WillyXJ** [comment]
Thanks for the report. This happens because there are no additional users created yet. As a workaround, create a new user first (it can even be in a disabled state).

**Comment by WillyXJ** [comment]
This is now fixed in [fM 4.6.2](http://www.facilemanager.com/download/) and later.
