### ISSUE TITLE
[BUG] [] operator not supported for strings[] in Edit Zone

### ISSUE THREAD

**Issue by imyller** [WillyXJ/facileManager#622]
fM Version : **4.6.1**
fmDNS Version : **6.0.4**

Debian 12 (Bookworm)
PHP 8.2.7
Apache 2.4.57

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

When editing zone configuration the edits are saved.

**(BUG | ISSUE) Actual Behavior:**

`Fatal error: Uncaught Error: [] operator not supported for strings in /opt/facileManager/server/fm-modules/fmDNS/functions.php:694 Stack trace: #0 /opt/facileManager/server/fm-modules/fmDNS/classes/class_zones.php(461): getZoneServers() #1 /opt/facileManager/server/fm-modules/fmDNS/pages/zones.php(61): fm_dns_zones->update() #2 /opt/facileManager/server/fm-modules/fmDNS/pages/zones-forward.php(27): include('...') #3 /opt/facileManager/server/index.php(57): include('...') #4 {main} thrown in /opt/facileManager/server/fm-modules/fmDNS/functions.php on line 694`

Click `Save`:

<img width="1166" alt="editzonerr" src="https://github.com/WillyXJ/facileManager/assets/1898870/a5253660-6e1d-4f0a-abbf-3c6750e05f65">

Results in:

<img width="1073" alt="editzoneerr2" src="https://github.com/WillyXJ/facileManager/assets/1898870/bceb946c-185a-404f-86a9-583a0fd91518">

**(BUG | ISSUE) Steps to reproduce:**

* Fresh installation
* Create server group with single server (e.g. `public`)
* Edit zone
* Assign zone DNS servers to created server group
* Save
* Edit zone (again)
* Save
* Fatal PHP error is displayed 

**NOTE:** I am not sure if the server group assignment is required to trigger this bug, but I was able to get the issue to appear after `Save` in Edit Zone worked first when changing zone's DNS server assignment from `All servers` to a newly created server group and then failed for subsequent edits.

**Comment by internethering** [comment]
change fm-modules/fmDNS/functions.php line 677: `$serial_no = array();`

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.5](http://www.facilemanager.com/modules/fmdns/) and later.
