### ISSUE TITLE
[BUG] Secondary zone from Windows DNS server

### ISSUE THREAD

**Issue by VN1977** [WillyXJ/facileManager#627]
fM Version : **4.6.1**
fMDNS Version : **6.0.4**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

We have Windows DNS server with primary zone. If we use usual pure BIND we can add slave zone pointing to that DNS server and everything works good. I could not find info how to do the same via fM. I added remote server but cannot choose it as master server during creating a new zone.
Maybe it is unsupported configuration?

**Comment by WillyXJ** [comment]
Thanks for the bug report. This will be fixed in the next release. If you need a fix sooner, you can change https://github.com/WillyXJ/facileManager/blob/fefedaf4d16f17572cd4feb99664ce0786b904a1/server/fm-modules/fmDNS/js/module.php#L366

From:

		} else if ($(this).val() == "slave" || $(this).val() == "stub") {
		
To:

		} else if ($(this).val() == "secondary" || $(this).val() == "stub") {
