### ISSUE TITLE
[BUG] peer address of failover peer is generated as FQDN/Name not IP-Address

### ISSUE THREAD

**Issue by shake-spear** [WillyXJ/facileManager#628]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.6.2**
fmDHCP Version : ** v0.8.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

If a peer group has been defined and hostnames of servers are resolvable (tested) or IP-Addresses of Servers have been entered (tested too) in server definition a config with ip addresses of peers should be generated:

 ## peer items ##
  failover peer "mypeers" {
  	primary;
  	address 1.2.3.4;
  	port 519;
  	peer address 1.2.3.5;
  	peer port 520;
  	split 256;
  	mclt 3600;
  	max-response-delay 60;
  	max-unacked-updates 10;
  	load balance max seconds 5;
 }

AND

 ## peer items ##
  failover peer "mypeers" {
  	secondary;
   	peer address 1.2.3.4;
  	peer port 519;
  	address 1.2.3.5;
  	port 520;
  	max-response-delay 60;
  	max-unacked-updates 10;
  	load balance max seconds 5;
 }

**(BUG | ISSUE) Actual Behavior:**

 ## peer items ##
  failover peer "mypeers" {
  	primary;
  	address  <FQDN 1>;
  	port 519;
  	peer address  <FQDN 2>;
  	peer port 520;
  	split 256;
  	mclt 3600;
  	max-response-delay 60;
  	max-unacked-updates 10;
  	load balance max seconds 5;
 }

AND

 ## peer items ##
  failover peer "mypeers" {
  	secondary;
   	peer address  <FQDN 1>;
  	peer port 519;
  	address  <FQDN 2>;
  	port 520;
  	max-response-delay 60;
  	max-unacked-updates 10;
  	load balance max seconds 5;
 }

**(BUG | ISSUE) Steps to reproduce:**

- define 2 DHCP Servers
- generate a failover peer group names "mypeers"
- add one server as primary the other as secondary
- generate config
- add IP-Adresses to both servers in server definition
- generate config 

{replace this line with your issue content}

**Comment by WillyXJ** [comment]
If the names are resolvable then the configuration will use the names regardless if the IP address field is populated. Based on the information you've provided, this is functioning as designed.  Please clarify the issue if that's not the case.

**Comment by shake-spear** [comment]
Thank you very much for your quick response!

I now had a deeper look into the issue and realised: the problem lied on the DHCP server side.
(i.e. the DHCP servers could resolve the names - but were resolving to 127.0.0.1. I didn't realise this in the first step and were searching for a solution on the fmDHCP side - and tried to "get it to use IP-Adresses" by entering the addresses in the UI - but as you mentioned: as long as the frontend can resolve the names it will take the names and put it into the config. That's the point I "got lost" and cried for help :)

Thank you - issue resolved + sry bothering you.
