### ISSUE TITLE
[BUG] It is not possible to create a secondary zone (forward or reverse), but the master is specified.

### ISSUE THREAD

**Issue by neutrolino** [WillyXJ/facileManager#631]
fM Version : v4.6.2
fmDNS v6.0.5

Debian 12 (Bookworm)
PHP 8.2.93
Apache 2.4.57-2

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

I create secundary reverse (or forward) zone:
![изображение](https://github.com/WillyXJ/facileManager/assets/68535525/af3d491f-32dd-4cd3-82ed-808a7548697f)
Click "Save"

Results, I get a warning:
![изображение](https://github.com/WillyXJ/facileManager/assets/68535525/5974ff95-0c62-4363-8773-bce3368f4c5e)

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 6.0.6](https://www.facilemanager.com/modules/fmdns/) and later.
