### ISSUE TITLE
ERROR VIEW DYNAMIC ZONE

### ISSUE THREAD

**Issue by nikpael** [WillyXJ/facileManager#637]
Please prefix your issue title with one of the following: [BUG]

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.7.o**
<Specify Module Name> Version : **6.2.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
view a change of dynamic zone

**(BUG | ISSUE) Actual Behavior:**
error:
show error: Warning: Undefined property: stdClass::$server_serial_no in /var/www/html/fmanager/fm-modules/fmDNS/functions.php on line 703
An error occured retrieving the associated servers from the database. Could not find any active [name servers](http://manager.xx.it/config-servers.php) for this zone.
![image](https://github.com/user-attachments/assets/4bc9e5ec-e2ab-46c8-8c1b-dce6598b30dc)

**(BUG | ISSUE) Steps to reproduce:**
open a dynamic zone

{replace this line with your issue content}
with the previus version worked fine

**Comment by WillyXJ** [comment]
I'm trying to reproduce this.  Would you please provide whether your dynamic zone is configured with "All Servers" or specific ones?  If specific, is it a group or individual? How many individual servers?

**Comment by nikpael** [comment]
> I'm trying to reproduce this. Would you please provide whether your dynamic zone is configured with "All Servers" or specific ones? If specific, is it a group or individual? How many individual servers?
> 
> Also, what previous version did you have that worked?

the dynamic zone is configured with a server group where inside there is 1 primary 2 secondaries

**Comment by WillyXJ** [comment]
This appears to have broken with 6.0.0 when updating the nomenclatures from "masters/slaves" to "primaries/secondaries". Until a new version is released, you can manually update server/fm-modules/fmDNS/functions.php line 694 from:

`function getZoneServers($domain_id, $server_types = array('primaries')) {`

to

`function getZoneServers($domain_id, $server_types = array('masters')) {`

**Comment by WillyXJ** [comment]
This is now fixed in [fmDNS 7.0-beta1](https://www.facilemanager.com/modules/fmdns/?t=3) and later.
