### ISSUE TITLE
User permission granularity with zones and records

### ISSUE THREAD

**Issue by WillyXJ** [WillyXJ/facileManager#7]
It would be nice to add more granularity to the fmDNS permissions so users can only manage records and zones for a select number of zones rather than all.

For instance, the following zones are hosted by fmDNS:

domain.com
mydomain.com
example.com

UserA only needs access to manage zones domain.com and mydomain.com while UserB only needs to manage the records of example.com.

**Comment by chamambom** [comment]
I am using fmdns 1.3 and facilemanger1.3 , i am trying to get specific users to manage certain zones and records but when i select one zone record ,it restricts all access, can you help

**Comment by WillyXJ** [comment]
Hi @chamambom,

Would you be able to give me reproducible steps or are you experiencing what was reported in #162?

Thanks.

**Comment by chamambom** [comment]
I saw the case #162 and i saw that the fmdns version is 1.3.3 , and
im running version 1.3 ,is there any difference and do i need update ??

**Comment by WillyXJ** [comment]
Yes, always upgrade to the latest version before opening a ticket as they contain bug fixes.
