### ISSUE TITLE
admin-modules.php not found

### ISSUE THREAD

**Issue by lordmuffin** [WillyXJ/facileManager#95]
After figuring out how to do a new server install, i managed to get through setting it up, creating a user.  And now every time i load it up it redirects to /admin-modules.php and it cannot be found.  Obviously because it doesn't exist.  What am i missing here?

**Comment by andrerdrummond** [comment]
Guys, I had the same problem. My .htaccess contains this information:

<IfModule mod_headers.c>
        <FilesMatch "\.(js|css|txt)$">
                Header set Cache-Control "max-age=7200"
        </FilesMatch>
        <FilesMatch "\.(jpe?g|png|gif|ico)$">
                Header set Cache-Control "max-age=2592000"
        </FilesMatch>
</IfModule>

<IfModule mod_rewrite.c>
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
</IfModule>

But I am always getting this message: Not Found

The requested URL /facileManager/admin-modules.php was not found on this server.

What I need to do?

**Comment by WillyXJ** [comment]
@andrerdrummond what is your server environment?

**Comment by andrerdrummond** [comment]
I'm using a CentOS 6.6

**Comment by WillyXJ** [comment]
@andrerdrummond What version of facileManager and apache are you using?  Do you have a virtualhost defined for this?  If so, are you allowing rewrites with it?

**Comment by andrerdrummond** [comment]
I'm using these:
facileManager: 2.0.3
Apache:  Server version: Apache/2.2.15 (Unix) / Server built:   Oct 16 2014 14:45:47.
No virtualhost defined, I'm using a virtualmachine with webservice just to FacileManager.

I the file httpd.conf there is a line to load the rewrites: LoadModule rewrite_module modules/mod_rewrite.so

**Comment by WillyXJ** [comment]
In your httpd.conf you should have a `<Directory>` directive and inside can you confirm you have the following?

`AllowOverride All`

**Comment by andrerdrummond** [comment]
OMG!!! Thanks a lot. It worked.

**Comment by WillyXJ** [comment]
Glad to hear it.
