### ISSUE TITLE
Import multiple zones simultaneously. 

### ISSUE THREAD

**Issue by framirezu** [WillyXJ/facileManager#96]
Hello. 

I manage several servers with DNS zones created around 2000, and I would like to migrate this information into fmdns. 
I have been researching and using "rndc dumpdb" and some "bash script" I can create "inserts" into the database. 
But before I try to develop this, Do you have any script or tool for this case?. Could you help me telling me which tables are would have to insert?. I've found 3 so far. (fm_dns_domains, fm_dns_records, fm_dns_soa) 

Thank you for your attention and for your great work.

PD. sorry for my poor english.

**Comment by WillyXJ** [comment]
The zone import wizard now includes this in [3.0-alpha1](http://www.facilemanager.com/download/?t=4) and later.

**Comment by WillyXJ** [comment]
This is now included in [3.0](http://www.facilemanager.com/download/) and later.
